Causeview Package Complete/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Organization_ID__c</fullName>
        <description>Organization ID</description>
        <externalId>true</externalId>
        <label>Organization ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Fund_Name__c</fullName>
        <description>Displays name for Fund populated in Lookup field</description>
        <formula>HYPERLINK(&quot;/&quot; &amp;   Fund__r.Id  , Fund__r.Fund_Name__c, &quot;_self&quot; )</formula>
        <label>Fund Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fund__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The designated Fund the Appeal is prompting for</description>
        <inlineHelpText>The designated Fund the Appeal is prompting for</inlineHelpText>
        <label>Fund</label>
        <referenceTo>Fund__c</referenceTo>
        <relationshipLabel>Campaigns/Appeals</relationshipLabel>
        <relationshipName>CampaignsAppeals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Letter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Selected letter that will be sent to donors when donating to this appeal or event Actionpage</description>
        <inlineHelpText>Selected letter that will be sent to donors when donating to this appeal/event Actionpage</inlineHelpText>
        <label>Letter</label>
        <referenceTo>Letter__c</referenceTo>
        <relationshipLabel>Appeals/Events</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Appeal</fullName>
        <active>true</active>
        <description>A request for funds</description>
        <label>Appeal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>A gathering of constituents for the purpose of fundraising or support</description>
        <label>Event</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Fund__c.object
<CustomObject>
    <description>Causeview - Captures your organization&apos;s funds.</description>
    <fields>
        <fullName>Fund_Name__c</fullName>
        <label>Fund Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Fund</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Fund ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Gift__c.object
<CustomObject>
    <description>Causeview - Any financial transactions including: gifts, product purchases, event registrations, membership renewals, etc.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Rollup of all payments with Status = Approved, Deposited, Refunded</description>
        <inlineHelpText>Sum of all payments with status (Approved, Deposited, Refunded)</inlineHelpText>
        <label>Approved Amount</label>
        <summarizedField>Payment__c.Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Payment__c.Status__c</field>
            <operation>equals</operation>
            <value>Approved, Deposited, Refunded, Invoiced</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Payment__c.Amount__c</field>
            <operation>notEqual</operation>
            <value>0</value>
        </summaryFilterItems>
        <summaryForeignKey>Payment__c.Donation__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Constituent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Individual</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Constituent)</relationshipLabel>
        <relationshipName>Gifts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expected_Amount__c</fullName>
        <description>Expected amount for transaction.  This does not based on payment.</description>
        <inlineHelpText>Expected amount for transaction, this is not based on the payments received.</inlineHelpText>
        <label>Expected Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gift_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gift_Type__c</fullName>
        <label>Gift Type</label>
        <picklist>
            <picklistValues>
                <fullName>One Time Gift</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Recurring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pledge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gift-in-Kind</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Sponsorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grant</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Letter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Letter</label>
        <referenceTo>Letter__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Entered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acknowledged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Letter__c.object
<CustomObject>
    <description>Causeview - Customization of Thank you/Receipt Letters (Acknowledgments).</description>
    <fields>
        <fullName>Fund_Name__c</fullName>
        <description>Name of fund to be printed on letter.</description>
        <inlineHelpText>Name of fund to be printed on letter.</inlineHelpText>
        <label>Fund Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Name of Letter</description>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Letter</label>
    <nameField>
        <displayFormat>L{0000}</displayFormat>
        <label>Letter Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Payment__c.object
<CustomObject>
    <description>Causeview - Payment records relating to a Transaction.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Constituent__c</fullName>
        <formula>IF(ISBLANK( Donation__r.Organization__c ), HYPERLINK(&quot;/&quot; &amp; Donation__r.Constituent__c, Donation__r.Constituent__r.FirstName &amp; &quot; &quot; &amp; Donation__r.Constituent__r.LastName,&quot;_self&quot;), HYPERLINK(&quot;/&quot; &amp; Donation__r.Organization__c, Donation__r.Organization__r.Name,&quot;_self&quot;))</formula>
        <label>Constituent</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Donation__c</fullName>
        <label>Transaction</label>
        <referenceTo>Gift__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Recurring_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Committed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refunded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Written Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACH Return</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Payment No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <recordTypes>
        <fullName>Refund</fullName>
        <active>true</active>
        <description>Refunded credit card payment - processed via payment gateway</description>
        <label>Refund</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/classes/TestClass.cls
@isTest
public with sharing class TestClass {

    public static testMethod void testGivingPowerUtility(){
        
        GivingPowerUtility gpu = new GivingPowerUtility();
        GivingPowerUtility.ConseqFiscalYears(new List<Date>(), 1);
        
        List<Date> dates = new List<Date>();
        dates.add(Date.today());
        dates.add(Date.today().addDays(1));
        GivingPowerUtility.ConseqFiscalYears(dates, 1);
            
        dates = new List<Date>();
        dates.add(Date.today().addDays(-365));
        dates.add(Date.today().addDays(-395));
        dates.add(Date.today().addDays(-465));
        GivingPowerUtility.ConseqFiscalYears(dates, 1);
        
        dates = new List<Date>();
        dates.add(Date.today().addDays(-366));
        dates.add(Date.today().addDays(-732));
        dates.add(Date.today().addDays(-1098));
        GivingPowerUtility.ConseqFiscalYears(dates, 1);
        
        GivingPowerUtility.findSobjectType('Temp');
        GivingPowerUtility.setFieldValue(new causeview__Gift__c(), 'causeview__Anonymous__c', 'Boolean', 'true');
        GivingPowerUtility.setFieldValue(new Contact(), 'Birthdate', 'Date', '10/10/1988');
        //GivingPowerUtility.setFieldValue(new Contact(), 'Name', 'DateTime', '10/10/1988');
        //GivingPowerUtility.setFieldValue(new causeview__Gift__c(), 'causeview__No_of_Expected_Payments__c', 'Double', '6');
        //GivingPowerUtility.setFieldValue(new causeview__Gift__c(), 'causeview__No_of_Expected_Payments__c', 'Int', '3');
        //GivingPowerUtility.setFieldValue(new Contact(), 'Name', 'String', 'Juan');
        
        GivingPowerUtility.IsEmptyOrNull('');
        
        Date currentDate = Date.today();
        DateTime currentDateTime = DateTime.now();
        
        GivingPowerUtility.formatDateForQuery(currentDate);
        GivingPowerUtility.formatDateTimeForQuery(currentDateTime);
        causeview__BatchSettings__c bs = new causeview__BatchSettings__c ();
        bs.Name = 'Default';
        bs.causeview__GatewayUrl__c = '';
        bs.causeview__BatchFormID__c = 'a';
        bs.causeview__BatchReportId__c = 'a';
        bs.causeview__BucketAccountId__c = 'a';
        bs.causeview__CurrencyCode__c = 'USD';
        bs.causeview__Data_Migration_Mode__c = false;
        bs.causeview__GatewayUrl__c = 'http://localhost/';
        bs.causeview__RegularGiftRecordTypeId__c = 'a';
        bs.causeview__Unknown_Guest_Id__c = 'a';
        insert bs;
        //Util.SubmitRecurringChanges('bcg', 'dfszf');
    }
    
    public static testMethod void testGiftBatchController(){
        
        //GiftBatchController cbg = new GiftBatchController();
        
    }
    public static testMethod void testPayment()
    {
        Map<String, String> rtypes_Map = new Map<String, String>();
        for(RecordType r : [Select Name, Id From RecordType where (Name = 'Gift' OR Name = 'Event' OR Name = 'Matching Gift' OR Name = 'Campaign' OR Name = 'Appeal' OR Name = 'Event' OR Name = 'Refund') AND NamespacePrefix = 'causeview']){
            rtypes_Map.put(r.Name, r.Id);
        }
        
        Fund__c fund = new Fund__c(Fund_Name__c = 'Test fund123');
        insert fund;
        Letter__c letter = new Letter__c(Name__c = 'Letter test123');
        insert letter;
         Account a = new Account(Name = 'sdsd', Organization_Id__c = 'ORG-11');
        insert a;
        Contact c = new Contact(LastName = 'asagafgh', AccountId = a.Id);
        insert c; 
        causeview__BatchSettings__c cs2 = new causeview__BatchSettings__c( Name = 'Default', causeview__BatchFormID__c = 'sadas',   causeview__BatchReportId__c = 'asdasd', causeview__RegularGiftRecordTypeId__c = rtypes_Map.get('Gift'), causeview__BucketAccountId__c = a.Id,    causeview__CurrencyCode__c = 'CAD', causeview__GatewayUrl__c = 'asdasd');        
        insert cs2;
        Gift__c g1 = new Gift__c(Constituent__c = c.Id, Expected_Amount__c = 100, Gift_Type__c = 'One Time Gift', Gift_Date__c = Date.Today());
        insert g1;
        Payment__c p1 = new Payment__c(Donation__c = g1.Id, Amount__c = 100, Status__c = 'Approved');
        insert p1;
        apexpages.currentpage().getparameters().put('id' , p1.id);
        Payment pay = new Payment(g1.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(p1);
        Payment p = new Payment(sc);
        Payment.BatchAllocationSetting batchAlloc = new Payment.BatchAllocationSetting();
        Payment.BatchAllocationSetting batchAlloc1 = new Payment.BatchAllocationSetting(fund.id, letter.id);
        //pay.submitPayment();
        pay.setKeyPrefix();
        pay.tryParseToInt('2');
        pay.setPaymentFieldList();
        pay.setAllocationFieldList();
        pay.setPayment();
        pay.setAllocationList();
        pay.getGiftDetailstoUpdate();
        pay.setAllocationOperationList();
        pay.saveAll();
    }
    public static testMethod void CampaignDashboardControllerTest()
    {
        Fund__c fund = new Fund__c(Fund_Name__c = 'Test fund123');
        insert fund;
        Letter__c letter = new Letter__c(Name__c = 'Letter test123');
        insert letter;
        RecordType recType=[SELECT Id FROM RecordType WHERE SobjectType = 'Campaign' AND Name = 'Appeal' limit 1];
        Campaign appeal = new Campaign(Name = 'Campaign Test123', Fund__c = fund.id, Letter__c = letter.id, RecordTypeId=recType.id );
        insert appeal;
        Contact con = new COntact(LastName = 'Test Contact123');
        insert con;
        ApexPages.StandardController sc = new ApexPages.StandardController(appeal);
        apexpages.currentpage().getparameters().put('id' , appeal.id);
        CampaignDashboardController campDash = new CampaignDashboardController(sc);
        
        CustomFundLookupController CFL = new CustomFundLookupController();
        CustomFundLookupController CFL1 = new CustomFundLookupController('Fund');
        system.currentPageReference().getParameters().put('objName','Account');
        CFL1.search();
    }

}