Causeview Package Complete/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Organization_ID__c</fullName>
        <description>Organization ID</description>
        <externalId>true</externalId>
        <label>Organization ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/App_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Causeview settings specific to each customer such as recordtype Ids</description>
    <fields>
        <fullName>Actionpages_URL__c</fullName>
        <defaultValue>&quot;https://actionpage.causeview.com/Default.aspx&quot;</defaultValue>
        <description>Used by Actionpage Designer to reference Actionpages.</description>
        <inlineHelpText>Used by Actionpage Designer to reference Actionpages.</inlineHelpText>
        <label>Actionpages URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Appeal_Donate_Now_Form_Id__c</fullName>
        <description>Client donation Actionform used as the Appeal Fundraising template for Actionpage Designer.</description>
        <inlineHelpText>Client donation Actionform used as the Appeal Fundraising template for Actionpage Designer.</inlineHelpText>
        <label>Appeal Fundraising Form Id</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Appeal_RecordType_Id__c</fullName>
        <description>The RecordTypeId of a Causeview Campaign of type &quot;Appeal&quot;</description>
        <inlineHelpText>The RecordTypeId of a Causeview Campaign of type &quot;Appeal&quot;</inlineHelpText>
        <label>Appeal RecordType Id</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CV_Account_Id__c</fullName>
        <description>Causeview customer ID.  18 digit alphanumeric ID.</description>
        <inlineHelpText>Causeview customer ID.  18 digit alphanumeric ID.</inlineHelpText>
        <label>Causeview Account Id</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_RecordType_Id__c</fullName>
        <description>The RecordTypeId of a Causeview Campaign of type &quot;Campaign&quot;</description>
        <inlineHelpText>The RecordTypeId of a Causeview Campaign of type &quot;Campaign&quot;</inlineHelpText>
        <label>Campaign RecordType Id</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Actionpages_Campaign__c</fullName>
        <description>Default Appeal record that Actionforms will allocate to if no Appeal or Event is assigned.</description>
        <inlineHelpText>Default Appeal record that Actionforms will allocate to if no Appeal or Event is assigned.</inlineHelpText>
        <label>Default Actionpages Appeal</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enable_Recurring_Receipts__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This feature is to enable the receipt creation for gift type as recurring.
Default is unchecked</description>
        <inlineHelpText>Enable it if you want receipt to be created for recurring</inlineHelpText>
        <label>Enable Recurring Receipts</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event_RecordType_Id__c</fullName>
        <description>The RecordTypeId of a Causeview Campaign of type &quot;Event&quot;</description>
        <inlineHelpText>The RecordTypeId of a Causeview Campaign of type &quot;Event&quot;</inlineHelpText>
        <label>Event RecordType Id</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Registration_Form_Id__c</fullName>
        <description>Recordtype Id for Individual Application on the Volunteer Applications object.</description>
        <inlineHelpText>Causeview Actionform Id - used by Actionform Designer as paid event form template</inlineHelpText>
        <label>Paid Event Registration Form Id</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_URL__c</fullName>
        <defaultValue>&quot;https://api.causeview.com/form/v2.1/&quot;</defaultValue>
        <description>URL that points to the Actionforms.  Used by Actionpage Designer.</description>
        <inlineHelpText>URL that points to the Actionforms.  Used by Actionpage Designer.</inlineHelpText>
        <label>Actionform URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Free_Event_Registration_Form_Id__c</fullName>
        <description>Client event registration Actionform used as the Free Event template for Actionpage Designer.</description>
        <inlineHelpText>Client event registration Actionform used as the Free Event template for Actionpage Designer.</inlineHelpText>
        <label>Free Event Registration Form Id</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Individual_App_RecordtypeId__c</fullName>
        <description>Recordtype Id for Individual Application on the Volunteer Applications object.</description>
        <inlineHelpText>Recordtype Id for Individual Application on the Volunteer Applications object.</inlineHelpText>
        <label>Individual Volunteer App Recordtype Id</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Causeview App Settings</label>
</CustomObject>

Causeview Package Complete/src/objects/BatchSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Causeview batch processing settings.</description>
    <fields>
        <fullName>BatchFormID__c</fullName>
        <description>Customer Batch Actionform Id.  Used by internal payment processing features.</description>
        <inlineHelpText>Customer Batch Actionform Id.  Used by internal payment processing features.</inlineHelpText>
        <label>Batch Form Id</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BatchReportId__c</fullName>
        <label>Batch Report ID</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BucketAccountId__c</fullName>
        <label>Bucket Account ID</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CurrencyCode__c</fullName>
        <label>Currency Code</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Migration_Mode__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox determines how the system behaves, much like a DEBUG mode.</description>
        <inlineHelpText>For CauseView use only. DO NOT CHECK OR MODIFY.</inlineHelpText>
        <label>Data Migration Mode</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GatewayUrl__c</fullName>
        <defaultValue>&quot;https://api.causeview.com/v2.1/Gateway.asmx&quot;</defaultValue>
        <description>URL used to connect to customer payment gateway via Causeview Actionengine.</description>
        <inlineHelpText>URL used to connect to customer payment gateway via Causeview Actionengine.</inlineHelpText>
        <label>Payment Gateway URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>RegularGiftRecordTypeId__c</fullName>
        <description>RecordType Id for Gift on the Transaction object.</description>
        <inlineHelpText>RecordType Id for Gift on the Transaction object.</inlineHelpText>
        <label>Transaction Gift RecordType ID</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Batch Settings</label>
</CustomObject>

Causeview Package Complete/src/objects/Gift__c.object
<CustomObject>
    <description>Causeview - Any financial transactions including: gifts, product purchases, event registrations, membership renewals, etc.</description>
    <fields>
        <fullName>Constituent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Individual</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Constituent)</relationshipLabel>
        <relationshipName>Gifts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gift_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gift_Type__c</fullName>
        <label>Gift Type</label>
        <picklist>
            <picklistValues>
                <fullName>One Time Gift</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Recurring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pledge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gift-in-Kind</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Sponsorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grant</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Recurring_Donation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recurring Gift</label>
        <referenceTo>Recurring_Donation__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Entered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acknowledged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Recurring_Donation__c.object
<CustomObject>
    <description>Causeview - Captures recurring gifts</description>
    <fields>
        <fullName>Constituent__c</fullName>
        <label>Constituent</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recurring Gifts</relationshipLabel>
        <relationshipName>Recurring_Donations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Recurring Gift</label>
    <nameField>
        <displayFormat>RD-{00000}</displayFormat>
        <label>Recurring Gift No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Gifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/classes/ContactHistoryControllerTestclass.cls
@isTest
public class ContactHistoryControllerTestclass{
 public static testMethod void ContactHistoryControllerTestclass(){
 
     App_Settings__c app = new App_Settings__c(Appeal_RecordType_Id__c = '123', Campaign_RecordType_Id__c = '123', 
            Event_RecordType_Id__c = '123', Actionpages_URL__c = 'www.example.com', Appeal_Donate_Now_Form_Id__c = 'sdfd', Event_Registration_Form_Id__c = 'dsf',
            Form_URL__c = 'www.example.com', Free_Event_Registration_Form_Id__c = 'gfdf', CV_Account_Id__c = '123', Default_Actionpages_Campaign__c = 'jdksf',
            Individual_App_RecordtypeId__c = '123', Enable_Recurring_Receipts__c = false);
        insert app;
        
        RecordType rtypes = [Select Name, Id From RecordType where Name = 'Gift' AND NamespacePrefix = 'causeview' LIMIT 1];  
        Account a = new Account(Name = 'sdsd', Organization_Id__c = 'ORG-11');
        insert a;  
        BatchSettings__c cs2 = new BatchSettings__c( Name = 'Default', Data_Migration_Mode__c = false, BatchFormID__c = 'sadas',   BatchReportId__c = 'asdasd', RegularGiftRecordTypeId__c = rtypes.Id, BucketAccountId__c = a.Id, CurrencyCode__c = 'CAD', GatewayUrl__c = 'asdasd');        
        insert cs2;
        
        Contact contacts = new Contact();
        contacts.LastName = 'Constituent Test';
        Insert contacts;
        
         String ContactIdurl =contacts.Id;
        
         /* Gift__c gift1 = new Gift__c();
        //gift1.Recurring_Donation__c = recurringGift1.Id;
        gift1.Status__c = 'Active';
        gift1.Constituent__c = contacts.Id;
        gift1.Gift_Date__c = Date.newinstance(2015, 2, 17);
        gift1.Gift_Type__c  = 'one time';
        Insert gift1; */
       
       Gift__c g = testMapping.createGift(contacts);
       ApexPages.StandardController sc = new ApexPages.standardController(g);
       ContactHistoryController c1 = new ContactHistoryController(sc);
 
       c1.loadGivingByYear(contacts.Id);
 
 
    }
}