Causeview Package Complete/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>Default organization email address.</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Gift__c.object
<CustomObject>
    <description>Causeview - Any financial transactions including: gifts, product purchases, event registrations, membership renewals, etc.</description>
    <fields>
        <fullName>Constituent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Individual</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Constituent)</relationshipLabel>
        <relationshipName>Gifts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gift_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gift_Type__c</fullName>
        <label>Gift Type</label>
        <picklist>
            <picklistValues>
                <fullName>One Time Gift</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Recurring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pledge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gift-in-Kind</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Sponsorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grant</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Receipt__c.object
<CustomObject>
    <description>Causeview - Tax receipt for transaction records.</description>
    <fields>
        <fullName>Amount_Receipted__c</fullName>
        <description>Amount of gift that is receipted.</description>
        <inlineHelpText>Populate if you would like to provide a specific dollar amount.  This will override all other calculations and set the Receipt Amount to your input.</inlineHelpText>
        <label>Custom Receipt Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Constituent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Captures the constituent ID for email receipting purposes.  Hidden to end users.</description>
        <label>Constituent</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gift_Type__c</fullName>
        <description>Type of gift received</description>
        <formula>TEXT(Gift__r.Gift_Type__c)</formula>
        <inlineHelpText>Type of gift received</inlineHelpText>
        <label>Gift Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gift__c</fullName>
        <label>Gift</label>
        <referenceTo>Gift__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Organization that receipt is issued to</description>
        <inlineHelpText>Organization that receipt is issued to</inlineHelpText>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Receipt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <recordTypes>
        <fullName>Void</fullName>
        <active>true</active>
        <description>Void receipt</description>
        <label>Void</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/classes/testupdateConstAndOrgLookupsTrigger.cls
@isTest
class testupdateConstAndOrgLookupsTrigger {
    static testMethod void testTrigger() {
        RecordType rtypes = [Select Name, Id From RecordType where Name = 'Gift' AND NamespacePrefix = 'causeview' LIMIT 1];        

        Contact c = new Contact(lastName='testContact', Email='test@contact.com');
        Insert c;
        Account a = new Account(name='testAccount', Email__c='test@account.com');
        Insert a;
        
        causeview__BatchSettings__c cs2 = new causeview__BatchSettings__c( Name = 'Default', causeview__BatchFormID__c = 'sadas',   causeview__BatchReportId__c = 'asdasd', causeview__RegularGiftRecordTypeId__c = rtypes.Id, causeview__BucketAccountId__c = a.Id,    causeview__CurrencyCode__c = 'CAD', causeview__GatewayUrl__c = 'asdasd');        
        insert cs2;
        Gift__c d1 = new Gift__c(Gift_Type__c='One Time Gift', Gift_Date__c=System.today(), Constituent__c=c.Id, Organization__c=null); 
        Insert d1;
        Gift__c d2 = new Gift__c(Gift_Type__c='One Time Gift', Gift_Date__c=System.today(), Constituent__c=null, Organization__c=a.Id); 
        Insert d2;

        Test.startTest();

        Receipt__c r1 = new Receipt__c(Gift__c=d1.Id);
        Insert r1;
        r1.Amount_Receipted__c = 100;
        Update r1;

        Receipt__c r2 = new Receipt__c(Gift__c=d2.Id);
        Insert r2;

        Test.stopTest();
    }
}