Causeview Package Complete/src/objects/App_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Causeview settings specific to each customer such as recordtype Ids</description>
    <fields>
        <fullName>Appeal_Donate_Now_Form_Id__c</fullName>
        <description>Client donation Actionform used as the Appeal Fundraising template for Actionpage Designer.</description>
        <inlineHelpText>Client donation Actionform used as the Appeal Fundraising template for Actionpage Designer.</inlineHelpText>
        <label>Appeal Fundraising Form Id</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Appeal_RecordType_Id__c</fullName>
        <description>The RecordTypeId of a Causeview Campaign of type &quot;Appeal&quot;</description>
        <inlineHelpText>The RecordTypeId of a Causeview Campaign of type &quot;Appeal&quot;</inlineHelpText>
        <label>Appeal RecordType Id</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CV_Account_Id__c</fullName>
        <description>Causeview customer ID.  18 digit alphanumeric ID.</description>
        <inlineHelpText>Causeview customer ID.  18 digit alphanumeric ID.</inlineHelpText>
        <label>Causeview Account Id</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_RecordType_Id__c</fullName>
        <description>The RecordTypeId of a Causeview Campaign of type &quot;Campaign&quot;</description>
        <inlineHelpText>The RecordTypeId of a Causeview Campaign of type &quot;Campaign&quot;</inlineHelpText>
        <label>Campaign RecordType Id</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Actionpages_Campaign__c</fullName>
        <description>Default Appeal record that Actionforms will allocate to if no Appeal or Event is assigned.</description>
        <inlineHelpText>Default Appeal record that Actionforms will allocate to if no Appeal or Event is assigned.</inlineHelpText>
        <label>Default Actionpages Appeal</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_RecordType_Id__c</fullName>
        <description>The RecordTypeId of a Causeview Campaign of type &quot;Event&quot;</description>
        <inlineHelpText>The RecordTypeId of a Causeview Campaign of type &quot;Event&quot;</inlineHelpText>
        <label>Event RecordType Id</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Registration_Form_Id__c</fullName>
        <description>Recordtype Id for Individual Application on the Volunteer Applications object.</description>
        <inlineHelpText>Causeview Actionform Id - used by Actionform Designer as paid event form template</inlineHelpText>
        <label>Paid Event Registration Form Id</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Free_Event_Registration_Form_Id__c</fullName>
        <description>Client event registration Actionform used as the Free Event template for Actionpage Designer.</description>
        <inlineHelpText>Client event registration Actionform used as the Free Event template for Actionpage Designer.</inlineHelpText>
        <label>Free Event Registration Form Id</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Individual_App_RecordtypeId__c</fullName>
        <description>Recordtype Id for Individual Application on the Volunteer Applications object.</description>
        <inlineHelpText>Recordtype Id for Individual Application on the Volunteer Applications object.</inlineHelpText>
        <label>Individual Volunteer App Recordtype Id</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_Address_Trigger_Setting__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Enable Other Address Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Public_Free_Event_Registration_Form_Id__c</fullName>
        <defaultValue>&quot;NA&quot;</defaultValue>
        <description>Actionform Id used for public facing registrations.  Field is deprecated post Causeview v1.919.</description>
        <inlineHelpText>Actionform Id used for public facing registrations.  Field is deprecated post Causeview v1.919.</inlineHelpText>
        <label>(deprecated) Public Free Event Form Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Use_Workflows_for_Sending_Receipts__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, the system will use workflows to send email receipts instead of the Causeview trigger.  If this is enabled, the receipt template can no longer use Recipient merge fields, only RelatedTo merge fields can be used.</description>
        <inlineHelpText>If checked, the system will use workflows to send email receipts instead of the Causeview trigger.  If this is enabled, the receipt template can no longer use Recipient merge fields, only RelatedTo merge fields can be used.</inlineHelpText>
        <label>Use Workflows for Sending Receipts</label>
        <type>Checkbox</type>
    </fields>
    <label>Causeview App Settings</label>
</CustomObject>

Causeview Package Complete/src/objects/BatchSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Causeview batch processing settings.</description>
    <fields>
        <fullName>BatchFormID__c</fullName>
        <description>Customer Batch Actionform Id.  Used by internal payment processing features.</description>
        <inlineHelpText>Customer Batch Actionform Id.  Used by internal payment processing features.</inlineHelpText>
        <label>Batch Form Id</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BatchReportId__c</fullName>
        <label>Batch Report ID</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BucketAccountId__c</fullName>
        <label>Bucket Account ID</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CurrencyCode__c</fullName>
        <label>Currency Code</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type_Id_for_Rollups__c</fullName>
        <description>Matching gift record type Id to be included in Gift related roll up for Individuals and Organizations.</description>
        <inlineHelpText>Matching gift record type Id to be included in Gift related roll up for Individuals and Organizations.</inlineHelpText>
        <label>Record Type Id for Giving Rollups</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RegularGiftRecordTypeId__c</fullName>
        <description>RecordType Id for Gift on the Transaction object.</description>
        <inlineHelpText>RecordType Id for Gift on the Transaction object.</inlineHelpText>
        <label>Transaction Gift RecordType ID</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unknown_Guest_Id__c</fullName>
        <defaultValue>&quot;NA&quot;</defaultValue>
        <description>Record Id of Unknown Guest contact record.  Used with event registrations.  This field is deprecated post Causeview v1.936.</description>
        <inlineHelpText>Record Id of Unknown Guest contact record.  Used with event registrations.  This field is deprecated post Causeview v1.936.</inlineHelpText>
        <label>(deprecated) Unknown Guest Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Batch Settings</label>
</CustomObject>

Causeview Package Complete/src/objects/givingpowerSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Causeview communication and notification templates.</description>
    <fields>
        <fullName>ConsolidatedReceiptEmailTemplateId__c</fullName>
        <label>Consolidated Receipt Email Template ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConsolidatedReceiptPDFDocId__c</fullName>
        <inlineHelpText>The ID of the HTML Document used as Consolidated Receipt&apos;s PDF Template</inlineHelpText>
        <label>Consolidated Receipt PDF Document Id</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consolidated_Receipt_Email_Document_Id__c</fullName>
        <description>Consolidated Receipt Email Document Id</description>
        <label>Consolidated Receipt Email Document Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DupeAttachTemplateId__c</fullName>
        <label>Duplicate Receipt PDF Document Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DupeConsolidatedReceiptEmailTempId__c</fullName>
        <label>Dupe Consolidated Receipt Email Temp Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DupeConsolidatedReceiptPDFDocId__c</fullName>
        <label>Dupe Consolidated Receipt PDF Doc Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DupeDocumentTemplateId__c</fullName>
        <label>Duplicate Receipt Email Document Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DupeEmailTemplateId__c</fullName>
        <label>Duplicate Email Template ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dupe_Event_Registration_Email_Doc_ID__c</fullName>
        <description>Duplicate event registration email content document ID (Salesforce ID)</description>
        <inlineHelpText>Duplicate event registration email content document ID (Salesforce ID)</inlineHelpText>
        <label>Dupe Event Registration Email Doc ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dupe_Event_Registration_Template_ID__c</fullName>
        <description>Event registration communication template ID (Salesforce ID) - duplicate/replacement template</description>
        <inlineHelpText>Event registration communication template ID (Salesforce ID) - duplicate/replacement template</inlineHelpText>
        <label>Dupe Event Registration Template ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmailTemplateId__c</fullName>
        <inlineHelpText>The Id of the Visualforce Email Template</inlineHelpText>
        <label>Email Template ID</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Registration_Email_Doc_ID__c</fullName>
        <description>Event registration email content document ID (Salesforce ID)</description>
        <inlineHelpText>Event registration email content document ID (Salesforce ID)</inlineHelpText>
        <label>Event Registration Email Doc ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Registration_Email_Template_ID__c</fullName>
        <description>Event registration communication template ID (Salesforce ID)</description>
        <inlineHelpText>Event registration communication template ID (Salesforce ID)</inlineHelpText>
        <label>Event Registration Email Template ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_Wide_Email_ID__c</fullName>
        <description>The Salesforce ID of the Organization Wide Email address you would like your Automatic receipting messages to come from.</description>
        <inlineHelpText>The Salesforce ID of the Organization Wide Email address you would like your Automatic receipting messages to come from.</inlineHelpText>
        <label>Org Wide Email ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReceiptEmailDocId__c</fullName>
        <inlineHelpText>The ID of the document (set as public) used for Receipt Email Template</inlineHelpText>
        <label>Receipt Email Document Id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReceiptPDFDocId__c</fullName>
        <inlineHelpText>The ID of the HTML Document used as Receipt&apos;s PDF Template</inlineHelpText>
        <label>Receipt PDF Document Id</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X15_DAYS_CC_Expiry_Email_Template__c</fullName>
        <description>Template used to send to donor when today is 15 days before credit card expiry date.</description>
        <inlineHelpText>Populate with Salesforce email template Id. Template used to send to donor when today is 15 days before credit card expiry date.</inlineHelpText>
        <label>15 DAYS - CC Expiry Email Template</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X30_DAYS_CC_Expiry_Email_Template__c</fullName>
        <description>Template used to send to donor when today is 30 days before credit card expiry date.</description>
        <inlineHelpText>Populate with Salesforce email template Id. Template used to send to donor when today is 30 days before credit card expiry date.</inlineHelpText>
        <label>30 DAYS - CC Expiry Email Template</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Causeview Receipt Templates</label>
</CustomObject>

Causeview Package Complete/src/classes/CauseViewCustomSetting.cls
/**
 * @Class CauseViewCustomSetting
 * Description : To auto create the record for the custom settings listed below
 *               1.Auto Number Counts 
 2. Batch Settings 3. Causeview App Settings  4. Causeview Templates
 *
 */

global class CauseViewCustomSetting
{

 /**
 * @Method defaultANumSettings
 * Description : To create the default record for Auto Number Counts
 *               name with value default and rest values are fields default value.
 *
 */
  global static void defaultANumSettings()
  {
     if(aNums__c.getInstance('Default') == null)
       {  
        aNums__c  aNum = new aNums__c();
        aNum.Name = 'Default';

            try
            {
                insert aNum;
                system.debug('ANumSettings created successfully');
            }    
            catch(System.DMLException e) 
            {
                emailUserAnError(e.getMessage());
            }  
      }
      causeview__aNums__c s = causeview__aNums__c.getInstance('Default');  
      List<causeview__Application_Setting__c> autonumberRecord = new List<causeview__Application_Setting__c>(); 
      autonumberRecord = [select Name, causeview__Org_Count__c from causeview__Application_Setting__c where Name =: 'Auto Number Setting' Limit 1];    //Auto Number Setting
      if(s != null){
          if(s.causeview__OrgCount__c != 0){
              if(autonumberRecord.size() > 0){
                  for(causeview__Application_Setting__c appSetting : autonumberRecord){
                      if(appSetting.causeview__Org_Count__c == 0){
                          appSetting.causeview__Org_Count__c = s.causeview__OrgCount__c;
                      }
                  }
              }else
              {
                  causeview__Application_Setting__c app = new causeview__Application_Setting__c();
                  app.Name = 'Auto Number Setting';
                  app.causeview__Org_Count__c = s.causeview__OrgCount__c;
                  try
                  {
                      insert app;
                      system.debug('Application setting created successfully');
                  }
                  catch(System.DMLException e) 
                  {
                      emailUserAnError(e.getMessage());
                  }
              }
          }else
          {
              if(!(autonumberRecord.size() > 0)){
                  causeview__Application_Setting__c app = new causeview__Application_Setting__c();
                  app.Name = 'Auto Number Setting';
                  app.causeview__Org_Count__c = s.causeview__OrgCount__c;
                  try
                  {
                      insert app;
                      system.debug('Application setting created successfully');
                  }
                  catch(System.DMLException e) 
                  {
                      emailUserAnError(e.getMessage());
                  }
              }
          }
      }
  }

/**
 * @Method defaultBatchSettings
 * Description : To create the default record for Batch Settings.
 */ 
 global static void defaultBatchSettings()
  {
     if((BatchSettings__c.getInstance('Default') == null))
       {  
        BatchSettings__c batchSettings = new BatchSettings__c ();
        batchSettings.Name = 'Default';
        batchSettings.CurrencyCode__c = UserInfo.getDefaultCurrency();
        batchSettings.BatchFormID__c = 'TBD';
        batchSettings.BatchReportId__c = getObjectId( 'Report' ,  'Gift Batch Summary Report' );
        batchSettings.BucketAccountId__c = createObject('Account', null , 'Individual');
        batchSettings.Unknown_Guest_Id__c = createObject('Contact', null , 'Unknown Guest');
        batchSettings.RegularGiftRecordTypeId__c = getObjectId( 'RecordType' ,  'Gift' );
        batchSettings.Record_Type_Id_for_Rollups__c = getObjectId( 'RecordType' ,  'Matching Gift' );
            try
            {
                insert batchSettings;
                system.debug('batchSettings created successfully');

            } 
            catch(System.DMLException e) 
            {
              emailUserAnError(e.getMessage());
            }  
        }
   }
  
/**
 * @Method defaultAppSettings
 * Description : To create the default record for causeview App Settings.
 */ 
    global static void defaultAppSettings()
     {
      App_Settings__c appSetting  = App_Settings__c.getInstance(UserInfo.getOrganizationId());
        
      if((appSetting.Name == null))
       {  
        appSetting.Public_Free_Event_Registration_Form_Id__c = 'TBD';
        appSetting.Appeal_Donate_Now_Form_Id__c = 'TBD';
        appSetting.Appeal_RecordType_Id__c = getObjectId( 'RecordType' ,  'Appeal' );
        appSetting.Campaign_RecordType_Id__c = getObjectId( 'RecordType' ,  'Campaign' );
        appSetting.CV_Account_Id__c = 'TBD';
        appSetting.Default_Actionpages_Campaign__c = createObject('Campaign','Appeal', 'CV Forms');
        appSetting.Event_RecordType_Id__c =  getObjectId( 'RecordType' ,  'Event' );
        appSetting.Individual_App_RecordtypeId__c = getObjectId( 'RecordType' ,  'Individual Application' );
        appSetting.Event_Registration_Form_Id__c = 'TBD';
        appSetting.Free_Event_Registration_Form_Id__c = 'TBD';
        appSetting.Use_Workflows_for_Sending_Receipts__c = false;
        appSetting.Other_Address_Trigger_Setting__c = true;
            try
            {
                insert appSetting ;
                system.debug('App settings created successfully');
                
            } 
            catch(System.DMLException e) 
            {
              emailUserAnError(e.getMessage()); 
            }  
        }
   }
     
     
    /**
    * @Method defaultAppTemplateSettings
    * Description : To create the default record for causeview App Template Settings which includes document mapping and object
    *               creation, email templates.
    */ 
   global static void defaultAppTemplateSettings()
    {

        if(givingpowerSettings__c.getInstance('Settings') == null)
        {  
            givingpowerSettings__c givingpowerSettings= new givingpowerSettings__c();
            givingpowerSettings.Name = 'Settings';
            givingpowerSettings.DupeEmailTemplateId__c = getObjectId( 'EmailTemplate' ,  'Receipt Template (Dupe)' );
            givingpowerSettings.EmailTemplateId__c = getObjectId( 'EmailTemplate' ,  'Receipt Template');
            givingpowerSettings.X15_DAYS_CC_Expiry_Email_Template__c = getObjectId( 'EmailTemplate' ,  'Credit Card Expiry - 15 DAY Notification');
            givingpowerSettings.X30_DAYS_CC_Expiry_Email_Template__c = getObjectId( 'EmailTemplate' ,  'Credit Card Expiry - 30 DAY Notification');
            givingpowerSettings.consolidatedReceiptEmailTemplateId__c = getObjectId( 'EmailTemplate' ,  'Consolidated Receipt Email Template');
            givingpowerSettings.DupeConsolidatedReceiptEmailTempId__c = getObjectId( 'EmailTemplate' , 'Consolidated Receipt Email Template (Dupe)');
            
            givingpowerSettings.Org_Wide_Email_ID__c = getObjectId( 'OrgWideEmailAddress' ,  'HN Foundation');

            givingpowerSettings.ReceiptEmailDocId__c = getObjectId( 'Document' ,  'en_htm');
            givingpowerSettings.DupeDocumentTemplateId__c = getObjectId( 'Document' ,  'HTML_Template_for_Reciept_Email_Content_Dupe');
            givingpowerSettings.ReceiptPDFDocId__c = getObjectId( 'Document' ,  'HTMLPage2_htm');
            givingpowerSettings.DupeAttachTemplateId__c = getObjectId( 'Document' ,  'HTML_Template_for_Reciept_PDF_Dupe');
            givingpowerSettings.consolidatedReceiptPDFDocId__c = getObjectId( 'Document' ,  'HTML_Template_for_Consolidated_Receipt_PDF_Attachment');
            givingpowerSettings.DupeConsolidatedReceiptPDFDocId__c = getObjectId( 'Document' ,  'HTML_Template_for_Consolidated_Reciept_PDF_Dupe');
           
            
            givingpowerSettings.Event_Registration_Email_Doc_ID__c = getObjectId( 'Document' ,  'HTML_Template_for_Event_Registration_Email_Content');
            givingpowerSettings.Dupe_Event_Registration_Email_Doc_ID__c = getObjectId( 'Document' ,  'HTML_Template_for_Event_Registration_Email_Content_Dupe');
            givingpowerSettings.Event_Registration_Email_Template_ID__c = getObjectId( 'EmailTemplate' ,  'Event Registration Acknowledgement');
            givingpowerSettings.Dupe_Event_Registration_Template_ID__c = getObjectId( 'EmailTemplate' ,  'Event Registration Acknowledgement (Dupe)');
            
            
            givingpowerSettings.Consolidated_Receipt_Email_Document_Id__c= getObjectId( 'Document' ,  'HTML_Template_for_Consolidated_Receipt_Email_Content');
            givingpowerSettings.Consolidated_Duplicate_Receipt_Email_Doc__c= getObjectId( 'Document' ,  'HTML_Template_for_Consolidated_Receipt_Email_Content_Dupe');

                
         try
            {
                insert givingpowerSettings;
                system.debug('App Template Settings created successfully');
            } 
            catch(System.DMLException e) 
            {
                emailUserAnError(e.getMessage()); 
            }  
            system.debug('givingpowerSettings is  :'+givingpowerSettings);
        }
    }

    /*
    *   @method : getObjectId
    *   Description : To get the id of the existing records from the database based on the field name and the object
    *
    */
    global static String getObjectId(String ObjectName, String fieldValue)
    {
        String soql = 'SELECT ID FROM '+ObjectName+' WHERE Name = : fieldValue';
        
        if(ObjectName.equals('OrgWideEmailAddress'))
            soql = 'SELECT ID FROM OrgWideEmailAddress WHERE DisplayName = : fieldValue';  
       
       if(ObjectName.equals('Document'))
            soql = 'SELECT ID FROM Document WHERE DeveloperName = : fieldValue';      
         
        String ret = '';
        
           system.debug(ObjectName+'  :soql for:'+fieldValue);
           if(Database.query(soql).size() == 0)
           {
              emailUserAnError('Missing record =>\n'+fieldValue+' in '+ObjectName+' does not exists. Please ensure this exists and retry');
           }    
           else
            ret = Database.query(soql)[0].Id;
        
        return ret;
    }
    
    /*
    *   @method : createObject
    *   Description : To get the id by creating the record Object name and recordtypeid and record name(value for the field named as name) is passed.
    *
    */
    global static Id createObject(String ObjectName,String recType, String RecordName) 
    {
        sObject sObj ;
        Schema.SObjectType targetType = Schema.getGlobalDescribe().get(ObjectName);
        
        if(targetType!=null)
        {
            sObj = targetType.newSObject();  
                
            if(ObjectName != 'Contact')
                sObj.put('name' , RecordName) ;
            else
                sObj.put('LastName' , RecordName) ;
     
            if(recType!=null)
            {
                Id recordId = getObjectId('RecordType', recType);

                sObj.put('RecordTypeId' , recordId);  
            }
    
            try
            {
                insert sObj ;    
            }
            catch(Exception e)
            {
                emailUserAnError(e.getMessage());
            }        
            
            // Instantiate an sObject with the type passed in as an argument
            //  at run time.
            return sObj.Id; 
        }
        else 
           return null;
    }

 global static void emailUserAnError(String ex)
 {
 
     system.debug('Message : '+ex);
/*   Messaging.SingleEmailMessage emailTobeSent = new Messaging.SingleEmailMessage();
            list<String> listEmailMembers = new list<String>();
            listEmailMembers.add(userInfo.getUserEmail());
            emailTobeSent.setToAddresses(listEmailMembers);
            emailTobeSent.setSubject('Post Install Script failed due unavailabilty of the record');
            emailTobeSent.setHtmlBody('Message : '+ex);
            Messaging.SendEmailResult [] r1 = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {emailTobeSent});
    system.debug('Error mailed to '+userInfo.getUserEmail());
*/ }
    
    public static Map<String, String> cronJobMethod()
    {
        Map<String, String> scheduleJobNamesMap = new Map<String, String>();
        for(CronJobDetail scheduleJobNames : [SELECT Id, Name FROM CronJobDetail]){
            scheduleJobNamesMap.put(scheduleJobNames.Name, scheduleJobNames.id);
        }
        return scheduleJobNamesMap;
    }
    
    public static void updateSeachKey(){
        List<causeview__Gift__c> newlist =new List<causeview__Gift__c> ();
        List<causeview__Gift__c>  giftlist=[select id , name,causeview__Constituent_Name__c ,causeview__Gift_Type__c,causeview__Amount__c from causeview__Gift__c where CreatedDate != null];
      
            for(causeview__Gift__c gift:giftlist)
             {
              string ss=gift.causeview__Constituent_Name__c + '-' + gift.causeview__Gift_Type__c + '-' + gift.causeview__Amount__c ;
              gift.causeview__Search_Key__c=ss;
              newlist.add(gift);
             }
          update newlist;
    }
}