Causeview Package Complete/src/objects/BatchSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Causeview batch processing settings.</description>
    <label>Batch Settings</label>
</CustomObject>

Causeview Package Complete/src/objects/Gift__c.object
<CustomObject>
    <description>Causeview - Any financial transactions including: gifts, product purchases, event registrations, membership renewals, etc.</description>
    <fields>
        <fullName>Batch_Status__c</fullName>
        <label>Batch Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Committed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Receipted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GiftBatch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Gift Batch that is related to gift</description>
        <label>Gift Batch</label>
        <referenceTo>Gift_Batch__c</referenceTo>
        <relationshipLabel>Gifts</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Gift_Batch__c.object
<CustomObject>
    <description>Causeview - Offline batch processing of gifts.</description>
    <fields>
        <fullName>Batch_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Batch name.</description>
        <label>Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Gift Batch</label>
    <nameField>
        <displayFormat>GB-{00000}</displayFormat>
        <label>Batch #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gift Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/src/classes/BatchTransactionListController.cls
public with sharing class BatchTransactionListController {
    
    public string batchId {get; set;}
    public string selectedView {get; set; }
    public boolean isBatchOpen {get; set; }
    public boolean hasGifts {
        get {
            return  batchGifts == null || batchGifts.size() == 0 ? false : true;     
        }
    }
    public List<GiftBatchWrapper> giftItems { 
      get; 
      set {
        giftItems = value;
        batchGifts = new List<GiftBatchWrapper>();
        for (GiftBatchWrapper gift : giftItems)
        {
            if (selectedView == 'All')
            {
                batchGifts.add(gift);
            }
            else if (selectedView == 'Pending')
            {
                if (gift.payment.Payment_Type__c == 'Credit Card' &&(gift.gift.Batch_Status__c == 'Pending' || gift.gift.Batch_Status__c == null)) batchGifts.add(gift);
            }
            else if (gift.gift.Batch_Status__c == 'Failed')
            {
                batchGifts.add(gift);
            }
        }//end for
      }
    }
    
    public List<GiftBatchWrapper> batchGifts { get; set; }
    public batchTransactionListController(){
       selectedView = 'All';
    }
    public void refreshGifts () {}
    
    static testMethod void testMe() {
        
        BatchSettings__c bs = GiftBatchWrapper.testCustomSettings();
        RecordType rtypes = [Select Name, Id From RecordType where Name = 'Gift' AND NamespacePrefix = 'causeview' LIMIT 1];
        
        causeview__Batch_Template__c bt123 = new causeview__Batch_Template__c();
        bt123.name = 'abc';
        insert bt123;
        
        Gift_Batch__c gb2 = new Gift_Batch__c();
        gb2.Name__c = 'test980';
        gb2.causeview__Template_Name__c = bt123.id;
        insert gb2;
        
        Account a = new Account(Name = 'ssss');
        insert a;
        
        Gift__c g = new Gift__c();
        g.Organization__c = a.Id;
        g.GiftBatch__c = gb2.Id;
        g.Batch_Status__c = 'Pending';
        g.RecordTypeId = rtypes.id;
        insert g;
        
        GiftBatchWrapper wrapper = GiftBatchWrapper.CreateInstance(g.Id);
        wrapper.payment.Payment_Type__c = 'Credit Card';
        wrapper.payment.Donation__c = g.Id;
        insert wrapper.payment;
        
        wrapper = GiftBatchWrapper.CreateInstance(g.Id);
        List<GiftBatchWrapper> wrappers = new List<GiftBatchWrapper>();
        wrappers.add(wrapper);
        
        BatchTransactionListController cnt = new BatchTransactionListController();
        cnt.batchId  = gb2.Id;
        cnt.selectedView = 'Pending';
        cnt.giftItems = wrappers;
        List<GiftBatchWrapper> wrappers2 = cnt.giftItems;
        
        cnt.selectedView = 'All';
        wrappers2 = cnt.giftItems;
        
        cnt.selectedView = 'Failed';
        wrappers2 = cnt.giftItems;
        
        boolean has = cnt.hasGifts;
        has = cnt.isBatchOpen;
        cnt.refreshGifts();
   
    }
    
}