Causeview Package Complete/src/objects/BatchSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Causeview batch processing settings.</description>
    <label>Batch Settings</label>
</CustomObject>

Causeview Package Complete/src/objects/Gift__c.object
<CustomObject>
    <description>Causeview - Any financial transactions including: gifts, product purchases, event registrations, membership renewals, etc.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Rollup of all payments with Status = Approved, Deposited, Refunded</description>
        <inlineHelpText>Sum of all payments with status (Approved, Deposited, Refunded)</inlineHelpText>
        <label>Approved Amount</label>
        <summarizedField>Payment__c.Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Payment__c.Status__c</field>
            <operation>equals</operation>
            <value>Approved, Deposited, Refunded, Invoiced</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Payment__c.Amount__c</field>
            <operation>notEqual</operation>
            <value>0</value>
        </summaryFilterItems>
        <summaryForeignKey>Payment__c.Donation__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Constituent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Individual</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Constituent)</relationshipLabel>
        <relationshipName>Gifts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gift_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Entered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acknowledged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/givingpowerSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Causeview communication and notification templates.</description>
    <fields>
        <fullName>ConsolidatedReceiptEmailTemplateId__c</fullName>
        <label>Consolidated Receipt Email Template ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consolidated_Duplicate_Receipt_Email_Doc__c</fullName>
        <description>Consolidated Duplicate Receipt Email Doc</description>
        <label>Consolidated Duplicate Receipt Email Doc</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consolidated_Receipt_Email_Document_Id__c</fullName>
        <description>Consolidated Receipt Email Document Id</description>
        <label>Consolidated Receipt Email Document Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DupeConsolidatedReceiptEmailTempId__c</fullName>
        <label>Dupe Consolidated Receipt Email Temp Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DupeDocumentTemplateId__c</fullName>
        <label>Duplicate Receipt Email Document Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dupe_Event_Registration_Email_Doc_ID__c</fullName>
        <description>Duplicate event registration email content document ID (Salesforce ID)</description>
        <inlineHelpText>Duplicate event registration email content document ID (Salesforce ID)</inlineHelpText>
        <label>Dupe Event Registration Email Doc ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dupe_Event_Registration_Template_ID__c</fullName>
        <description>Event registration communication template ID (Salesforce ID) - duplicate/replacement template</description>
        <inlineHelpText>Event registration communication template ID (Salesforce ID) - duplicate/replacement template</inlineHelpText>
        <label>Dupe Event Registration Template ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmailTemplateId__c</fullName>
        <inlineHelpText>The Id of the Visualforce Email Template</inlineHelpText>
        <label>Email Template ID</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Registration_Email_Doc_ID__c</fullName>
        <description>Event registration email content document ID (Salesforce ID)</description>
        <inlineHelpText>Event registration email content document ID (Salesforce ID)</inlineHelpText>
        <label>Event Registration Email Doc ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Registration_Email_Template_ID__c</fullName>
        <description>Event registration communication template ID (Salesforce ID)</description>
        <inlineHelpText>Event registration communication template ID (Salesforce ID)</inlineHelpText>
        <label>Event Registration Email Template ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReceiptEmailDocId__c</fullName>
        <inlineHelpText>The ID of the document (set as public) used for Receipt Email Template</inlineHelpText>
        <label>Receipt Email Document Id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReceiptPDFDocId__c</fullName>
        <inlineHelpText>The ID of the HTML Document used as Receipt&apos;s PDF Template</inlineHelpText>
        <label>Receipt PDF Document Id</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Causeview Receipt Templates</label>
</CustomObject>

Causeview Package Complete/src/objects/Receipt__c.object
<CustomObject>
    <description>Causeview - Tax receipt for transaction records.</description>
    <fields>
        <fullName>Auto_Email_Receipt__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag will auto email a receipt to donor when donation is submitted via DonateNow - from website.</description>
        <label>Auto Email Receipt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Constituent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Captures the constituent ID for email receipting purposes.  Hidden to end users.</description>
        <label>Constituent</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Issued__c</fullName>
        <description>Populated by Conga Merge when receipt is generated.</description>
        <label>Date Issued</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gift__c</fullName>
        <label>Gift</label>
        <referenceTo>Gift__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Receipt_Address__c</fullName>
        <description>Receipt issued to: Address</description>
        <label>Receipt Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Receipt_Amount__c</fullName>
        <description>The amount of donation that is receiptable</description>
        <formula>IF(NOT(ISNULL(Amount_Receipted__c)),  
    Amount_Receipted__c,
    IF(AND(NOT(ISNULL(Gift__r.Sponsorship_Amount__c)), (Gift__r.Sponsorship_Amount__c &gt; 0)) , 
         Gift_Total__c - Amount_Not_Eligible__c,        

           IF(AND(NOT(ISNULL(Percent_Eligible__c)), (Amount_Not_Eligible__c = 0)), 
                 Gift_Total__c * Percent_Eligible__c,
                  Gift_Total__c - Amount_Not_Eligible__c) 
                      ))</formula>
        <label>Receipt Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Issued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To be Issued</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Void</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Receipt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <recordTypes>
        <fullName>Void</fullName>
        <active>true</active>
        <description>Void receipt</description>
        <label>Void</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/classes/DocEmailTemplateController.cls
public with sharing class DocEmailTemplateController {
  
  public String relatedToType { get; set; }
  public String recipientType { get; set; }
  public String isDupe { get; set; }
  public Id relatedToId { get; set; }
  public Id recipientId { get; set; }
  public String emailTemplateType { get; set; }
  
  public string content { 
    get {
      string retVal = '';
      Id docId = null;
      
      // read custom settings
      /*List<givingpowerSettings__c> settingsRecords = [SELECT DupeDocumentTemplateId__c, Event_Registration_Email_Doc_ID__c, Dupe_Event_Registration_Email_Doc_ID__c, Consolidated_Duplicate_Receipt_Email_Doc__c, Consolidated_Receipt_Email_Document_Id__c, ReceiptEmailDocId__c, ConsolidatedReceiptEmailTemplateId__c,
         DupeConsolidatedReceiptEmailTempId__c, Event_Registration_Email_Template_ID__c, Dupe_Event_Registration_Template_ID__c
         FROM givingpowerSettings__c WHERE name = 'settings'];
      */   
         
      givingpowerSettings__c  settings = givingpowerSettings__c.getInstance('Settings');
         
      //if (settingsRecords != null && settingsRecords.size()>0) {
      if(settings != null) {
         //givingpowerSettings__c settings = settingsRecords[0];
         docId = getTemplateId(settings);
      }
       
      // load document
      System.Debug(docId);
      try 
      {
         retVal = DonationUtility.MergeDocument(docId, relatedToType, relatedToId, recipientType, recipientId);
      }
      catch(Exception ex)
      {
         retVal = ex.getMessage() + ' doc id: ' + docId + ' recipientType='+ recipientType + ' recipientId=' + recipientId;
      }
      
      return retVal;
    }
  }
  
  private ID getTemplateId(givingpowerSettings__c settings)
  {
      if (emailTemplateType=='ConsolidatedReceipt')
      {
         return (isDupe == 'True') ? (Id)settings.Consolidated_Duplicate_Receipt_Email_Doc__c:(Id)settings.Consolidated_Receipt_Email_Document_Id__c;
      }
      else if (emailTemplateType=='EventRegistration')
      {
         return (isDupe == 'True') ? (Id)settings.Dupe_Event_Registration_Email_Doc_ID__c:(Id)settings.Event_Registration_Email_Doc_ID__c;
      }
      else
      {
         return (isDupe == 'True') ? (Id)settings.DupeDocumentTemplateId__c:(Id)settings.ReceiptEmailDocId__c;
      }
  }
  
  static testMethod void testMe()
  {
      Profile pr = [select id from profile where name='System Administrator']; 
       User u = new User(alias = 'stadu', email='standard_user@testorg.com', 
            emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
            localesidkey='en_US', profileid = pr.Id, 
            timezonesidkey='America/Los_Angeles', username='standard_user2@testorg.com');


      System.runAs(u) {
        
        BatchSettings__c bs = GiftBatchWrapper.testCustomSettings();
        RecordType rtypes = [Select Name, Id From RecordType where Name = 'Gift' AND NamespacePrefix = 'causeview' LIMIT 1];

      Contact c = new Contact(LastName='test lastname',Email='test@test.com');
      insert c;
      
      Gift__c g = new Gift__c();
      g.Constituent__c = c.Id;
      //g.Amount__c = 80;
      g.Gift_Date__c = Date.today();
      g.Status__c = 'New';
      g.RecordTypeId = rtypes.id;
      insert g;
      
      Receipt__c r = new Receipt__c();
      r.Constituent__c = c.Id;
      r.Auto_Email_Receipt__c = true;
      r.Receipt_Address__c = 'sdajdhasdja dhas dhasjd sahd as';
      r.Date_Issued__c = Date.today();
      r.Gift__c = g.Id;
      insert r;
      
          
      List<givingpowerSettings__c> settingsRecords = [SELECT ReceiptEmailDocId__c, ReceiptPDFDocId__c FROM givingpowerSettings__c WHERE name = 'settings'];
      if (settingsRecords == null || settingsRecords.size()<=0)
      {
          Id folderId = null;
          List<Folder> folders = [SELECT Id FROM Folder WHERE Type = 'Document' limit 5];
          if (folders != null && folders.size()>0)
            folderId = folders[0].Id;
      
          Document doc = new Document();
          doc.Body = Blob.valueOf(' hi {!recipient.Name} <br/> {!relatedTo.Receipt_Amount__c} ');
          doc.Name = 'test document';
          doc.IsPublic = true;
          doc.ContentType = 'text/html';
          doc.FolderId = folderId;
          insert doc;
          
          string EmailTemplateId = 'sdfsdfdsfdsf';
          List<EmailTemplate> templates = [Select TemplateType, Name, Id From EmailTemplate WHERE Name = 'Receipt Template 2' and TemplateType = 'Visualforce'];
          if (templates != null && templates.size()>0)
            EmailTemplateId = templates[0].Id;
          
          givingpowerSettings__c settings = new givingpowerSettings__c();
          settings.ReceiptEmailDocId__c = doc.Id;
          settings.ReceiptPDFDocId__c = doc.Id;
          settings.EmailTemplateId__c = EmailTemplateId;
          settings.Name = 'settings';
          insert settings;
      }
  
      DocEmailTemplateController controller = new DocEmailTemplateController();
      controller.relatedToType = 'Receipt__c';
      controller.recipientType = 'Contact';
      controller.relatedToId = r.Id;
      controller.recipientId = c.Id; 
      
      String result = controller.content;
      
      controller.relatedToType = 'Receipt__c';
      controller.recipientType = 'Contact';
      controller.relatedToId = null;
      controller.recipientId = null;
      
      result = controller.content;
      
      
      DocPDFTemplateController cnt = new DocPDFTemplateController();
      cnt.relatedToType = 'Receipt__c';
      cnt.recipientType = 'Contact';
      cnt.relatedToId = r.Id;
      cnt.recipientId = c.Id; 
      
      result = cnt.content;
      
      cnt.relatedToId = null;
      cnt.recipientId = null;
      
      //result = cnt.content;
      
       
      }
      
  }
  
}