Causeview Package Complete/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>volunteer_Position__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>volunteer Position</label>
        <referenceTo>Volunteer_Role__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Languages__c</fullName>
        <label>Languages</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred_Locales__c</fullName>
        <description>Locations the volunteer prefers to volunteer in.</description>
        <label>Preferred Locale(s)</label>
        <picklist>
            <picklistValues>
                <fullName>To be defined by organization</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Professional_Skills__c</fullName>
        <description>Professional skills the individual has.</description>
        <label>Professional Skills</label>
        <picklist>
            <picklistValues>
                <fullName>Ability to Lift Heavy Objects</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accounting/Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult Educator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advertising/PR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy Skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Art/Graphic Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Career Counselor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communication Skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computer Skill: Data Entry and Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computer Skill: Expert MS Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computer Skill: Intermediate MS Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computer Skill: Social Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Creative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Culinary Arts/Chef</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dependable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Software Skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Detail Oriented</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Early Childhood Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ESL English as Second Language Teacher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Planner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fundraising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospitality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interpersonal Skills</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Sys_No_Availability__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sys No Availability</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Volunteer_Availability__c</fullName>
        <description>Times during the week when the individual is available to volunteer.</description>
        <inlineHelpText>Captures when volunteer is available for service</inlineHelpText>
        <label>Volunteer Availability</label>
        <picklist>
            <picklistValues>
                <fullName>Monday Morning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monday Afternoon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monday Evening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday Morning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday Afternoon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday Evening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday Morning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday Afternoon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday Evening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday Morning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday Afternoon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday Evening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday Morning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday Afternoon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday Evening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday Morning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday Afternoon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday Evening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunday Morning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunday Afternoon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunday Evening</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Volunteer_Opportunity__c.object
<CustomObject>
    <description>Used to track and manage the various Volunteer Opportunities within the Volunteer application.</description>
    <label>Volunteer Opportunity</label>
    <nameField>
        <label>Volunteer Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Volunteer_Role__c.object
<CustomObject>
    <description>Used to track and manage the required Volunteer Roles within the Volunteer Opportunities in the Causeview Volunteers application</description>
    <fields>
        <fullName>Language__c</fullName>
        <description>Required language skills for volunteers filling the role</description>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>Arabic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASL American Sign Language</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burmese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>German</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kurdish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Navajo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nepali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Somali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Swahili</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turkish</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Number_of_Service_Hours_Involved__c</fullName>
        <description>Sum of the duration (hours) for all existing Volunteer Position Shifts for the Volunteer Role.</description>
        <label>Number of Service Hours Involved</label>
        <summarizedField>Volunteer_Shift__c.Duration_Hours__c</summarizedField>
        <summaryForeignKey>Volunteer_Shift__c.Volunteer_Role__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Role_Locale__c</fullName>
        <description>The areas that the role requires the Volunteer to travel to</description>
        <inlineHelpText>The areas that the role requires the Volunteer to travel to</inlineHelpText>
        <label>Role Locale</label>
        <picklist>
            <picklistValues>
                <fullName>To be defined by organization</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Skills_Needed__c</fullName>
        <description>Desired professional skills for volunteers to fill Volunteer Role.</description>
        <label>Skills &amp; Experience</label>
        <picklist>
            <picklistValues>
                <fullName>Ability to Lift Heavy Objects</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accounting/Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult Educator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advertising/PR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advocacy Skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Art/Graphic Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Career Counselor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communication Skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computer Skill: Data Entry + email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computer Skill: Expert MS Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computer Skill: Intermediate MS Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computer Skill: Social Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Creative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Culinary Arts/Chef</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dependable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Software Skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Detail Oriented</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Early Childhood Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ESL English as Second Language Teacher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fundraising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospitality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interpersonal Skills</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Volunteer_Opportunity__c</fullName>
        <inlineHelpText>The Volunteer Opportunity that the role is related to</inlineHelpText>
        <label>Volunteer Opportunity</label>
        <referenceTo>Volunteer_Opportunity__c</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Volunteer_Positions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Volunteer Role</label>
    <nameField>
        <label>Volunteer Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/classes/CSearchPos.cls
public with sharing class CSearchPos {
// Security issue resolve.
    public void back() {
        wizardStep = 1;
    }


    public PageReference addConfirm() {
        try 
        {               
            List<CampaignMember> theMembers = new List<CampaignMember>();
            campaign.Name = thePosition.Name + '--' + DateTime.Now();
            insert campaign;            
            for (Contact c : selectedContacts)
            {
                CampaignMember buff = new CampaignMember(ContactId = c.Id, CampaignId = campaign.Id);
                theMembers.add(buff);
            }
            insert theMembers;
            PageReference pr = new ApexPages.StandardController(campaign).view();
            pr.setRedirect(true);
            return pr;
        }
        catch (Exception ex)
        {
            System.debug(ex.getMessage());
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,String.valueOf(ex.getLineNumber())));
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,ex.getMessage()));                
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,ex.getStackTraceString()));  
            return null;        
        }
        
    }


    public void addToCampaign() {
        wizardStep = 2;
        for (resultWrapper rw : theVolunteers)
        {
            if (rw.isChecked)
            { selectedContacts.add(rw.theVolunteer); }
        }        
    }    


    public CSearchPos() {
        theVolunteers = new List<resultWrapper>();
        thePosition = [SELECT Id, Number_Of_Service_Hours_Involved__c, Role_Locale__c, Language__c, Name, Skills_Needed__c FROM Volunteer_Role__c WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
        theOpp = new Volunteer_Opportunity__c();
        con = new Contact();
        con.Preferred_Locales__c = thePosition.Role_Locale__c;
        campaign = new Campaign(Volunteer_Position__c = thePosition.Id, IsActive = True);
        selectedContacts = new List<Contact>();
        filterOptions = new List<CKvp>();
        filterOptionsLang = new List<CKvp>();        
        wizardStep = 1;
        Set<String> selectedSkills = new Set<String>();
        if (thePosition.Skills_Needed__c != '' && thePosition.Skills_Needed__c != null)
        { selectedSkills.addAll(thePosition.Skills_Needed__c.split(';')); }
        Set<String> selectedLangs = new Set<String>();       
        if (thePosition.Language__c != '' && thePosition.Language__c != null)
        { selectedLangs.addAll(thePosition.Language__c.split(';')); }
        for (Schema.PicklistEntry p : Contact.Professional_Skills__c.getDescribe().getPicklistValues())
        {
            if (selectedSkills.contains(p.getLabel())) { filterOptions.add(new CKvp(p.getLabel(), true)); }            
            else { filterOptions.add(new CKvp(p.getLabel(), false)); }            
        }
        for (Schema.PicklistEntry p : Contact.Languages__c.getDescribe().getPicklistValues())
        {
            if (selectedLangs.contains(p.getLabel())) { filterOptionsLang.add(new CKvp(p.getLabel(), true)); }            
            else { filterOptionsLang.add(new CKvp(p.getLabel(), false)); }           
        }        
        //refreshList();
    }   
        
    public List<resultWrapper> theVolunteers { get; set; }
    public Volunteer_Role__c thePosition { get; set; }
    public Volunteer_Opportunity__c theOpp { get; set; }
    public Contact con { get; set; }    
    public List<CKvp> filterOptions { get; set; }
    public List<CKvp> filterOptionsLang { get; set; }    
    public String posType { get; set; }
    public Integer wizardStep {get;set;}
    public Campaign campaign {get;set;}
    public List<Contact> selectedContacts {get;set;}

    public List<SelectOption> getTypes() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('All', 'All'));                
        options.add(new SelectOption('012d000000047ls', 'Group'));        
        options.add(new SelectOption('012d000000047ln', 'Individual'));                                                                                                                                                                                                                                                                                                
        return options;
    }
    
    public void refreshList() {
        try
        {
            String queryString = 'SELECT FirstName, LastName, Phone, Id, Email, Sys_No_Availability__c FROM Contact';
            List<String> filters = new List<String>();
            String buffFilters = '';
            String finalFilters = '';
            List<Contact> contactResults = new List<Contact>();
            
            if (con.Volunteer_Availability__c != '' && con.Volunteer_Availability__c != null) {
                string filterBuff = '';
                filterBuff += '(Volunteer_Availability__c INCLUDES (';
                if (con.Volunteer_Availability__c.contains(';')) {
                    List<string> values = new List<string>();
                    for (String str : con.Volunteer_Availability__c.split(';')) {
                         values.add('\'' + str + '\'');
                    }
                    filterBuff += string.join(values, ',');
                }
                else {
                    filterBuff += '\'' + con.Volunteer_Availability__c + '\'';
                }
                filterBuff += '))';
                filters.add(filterBuff);                    
            }

            //MY PROFESSIONAL SKILLS
            List<String> selectedSkills = new List<String>();
            Boolean isSkillFiltered = false;
            for (CKvp kvp : filterOptions)
            {
                if(kvp.value)
                {
                    selectedSkills.add(kvp.key);
                    isSkillFiltered = true;
                }
            }            
            if (isSkillFiltered)
            {
                buffFilters = '';
                buffFilters += '(Professional_Skills__c INCLUDES(\'';
                for (String strSkill : selectedSkills)
                {                    
                    buffFilters += (strSkill + ';');
                }
                buffFilters = buffFilters.substring(0, buffFilters.length() - 1);
                buffFilters += '\'))';  
                filters.add(buffFilters);                              
            }
            
            //LOCATION
            if (con.Preferred_Locales__c != '' && con.Preferred_Locales__c != null)
            {
                buffFilters = '';
                buffFilters += '(Preferred_Locales__c INCLUDES(';
                for (String strLoc : con.Preferred_Locales__c.split(';'))
                {                    
                    buffFilters += ('\'' + strLoc + '\', ');
                }
                buffFilters = buffFilters.substring(0, buffFilters.length() - 2);
                buffFilters += '))';
                filters.add(buffFilters);
            }              
            
            //LANGUAGES
            List<String> selectedSkillsLang = new List<String>();
            Boolean isSkillFilteredLang = false;
            for (CKvp kvp : filterOptionsLang)
            {
                if(kvp.value)
                {
                    selectedSkillsLang.add(kvp.key);
                    isSkillFilteredLang = true;
                }
            }            
            if (isSkillFilteredLang)
            {
                buffFilters = '';
                buffFilters += '(Languages__c INCLUDES(\'';
                for (String strSkill : selectedSkillsLang)
                {                    
                    buffFilters += (strSkill + ';');
                }
                buffFilters = buffFilters.substring(0, buffFilters.length() - 1);
                buffFilters += '\'))';                
                filters.add(buffFilters);
            }            
            
            if (filters.size() > 0) 
            {             
                finalFilters += ' WHERE '; 
                for (String f : filters)
                {
                    finalFilters += (f + ' AND ');
                }
                finalFilters = finalFilters.substring(0, finalFilters.length() - 5);
            }

            system.debug(queryString + finalFilters + ' ORDER BY LastName');
            contactResults = Database.query(queryString + finalFilters + ' ORDER BY LastName');          
            theVolunteers = new List<resultWrapper>();  
            for (Contact c : contactResults)
            {
                theVolunteers.add(new resultWrapper(c));
            }
        }
        catch (Exception ex)
        {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,String.valueOf(ex.getLineNumber())));
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,ex.getMessage()));                
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,ex.getStackTraceString()));       
        }
    }

    public class resultWrapper {
        public resultWrapper(Contact c) {
            theVolunteer = c;
            isChecked = false;
        }
        public boolean isChecked {get;set;}
        public Contact theVolunteer {get;set;}        
    }

    public class CKvp
    {
        public CKvp(string sKey, boolean bValue)
        {
            key = sKey;
            value = bValue;
        }
        public string key { get; set; }
        public boolean value { get; set; }
    }
}