Causeview Package Complete/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Fund__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The designated Fund the Appeal is prompting for</description>
        <inlineHelpText>The designated Fund the Appeal is prompting for</inlineHelpText>
        <label>Fund</label>
        <referenceTo>Fund__c</referenceTo>
        <relationshipLabel>Campaigns/Appeals</relationshipLabel>
        <relationshipName>CampaignsAppeals</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Appeal</fullName>
        <active>true</active>
        <description>A request for funds</description>
        <label>Appeal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>A gathering of constituents for the purpose of fundraising or support</description>
        <label>Event</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Event__c.object
<CustomObject>
    <description>Causeview - No longer required.</description>
    <fields>
        <fullName>Fund__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fund</label>
        <referenceTo>Fund__c</referenceTo>
        <relationshipName>Special_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>(DEPRECATED)</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Event No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(DEPRECATED)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Event_Level__c.object
<CustomObject>
    <description>Causeview - event ticket and sponsorship levels</description>
    <fields>
        <fullName>Event__c</fullName>
        <description>Event the ticket type is belongs to</description>
        <label>Event</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Event Level</label>
    <nameField>
        <label>Event Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Fund__c.object
<CustomObject>
    <description>Causeview - Captures your organization&apos;s funds.</description>
    <label>Fund</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Fund ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Gift__c.object
<CustomObject>
    <description>Causeview - Any financial transactions including: gifts, product purchases, event registrations, membership renewals, etc.</description>
    <fields>
        <fullName>Constituent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Individual</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Constituent)</relationshipLabel>
        <relationshipName>Gifts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event (dep)</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/src/classes/TestCauseViewCustomSetting.cls
@IsTest
public class TestCauseViewCustomSetting
{


 static testMethod  void testANumSettings()
 {
     CauseViewCustomSetting.defaultANumSettings();   
 }
 
 
 
  static testMethod  void testBatchSettings()
 {
     CauseViewCustomSetting.defaultBatchSettings();
 }
 
 
 
 static testMethod  void testAppSettings()
 {
     CauseViewCustomSetting.defaultAppSettings();
 }
 
 
 static testMethod  void testAppTemplateSettings()
 {
   CauseViewCustomSetting.defaultAppTemplateSettings();
 }
 
 static testMethod void testSearchKey(){
      Map<String, String> rtype_Map = new Map<String, String>();
        rtype_Map = GLAllocationfieldUpdateTriggerTest.getrecordTypes();
        causeview__aNums__c cs1 = GLAllocationfieldUpdateTriggerTest.anumsSettings();

        causeview__FormSettings__c fs1 = GLAllocationfieldUpdateTriggerTest.formSettings();    
        
        causeview__App_Settings__c appSetting = GLAllocationfieldUpdateTriggerTest.appSettings();
        
        Account a = GLAllocationfieldUpdateTriggerTest.acc();

        causeview__BatchSettings__c cs2 = GLAllocationfieldUpdateTriggerTest.batchSettings();        

        Contact c = GLAllocationfieldUpdateTriggerTest.con();
        Fund__c f = GLAllocationfieldUpdateTriggerTest.fundRecord();
        //Campaign cam = GLAllocationfieldUpdateTriggerTest.campaignRecord();
        //insert cam;
         Campaign camp = new Campaign(Name = 'Campaign', RecordTypeId = rtype_Map.get('Campaign'));
        insert camp;
        Campaign pAppeal = new Campaign(Name = 'Appeal', RecordTypeId = rtype_Map.get('Appeal'), ParentId = camp.Id);
        insert pAppeal;
        Campaign event = new Campaign(Name = 'Event', RecordTypeId = rtype_Map.get('Event'), ParentId = pAppeal.Id);
        insert event;
        Event_Level__c e = GLAllocationfieldUpdateTriggerTest.eventLevelRecord();
        e.Event__c = event.Id;
        insert e;
        
        Gift__c g= GLAllocationfieldUpdateTriggerTest.giftRecord();
        g.Constituent__c = c.Id;
        g.RecordTypeId = rtype_Map.get('Gift');
        insert g;
        
        CauseViewCustomSetting.updateSeachKey();
  }



}