Causeview Package Complete/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Gift_Amount__c</fullName>
        <description>Total number of Gifts received NOT including child records</description>
        <inlineHelpText>Total number of Gifts received NOT including child records</inlineHelpText>
        <label>Gift Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gift_Count__c</fullName>
        <description>Total number of Gifts received NOT including child records</description>
        <formula>One_Time_Gift_Count__c  +  Recurring_Gift_Count__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total number of Gifts received NOT including child records</inlineHelpText>
        <label>Gift Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Gifts_for_Current_Fiscal__c</fullName>
        <description>Total amount of Gifts received during current fiscal NOT including child records</description>
        <inlineHelpText>Total amount of Gifts received during current fiscal NOT including child records</inlineHelpText>
        <label>Gifts for Current Fiscal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gifts_for_Current_Quarter__c</fullName>
        <description>Total amount of Gifts received during current quarter NOT including child records</description>
        <inlineHelpText>Total amount of Gifts received during current quarter NOT including child records</inlineHelpText>
        <label>Gifts for Current Quarter</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>One_Time_Gift_Count__c</fullName>
        <description>Total number of One-Time Gifts received NOT including child records</description>
        <inlineHelpText>Total number of One-Time Gifts received NOT including child records</inlineHelpText>
        <label>One-Time Gift Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Overall_Gift_Amount__c</fullName>
        <description>Total amount of Gifts received including all child records</description>
        <inlineHelpText>Total amount of Gifts received including all child records</inlineHelpText>
        <label>Overall Lifetime Gift Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Overall_Gift_Count__c</fullName>
        <description>Total number of Gifts received including all child records</description>
        <formula>Overall_One_Time_Gift_Count__c  +  Overall_Recurring_Gift_Count__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total number of Gifts received including all child records</inlineHelpText>
        <label>Overall Lifetime Gift Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Overall_Gifts_for_Current_Fiscal__c</fullName>
        <description>Total amount of Gifts received during current fiscal including all child records</description>
        <inlineHelpText>Total amount of Gifts received during current fiscal including all child records</inlineHelpText>
        <label>Overall Gifts for Current Fiscal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Overall_Gifts_for_Current_Quarter__c</fullName>
        <description>Total amount of Gifts received during current quarter including all child records</description>
        <inlineHelpText>Total amount of Gifts received during current quarter including all child records</inlineHelpText>
        <label>Overall Gifts for Current Quarter</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Overall_One_Time_Gift_Count__c</fullName>
        <description>Total number of One-Time Gifts received including all child records</description>
        <inlineHelpText>Total number of One-Time Gifts received including all child records</inlineHelpText>
        <label>Overall One-Time Gift Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Overall_Recurring_Gift_Count__c</fullName>
        <description>Total number of Recurring Gifts received including all child records</description>
        <inlineHelpText>Total number of Recurring Gifts received including all child records</inlineHelpText>
        <label>Overall Recurring Gift Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recurring_Gift_Count__c</fullName>
        <description>Total number of Recurring Gifts received NOT including child records</description>
        <inlineHelpText>Total number of Recurring Gifts received NOT including child records</inlineHelpText>
        <label>Recurring Gift Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Appeal</fullName>
        <active>true</active>
        <description>A request for funds</description>
        <label>Appeal</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Expense__c.object
<CustomObject>
    <description>Causeview - Expenses relating to Gifts, Appeals or Events.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gift__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gift</label>
        <referenceTo>Gift__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign/Appeal</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Gift__c.object
<CustomObject>
    <description>Causeview - Any financial transactions including: gifts, product purchases, event registrations, membership renewals, etc.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Rollup of all payments with Status = Approved, Deposited, Refunded</description>
        <inlineHelpText>Sum of all payments with status (Approved, Deposited, Refunded)</inlineHelpText>
        <label>Approved Amount</label>
        <summarizedField>Payment__c.Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Payment__c.Status__c</field>
            <operation>equals</operation>
            <value>Approved, Deposited, Refunded, Invoiced</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Payment__c.Amount__c</field>
            <operation>notEqual</operation>
            <value>0</value>
        </summaryFilterItems>
        <summaryForeignKey>Payment__c.Donation__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Gift_Count__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gift Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Gift_Type__c</fullName>
        <label>Gift Type</label>
        <picklist>
            <picklistValues>
                <fullName>One Time Gift</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Recurring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pledge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gift-in-Kind</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Sponsorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grant</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Recurring_Donation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recurring Gift</label>
        <referenceTo>Recurring_Donation__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Gift_Detail__c.object
<CustomObject>
    <description>Causeview - Manages the allocation of your gifts across Funds, Appeals, Tributes, Products and Campaigns.</description>
    <fields>
        <fullName>Allocation_Date__c</fullName>
        <description>Date of allocation - referenced from Gift Payment</description>
        <inlineHelpText>Date of allocation - referenced from Gift Payment</inlineHelpText>
        <label>Allocation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Allocated Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Approved_Amount__c</fullName>
        <formula>IF( $Setup.App_Settings__c.Enable_Pledge_Accrual_Accounting__c &amp;&amp; ISPICKVAL(Gift__r.Gift_Type__c, &quot;Pledge&quot;),
Amount__c,
IF(ISBLANK(Payment__c), 
0, 
IF(OR(
ISPICKVAL(Payment__r.Status__c, &quot;Declined&quot;), 
ISPICKVAL(Payment__r.Status__c, &quot;Pending&quot;), 
ISPICKVAL(Payment__r.Status__c, &quot;Written Off&quot;), 
ISPICKVAL(Payment__r.Status__c, &quot;ACH Return&quot;)), 
0,
IF(Payment__r.Amount__c = 0, 
0, 
Amount__c)
)
)
)</formula>
        <label>Approved Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gift_Type__c</fullName>
        <formula>TEXT( Gift__r.Gift_Type__c )</formula>
        <label>Gift Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gift__c</fullName>
        <label>Transaction</label>
        <referenceTo>Gift__c</referenceTo>
        <relationshipLabel>Allocations</relationshipLabel>
        <relationshipName>Gift_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>New_Campaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Links transactions to Campaign/Appeals.</description>
        <label>Appeal</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Campaign.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Campaign</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Transaction Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Allocation</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Allocation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Recurring_Donation__c.object
<CustomObject>
    <description>Causeview - Captures recurring gifts</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount per payment</description>
        <label>Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Recurring Gift</label>
    <nameField>
        <displayFormat>RD-{00000}</displayFormat>
        <label>Recurring Gift No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Gifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/classes/AppealUtil.cls
public without sharing class AppealUtil {
     
      public static void RollupCampaigns(Set<Id> AppealIDs)
    {
        Set<String> AppealIDsH = new Set<String>();
        Map<String, List<Campaign>> Appeals_to_Children = new Map<String, List<Campaign>>();        
        Integer fysm = [Select o.FiscalYearStartMonth from Organization o where o.id=:Userinfo.getOrganizationId() LIMIT 1].FiscalYearStartMonth;
        List<Date> FiscalQuarterArray = getFQArray(fysm);
        Date FiscalYearStartDate = Date.Today();
       
         //Set<Id> parentappeal=new Set<Id>();

        if (Date.Today().Month() >= fysm)
        { FiscalYearStartDate = Date.newInstance(Date.Today().Year(), fysm, 1); }
        if (Date.Today().Month() < fysm)
        { FiscalYearStartDate = Date.newInstance(Date.Today().Year() - 1, fysm, 1); }

        if (AppealIDs == null || AppealIDs.size()<=0)
        return;

        /*List<Campaign> Appeals = [SELECT c.Name, c.ParentId, c.ActualCost, c.Gift_Amount__c, c.Gift_Count__c, c.Gifts_for_Current_Fiscal__c, c.Gifts_for_Current_Quarter__c, 
                                  c.One_Time_Gift_Count__c, c.Overall_Gift_Amount__c, c.Overall_Gift_Count__c, c.Overall_Gifts_for_Current_Fiscal__c, 
                                  c.Overall_Gifts_for_Current_Quarter__c, c.Overall_One_Time_Gift_Count__c, c.Overall_Recurring_Gift_Count__c, c.Recurring_Gift_Count__c , 
                                  (SELECT Gift__r.Recurring_Donation__c, Gift__r.Gift_Type__c, Gift__c, Allocation_Date__c, Approved_Amount__c FROM Allocations__r 
                                  ) FROM Campaign c WHERE  Id IN :AppealIDs  FOR UPDATE ];*/
                                  
      	List<Campaign> Appeals = new List<Campaign>();
        for(Campaign appeal : [SELECT c.Name, c.ParentId, c.ActualCost, c.Gift_Amount__c, c.Gift_Count__c, c.Gifts_for_Current_Fiscal__c, c.Gifts_for_Current_Quarter__c, 
                                  c.One_Time_Gift_Count__c, c.Overall_Gift_Amount__c, c.Overall_Gift_Count__c, c.Overall_Gifts_for_Current_Fiscal__c, 
                                  c.Overall_Gifts_for_Current_Quarter__c, c.Overall_One_Time_Gift_Count__c, c.Overall_Recurring_Gift_Count__c, c.Recurring_Gift_Count__c 
                                  FROM Campaign c WHERE  Id IN :AppealIDs  FOR UPDATE ]) {
            Appeals.add(appeal);
        }
        
        List<Gift_Detail__c> Allocations = new List<Gift_Detail__c>();
        for(Gift_Detail__c allocation : [SELECT Gift__r.Recurring_Donation__c, Gift__r.Gift_Type__c, Gift__c, Allocation_Date__c, Approved_Amount__c, New_Campaign__c FROM Gift_Detail__c WHERE New_Campaign__c  IN :AppealIDs FOR UPDATE])
        {
            Allocations.add(allocation);
        }
        
        system.debug('am here ' + Appeals);
        for(Campaign c : Appeals)
        {
            AppealIDsH.add(c.Id);
        }
        
        List<Campaign> AppealsH = [SELECT  c.Parent.ParentId,c.ParentId, c.ActualCost, c.Gift_Amount__c, c.Gift_Count__c, c.Gifts_for_Current_Fiscal__c, c.Gifts_for_Current_Quarter__c, c.One_Time_Gift_Count__c, c.Overall_Gift_Amount__c, c.Overall_Gift_Count__c, c.Overall_Gifts_for_Current_Fiscal__c, c.Overall_Gifts_for_Current_Quarter__c, c.Overall_One_Time_Gift_Count__c, c.Overall_Recurring_Gift_Count__c, c.Recurring_Gift_Count__c FROM Campaign c WHERE c.ParentId IN :AppealIDsH OR c.Parent.ParentId IN :AppealIDsH ]; 
        system.debug('am here ' + AppealsH);
        for(Campaign c : Appeals)
        {
            List<Campaign> cs = new List<Campaign>();
            for(Campaign cH : AppealsH)
            {
                if(c.Id == cH.ParentId )// || c.Id == cH.Parent.ParentId)
                { cs.add(cH); }
            }
            Appeals_to_Children.put(c.Id, cs);
        }       
        
  
        
        for(Campaign c : Appeals)
        {
            transient Integer countGiftsFY = 0;
            transient Integer countGiftsFQ = 0;            
            transient Decimal Amount = 0;
            transient Decimal AmountRD = 0;            
            transient Decimal AmountH = 0;
            transient Decimal AmountRDH = 0;            
            transient Decimal AmountFY = 0;
            transient Decimal AmountFQ = 0;
            transient Decimal AmountFYH = 0;
            transient Decimal AmountFQH = 0;    
            transient Decimal AmountRDFY = 0;
            transient Decimal AmountRDFQ = 0;
            transient Decimal AmountRDFYH = 0;
            transient Decimal AmountRDFQH = 0;   
            c.Gift_Amount__c = 0; 
            c.Overall_Gift_Amount__c = 0;
            c.One_Time_Gift_Count__c = 0;           
            c.Overall_One_Time_Gift_Count__c = 0;
            c.Overall_Recurring_Gift_Count__c = 0;
            c.Recurring_Gift_Count__c = 0;
            c.Gifts_for_Current_Fiscal__c = 0;
            c.Overall_Gifts_for_Current_Fiscal__c = 0;
            c.Overall_Gifts_for_Current_Quarter__c = 0; 
            c.Gifts_for_Current_Quarter__c = 0;                              
            Set<String> Count = new Set<String>();
            Set<String> CountRD = new Set<String>();            
            Set<String> CountH = new Set<String>();
            Set<String> CountRDH = new Set<String>();            
            Campaign ParentRec =new Campaign();
            //system.debug('DETAILSARE' + c.Name + c.Gift_Details__r.size());
            
            if (Allocations != null)           
            {
                for(Gift_Detail__c gd : Allocations)
                {
                	if(c.Id == gd.New_Campaign__c){                   
	                    if (gd.Gift__r.Gift_Type__c == 'Recurring')
	                    { 
	                        AmountRD += (gd.Approved_Amount__c != null) ? gd.Approved_Amount__c : 0; 
	                        if (isCurrentFiscal(gd.Allocation_Date__c, fysm))
	                        { AmountRDFY += (gd.Approved_Amount__c != null) ? gd.Approved_Amount__c : 0; }
	                        if (isCurrentFiscalQuarter(gd.Allocation_Date__c, FiscalQuarterArray))
	                        { AmountRDFQ += (gd.Approved_Amount__c != null) ? gd.Approved_Amount__c : 0; }
	                        CountRD.add(gd.Gift__r.Recurring_Donation__c);
	                    }
	                    else
	                    {
	                        Amount += (gd.Approved_Amount__c != null) ? gd.Approved_Amount__c : 0; 
	                        if (isCurrentFiscal(gd.Allocation_Date__c, fysm))
	                        { AmountFY += (gd.Approved_Amount__c != null) ? gd.Approved_Amount__c : 0; }
	                        if (isCurrentFiscalQuarter(gd.Allocation_Date__c, FiscalQuarterArray))
	                        { AmountFQ += (gd.Approved_Amount__c != null) ? gd.Approved_Amount__c : 0; }
	                        Count.add(gd.Gift__c);                    
	                    }
                	}
                }
            }                                          
            
            if (Appeals_to_Children.containsKey(c.Id))
            {
                for (Campaign cH : Appeals_to_Children.get(c.Id))
                {  
                    if (cH!=null){   
                    //system.debug('am inside null');
                    
                    cH.Overall_Gift_Amount__c = cH.Overall_Gift_Amount__c == null? 0.00 : cH.Overall_Gift_Amount__c;           
                    c.Overall_Gift_Amount__c += cH.Overall_Gift_Amount__c;                   
                                 
                    cH.Overall_One_Time_Gift_Count__c = cH.Overall_One_Time_Gift_Count__c == null? 0 : cH.Overall_One_Time_Gift_Count__c;
                    c.Overall_One_Time_Gift_Count__c += cH.Overall_One_Time_Gift_Count__c;
                    
                     
                    cH.Overall_Recurring_Gift_Count__c = cH.Overall_Recurring_Gift_Count__c == null? 0 : cH.Overall_Recurring_Gift_Count__c;                                     
                    c.Overall_Recurring_Gift_Count__c += cH.Overall_Recurring_Gift_Count__c; 
                    
                    cH.Overall_Gifts_for_Current_Fiscal__c = cH.Overall_Gifts_for_Current_Fiscal__c == null? 0.00 : cH.Overall_Gifts_for_Current_Fiscal__c;
                    c.Overall_Gifts_for_Current_Fiscal__c += cH.Overall_Gifts_for_Current_Fiscal__c;
                     
                    cH.Overall_Gifts_for_Current_Quarter__c = cH.Overall_Gifts_for_Current_Quarter__c == null? 0.00 : cH.Overall_Gifts_for_Current_Quarter__c;
                    c.Overall_Gifts_for_Current_Quarter__c += cH.Overall_Gifts_for_Current_Quarter__c; 
                    
                    cH.Gifts_for_Current_Quarter__c = cH.Gifts_for_Current_Quarter__c == null? 0.00 : cH.Gifts_for_Current_Quarter__c; 
                    c.Gifts_for_Current_Quarter__c += cH.Gifts_for_Current_Quarter__c;
                    }
                    
                   }
 
                
            }            
                
            c.Overall_Gift_Amount__c += Amount + AmountH + AmountRD + AmountRDH;
            c.Gifts_for_Current_Quarter__c += AmountFQ + AmountRDFQ;
            c.Overall_Gifts_for_Current_Quarter__c += AmountFQ + AmountFQH + AmountRDFQ + AmountRDFQH;
            c.Overall_Gifts_for_Current_Fiscal__c += AmountFY + AmountFYH + AmountRDFY + AmountRDFYH;
            c.Gifts_for_Current_Fiscal__c += AmountFY + AmountRDFY;
            c.Recurring_Gift_Count__c += CountRD.size();
            c.Overall_One_Time_Gift_Count__c += (Count.size() + CountH.size());
            c.Overall_Recurring_Gift_Count__c += (CountRD.size() + CountRDH.size());
            c.Gift_Amount__c += Amount + AmountRD;
            c.One_Time_Gift_Count__c += Count.size();   
                        
            }
            
            update Appeals;

        }
    
    
    public static void RollupPackages(Set<Id> AppealIDs)
    {     
        Integer fysm = [Select o.FiscalYearStartMonth from Organization o where o.id=:Userinfo.getOrganizationId() LIMIT 1].FiscalYearStartMonth;
        List<Date> FiscalQuarterArray = getFQArray(fysm);
        Date FiscalYearStartDate = Date.Today();

        if (Date.Today().Month() >= fysm)
        { FiscalYearStartDate = Date.newInstance(Date.Today().Year(), fysm, 1); }
        if (Date.Today().Month() < fysm)
        { FiscalYearStartDate = Date.newInstance(Date.Today().Year() - 1, fysm, 1); }

        if (AppealIDs == null || AppealIDs.size()<=0)
        return;

        /*List<Campaign> Appeals = [SELECT c.ParentId, c.Gift_Amount__c, c.Gift_Count__c, c.Gifts_for_Current_Fiscal__c, c.Gifts_for_Current_Quarter__c, 
                                  c.One_Time_Gift_Count__c, c.Overall_Gift_Amount__c, c.Overall_Gift_Count__c, c.Overall_Gifts_for_Current_Fiscal__c, 
                                  c.Overall_Gifts_for_Current_Quarter__c, c.Overall_One_Time_Gift_Count__c, c.Overall_Recurring_Gift_Count__c, c.Recurring_Gift_Count__c , 
                                  (SELECT Gift__r.Recurring_Donation__c, Gift__c, Allocation_Date__c, Approved_Amount__c FROM Allocations__r) FROM Campaign c WHERE Id IN :AppealIDs  FOR UPDATE];*/
      	
      	List<Campaign> Appeals = new List<Campaign>();
        for(Campaign appeal : [SELECT c.ParentId, c.Gift_Amount__c, c.Gift_Count__c, c.Gifts_for_Current_Fiscal__c, c.Gifts_for_Current_Quarter__c, 
                                  c.One_Time_Gift_Count__c, c.Overall_Gift_Amount__c, c.Overall_Gift_Count__c, c.Overall_Gifts_for_Current_Fiscal__c, 
                                  c.Overall_Gifts_for_Current_Quarter__c, c.Overall_One_Time_Gift_Count__c, c.Overall_Recurring_Gift_Count__c, c.Recurring_Gift_Count__c  
                                  FROM Campaign c WHERE Id IN :AppealIDs  FOR UPDATE]) {
            Appeals.add(appeal);
        }
        
        List<Gift_Detail__c> Allocations = new List<Gift_Detail__c>();
        for(Gift_Detail__c allocation : [SELECT Gift__r.Recurring_Donation__c, Gift__c, Allocation_Date__c, Approved_Amount__c, New_Campaign__c FROM Gift_Detail__c WHERE New_Campaign__c  IN :AppealIDs FOR UPDATE])
        {
            Allocations.add(allocation);
        }
                                          
        for(Campaign c : Appeals)
        {
            Integer countGiftsFY = 0;
            Integer countGiftsFQ = 0;            
            Decimal Amount = 0;
            Decimal AmountRD = 0;            
            Decimal AmountH = 0;
            Decimal AmountRDH = 0;            
            Decimal AmountFY = 0;
            Decimal AmountFQ = 0;
            Decimal AmountFYH = 0;
            Decimal AmountFQH = 0;    
            Decimal AmountRDFY = 0;
            Decimal AmountRDFQ = 0;
            Decimal AmountRDFYH = 0;
            Decimal AmountRDFQH = 0;                     
            Set<String> Count = new Set<String>();
            Set<String> CountRD = new Set<String>();            
            Set<String> CountH = new Set<String>();
            Set<String> CountRDH = new Set<String>();            
            
            //system.debug(c.Gift_Details__r.size());
            
            if (Allocations != null)           
            {
                for(Gift_Detail__c gd : Allocations)
                {
                	if(c.Id == gd.New_Campaign__c){ 
                		if (gd.Gift__r.Recurring_Donation__c != null)
	                    { 
	                        AmountRD += (gd.Approved_Amount__c != null) ? gd.Approved_Amount__c : 0; 
	                        if (isCurrentFiscal(gd.Allocation_Date__c, fysm))
	                        { AmountRDFY += (gd.Approved_Amount__c != null) ? gd.Approved_Amount__c : 0; }
	                        if (isCurrentFiscalQuarter(gd.Allocation_Date__c, FiscalQuarterArray))
	                        { AmountRDFQ += (gd.Approved_Amount__c != null) ? gd.Approved_Amount__c : 0; }
	                        CountRD.add(gd.Gift__r.Recurring_Donation__c);
	                    }
	                    else
	                    {
	                        Amount += (gd.Approved_Amount__c != null) ? gd.Approved_Amount__c : 0; 
	                        if (isCurrentFiscal(gd.Allocation_Date__c, fysm))
	                        { AmountFY += (gd.Approved_Amount__c != null) ? gd.Approved_Amount__c : 0; }
	                        if (isCurrentFiscalQuarter(gd.Allocation_Date__c, FiscalQuarterArray))
	                        { AmountFQ += (gd.Approved_Amount__c != null) ? gd.Approved_Amount__c : 0; }
	                        Count.add(gd.Gift__c);                    
	                    }
                	}                   
                }
            }                                          
                      
            c.Gift_Amount__c = Amount + AmountRD; 
            c.Overall_Gift_Amount__c = Amount + AmountH + AmountRD + AmountRDH;
            c.One_Time_Gift_Count__c = Count.size();           
            c.Overall_One_Time_Gift_Count__c = (Count.size() + CountH.size());
            c.Overall_Recurring_Gift_Count__c = (CountRD.size() + CountRDH.size());
            c.Recurring_Gift_Count__c = CountRD.size();
            c.Gifts_for_Current_Fiscal__c = AmountFY + AmountRDFY;
            c.Overall_Gifts_for_Current_Fiscal__c = AmountFY + AmountFYH + AmountRDFY + AmountRDFYH;
            c.Overall_Gifts_for_Current_Quarter__c = AmountFQ + AmountFQH + AmountRDFQ + AmountRDFQH; 
            c.Gifts_for_Current_Quarter__c = AmountFQ + AmountRDFQ;
        }         
        update Appeals;
    }
    
    public static void RollupAppeals(Set<Id> AppealIDs)
    {
        Set<String> AppealIDsH = new Set<String>();
        Map<String, List<Campaign>> Appeals_to_Children = new Map<String, List<Campaign>>();        
        Integer fysm = [Select o.FiscalYearStartMonth from Organization o where o.id=:Userinfo.getOrganizationId() LIMIT 1].FiscalYearStartMonth;
        List<Date> FiscalQuarterArray = getFQArray(fysm);
        Date FiscalYearStartDate = Date.Today();

        if (Date.Today().Month() >= fysm)
        { FiscalYearStartDate = Date.newInstance(Date.Today().Year(), fysm, 1); }
        if (Date.Today().Month() < fysm)
        { FiscalYearStartDate = Date.newInstance(Date.Today().Year() - 1, fysm, 1); }

        if (AppealIDs == null || AppealIDs.size()<=0)
        return;

        /*List<Campaign> Appeals = [SELECT c.ParentId, c.ActualCost, c.Gift_Amount__c, c.Gift_Count__c, c.Gifts_for_Current_Fiscal__c, c.Gifts_for_Current_Quarter__c, 
                                  c.One_Time_Gift_Count__c, c.Overall_Gift_Amount__c, c.Overall_Gift_Count__c, c.Overall_Gifts_for_Current_Fiscal__c, 
                                  c.Overall_Gifts_for_Current_Quarter__c, c.Overall_One_Time_Gift_Count__c, c.Overall_Recurring_Gift_Count__c, c.Recurring_Gift_Count__c , 
                                  (SELECT Gift__r.Recurring_Donation__c, Gift__r.Gift_Type__c, Gift__c, Allocation_Date__c, Approved_Amount__c FROM Allocations__r 
                                  ) FROM Campaign c WHERE Id IN :AppealIDs   FOR UPDATE ];*/
                                  
        List<Campaign> Appeals = new List<Campaign>();
        for(Campaign appeal : [SELECT c.ParentId, c.ActualCost, c.Gift_Amount__c, c.Gift_Count__c, c.Gifts_for_Current_Fiscal__c, c.Gifts_for_Current_Quarter__c, 
                                  c.One_Time_Gift_Count__c, c.Overall_Gift_Amount__c, c.Overall_Gift_Count__c, c.Overall_Gifts_for_Current_Fiscal__c, 
                                  c.Overall_Gifts_for_Current_Quarter__c, c.Overall_One_Time_Gift_Count__c, c.Overall_Recurring_Gift_Count__c, c.Recurring_Gift_Count__c 
                                  FROM Campaign c WHERE Id IN :AppealIDs   FOR UPDATE ]) {
            Appeals.add(appeal);
        }
        
        List<Gift_Detail__c> Allocations = new List<Gift_Detail__c>();
        for(Gift_Detail__c allocation : [SELECT Gift__r.Recurring_Donation__c, Gift__r.Gift_Type__c, Gift__c, Allocation_Date__c, Approved_Amount__c, New_Campaign__c FROM Gift_Detail__c WHERE New_Campaign__c  IN :AppealIDs FOR UPDATE])
        {
            Allocations.add(allocation);
        }
        
        
        for(Campaign c : Appeals)
        {
            AppealIDsH.add(c.Id);
        }
        system.debug('Appeals==>'+Appeals.size());
        List<Campaign> AppealsH = [SELECT c.Parent.ParentId, c.ParentId, c.ActualCost, c.Gift_Amount__c, c.Gift_Count__c, c.Gifts_for_Current_Fiscal__c, c.Gifts_for_Current_Quarter__c, c.One_Time_Gift_Count__c, c.Overall_Gift_Amount__c, c.Overall_Gift_Count__c, c.Overall_Gifts_for_Current_Fiscal__c, c.Overall_Gifts_for_Current_Quarter__c, c.Overall_One_Time_Gift_Count__c, c.Overall_Recurring_Gift_Count__c, c.Recurring_Gift_Count__c FROM Campaign c WHERE c.ParentId IN :AppealIDsH];
        for(Campaign c : Appeals)
        {
            List<Campaign> cs = new List<Campaign>();
            for(Campaign cH : AppealsH)
            {
                if(c.Id == cH.ParentId)
                { cs.add(cH); }
            }
            Appeals_to_Children.put(c.Id, cs);
        }       
        
        for(Campaign c : Appeals)
        {
            transient Integer countGiftsFY = 0;
            transient Integer countGiftsFQ = 0;            
            transient Decimal Amount = 0;
            transient Decimal AmountRD = 0;            
            transient Decimal AmountH = 0;
            transient Decimal AmountRDH = 0;            
            transient Decimal AmountFY = 0;
            transient Decimal AmountFQ = 0;
            transient Decimal AmountFYH = 0;
            transient Decimal AmountFQH = 0;    
            transient Decimal AmountRDFY = 0;
            transient Decimal AmountRDFQ = 0;
            transient Decimal AmountRDFYH = 0;
            transient Decimal AmountRDFQH = 0;                     
            c.Gift_Amount__c = 0; 
            c.Overall_Gift_Amount__c = 0;
            c.One_Time_Gift_Count__c = 0;           
            c.Overall_One_Time_Gift_Count__c = 0;
            c.Overall_Recurring_Gift_Count__c = 0;
            c.Recurring_Gift_Count__c = 0;
            c.Gifts_for_Current_Fiscal__c = 0;
            c.Overall_Gifts_for_Current_Fiscal__c = 0;
            c.Overall_Gifts_for_Current_Quarter__c = 0; 
            c.Gifts_for_Current_Quarter__c = 0;
            Set<String> Count = new Set<String>();
            Set<String> CountRD = new Set<String>();            
            Set<String> CountH = new Set<String>();
            Set<String> CountRDH = new Set<String>();            
            
            //system.debug(c.Gift_Details__r.size());
            
            if (Allocations != null)           
            {
                for(Gift_Detail__c gd : Allocations)
                {
                	if(c.Id == gd.New_Campaign__c){                   
	                    if (gd.Gift__r.Gift_Type__c == 'Recurring')
	                    { 
	                        AmountRD += (gd.Approved_Amount__c != null) ? gd.Approved_Amount__c : 0; 
	                        if (isCurrentFiscal(gd.Allocation_Date__c, fysm))
	                        { AmountRDFY += (gd.Approved_Amount__c != null) ? gd.Approved_Amount__c : 0; }
	                        if (isCurrentFiscalQuarter(gd.Allocation_Date__c, FiscalQuarterArray))
	                        { AmountRDFQ += (gd.Approved_Amount__c != null) ? gd.Approved_Amount__c : 0; }
	                        CountRD.add(gd.Gift__r.Recurring_Donation__c);
	                    }
	                    else
	                    {
	                        Amount += (gd.Approved_Amount__c != null) ? gd.Approved_Amount__c : 0; 
	                        if (isCurrentFiscal(gd.Allocation_Date__c, fysm))
	                        { AmountFY += (gd.Approved_Amount__c != null) ? gd.Approved_Amount__c : 0; }
	                        if (isCurrentFiscalQuarter(gd.Allocation_Date__c, FiscalQuarterArray))
	                        { AmountFQ += (gd.Approved_Amount__c != null) ? gd.Approved_Amount__c : 0; }
	                        Count.add(gd.Gift__c);                    
	                    }
                	}
                }
            }                                          
            
            if (Appeals_to_Children.containsKey(c.Id))
            {
                for (Campaign cH : Appeals_to_Children.get(c.Id))
                {  
                  if (cH!=null){ //added by Sam  
                    cH.Overall_Gift_Amount__c = cH.Overall_Gift_Amount__c == null? 0.00 : cH.Overall_Gift_Amount__c;    
                    c.Overall_Gift_Amount__c += cH.Overall_Gift_Amount__c;  
                       
                    cH.Overall_One_Time_Gift_Count__c = cH.Overall_One_Time_Gift_Count__c == null? 0 : cH.Overall_One_Time_Gift_Count__c;                  
                    c.Overall_One_Time_Gift_Count__c += cH.Overall_One_Time_Gift_Count__c;
                    
                    cH.Overall_Recurring_Gift_Count__c = cH.Overall_Recurring_Gift_Count__c == null? 0 : cH.Overall_Recurring_Gift_Count__c;
                    c.Overall_Recurring_Gift_Count__c += cH.Overall_Recurring_Gift_Count__c;
                    
                    cH.Overall_Gifts_for_Current_Fiscal__c= cH.Overall_Gifts_for_Current_Fiscal__c == null? 0.00 :cH.Overall_Gifts_for_Current_Fiscal__c;                                        
                    c.Overall_Gifts_for_Current_Fiscal__c += cH.Overall_Gifts_for_Current_Fiscal__c;
                    
                    cH.Overall_Gifts_for_Current_Quarter__c = cH.Overall_Gifts_for_Current_Quarter__c == null? 0.00 : cH.Overall_Gifts_for_Current_Quarter__c;
                    c.Overall_Gifts_for_Current_Quarter__c += cH.Overall_Gifts_for_Current_Quarter__c;
                    
                    cH.Gifts_for_Current_Quarter__c = cH.Gifts_for_Current_Quarter__c == null? 0.00 : cH.Gifts_for_Current_Quarter__c;
                    c.Gifts_for_Current_Quarter__c += cH.Gifts_for_Current_Quarter__c;
                   }
                }
            }            
                 
            c.Overall_Gift_Amount__c += Amount + AmountH + AmountRD + AmountRDH;
            c.Gifts_for_Current_Quarter__c += AmountFQ + AmountRDFQ;
            c.Overall_Gifts_for_Current_Quarter__c += AmountFQ + AmountFQH + AmountRDFQ + AmountRDFQH;
            c.Overall_Gifts_for_Current_Fiscal__c += AmountFY + AmountFYH + AmountRDFY + AmountRDFYH;
            c.Gifts_for_Current_Fiscal__c += AmountFY + AmountRDFY;
            c.Recurring_Gift_Count__c += CountRD.size();
            c.Overall_One_Time_Gift_Count__c += (Count.size() + CountH.size());
            c.Overall_Recurring_Gift_Count__c += (CountRD.size() + CountRDH.size());
            c.Gift_Amount__c += Amount + AmountRD;
            c.One_Time_Gift_Count__c += Count.size();           
            
          
        }
        update Appeals;
    }
    
    public static void RollupExpenses(Set<String> AppealIDs)
    {
        if (AppealIDs == null || AppealIDs.size()<=0)
        return;

        List<Campaign> Appeals = [SELECT c.ActualCost , (SELECT Amount__c FROM Expenses__r) FROM Campaign c WHERE Id IN :AppealIDs FOR UPDATE];        
        
        for(Campaign c : Appeals)
        {
            Decimal Amount = 0;

            if (c.Expenses__r != null)           
            {
                for(Expense__c ex : c.Expenses__r)
                { Amount += (ex.Amount__c != null) ? ex.Amount__c : 0; }
            }                               
            
            c.ActualCost = Amount;  
        }         
        update Appeals;
    }
    
    public static Boolean isCurrentFiscal(Date aDate, Integer fysm)
   {
       Integer FYrStrtMonth = fysm;
       if (aDate == null)
           return false;
       
       //if the fiscal year starts on Jan 1st, then we only need to check the year
       if (FYrStrtMonth == 1 && aDate.Year() == Date.Today().Year())
       { return true; }       
       //if the current month is beyond the starting fiscal month, the fiscal year ends in the next calendar year
       if (Date.Today().Month() >= FYrStrtMonth && aDate >= Date.newInstance(Date.Today().Year(), FYrStrtMonth, 1) && aDate < Date.newInstance(Date.Today().Year() + 1, FYrStrtMonth, 1))
       { return true; }
       //if the current month has not reached the starting fiscal month, the fiscal year began in the previous calendar year       
       else if (Date.Today().Month() < FYrStrtMonth && aDate >= Date.newInstance(Date.Today().Year() - 1, FYrStrtMonth, 1) && aDate < Date.newInstance(Date.Today().Year(), FYrStrtMonth, 1))
       { return true; }
              
       return false;
   }
   
    public static List<Date> getFQArray(Integer fysm)
   {
        //Integer FYrStrtMonth = fysm;      
        Date FiscalYearStartDate;
        Integer currentQuarter = -1;    
        
        if (fysm == 0 || fysm == null)
            return null;
        
        if (Date.Today().Month() >= fysm)
        { FiscalYearStartDate = Date.newInstance(Date.Today().Year(), fysm, 1); }
        if (Date.Today().Month() < fysm)
        { FiscalYearStartDate = Date.newInstance(Date.Today().Year() - 1, fysm, 1); }

        // Jan/Feb/March, April/May/June, July/Aug/Sept, Oct/Nov/Dec { [Jan 1 2011, March 31 2011], [April 1 2011, June 30 2011], [July 1 2011, Sept 31 2011], [Oct 1 2011, Dec 31 2011] }
        List<List<Date>> FiscalQuarterArray = new List<List<Date>>();      

        Integer fy = FiscalYearStartDate.Year();
        for (Integer i = 0; i < 4; i++)
        {
            List<Date> aQuarter = new List<Date>();
            aQuarter.add(Date.newInstance(fy, fysm, 1));
            fysm += 2;
            if (fysm > 12)
            { fysm = Math.mod(fysm, 12); fy++; }
            
            /*for (Integer c = 0; c < 2; c++)
            {
                fysm++;
                if (fysm > 12)
                { fysm = 1; fy++;}                              
            }*/
            
            aQuarter.add(Date.newInstance(fy, fysm, Date.daysInMonth(fy, fysm)));
            fysm++;
            FiscalQuarterArray.add(aQuarter);
        }       
        
        for (Integer i = 0; i < 4; i++)     
        {           
            Date FQstart = FiscalQuarterArray[i].get(0);
            Date FQend = FiscalQuarterArray[i].get(1);
            
            System.debug('FQStart: ' + FQstart);
            System.debug('FQEnd: ' + FQend);
            
            if (Date.Today() >= FQstart && Date.Today() <= FQend)
            { currentQuarter = i; break; }
        }
        
        return FiscalQuarterArray[currentQuarter];
    }
    
   public static Boolean isCurrentFiscalQuarter(Date aDate, List<Date> FiscalQuarterArray)
   {      
                
        if (aDate >= FiscalQuarterArray.get(0) && aDate <= FiscalQuarterArray.get(1))
        {
            System.debug('aDate: ' + aDate);
            System.debug('0: ' + FiscalQuarterArray[0]);
            System.debug('1: ' + FiscalQuarterArray[1]);

            return true;
        }
        
        return false;
   }
}