Causeview Package Complete/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Volunteer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if constituent is a current volunteer</description>
        <inlineHelpText>Checked if constituent is a current volunteer</inlineHelpText>
        <label>Volunteer</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Role_Template__c.object
<CustomObject>
    <description>Used to develop and manage Volunteer Role descriptions</description>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This status determines whether the Volunteer Position Description is available for use by Opportunities and Positions</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Proposed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Role Template</label>
    <nameField>
        <label>Description Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Role Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Volunteer_Application__c.object
<CustomObject>
    <description>Used to manage and review the Applications submitted by Volunteers</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>The current status of the application (Submitted / In Screening, Screening Complete, Approved, Placed, Declined, Exited).</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted / In-Screening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Screening Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Placed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exited</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volunteer_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to populate MyGroups</description>
        <inlineHelpText>Used to populate MyGroups</inlineHelpText>
        <label>(Dep) Volunteer Opportunity</label>
        <referenceTo>Volunteer_Opportunity__c</referenceTo>
        <relationshipLabel>Volunteer Applications</relationshipLabel>
        <relationshipName>Volunteer_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The ID of the Volunteer Role the application is related to.</description>
        <inlineHelpText>The Volunteer Role that the Application is matched with</inlineHelpText>
        <label>Volunteer Role</label>
        <referenceTo>Volunteer_Role__c</referenceTo>
        <relationshipLabel>Volunteer Applications</relationshipLabel>
        <relationshipName>Volunteer_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The ID of the Individual making the application.</description>
        <label>Volunteer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Applications</relationshipLabel>
        <relationshipName>Volunteer_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Application</label>
    <nameField>
        <displayFormat>VA-{000000}</displayFormat>
        <label>Volunteer Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Volunteer_Opportunity__c.object
<CustomObject>
    <description>Used to track and manage the various Volunteer Opportunities within the Volunteer application.</description>
    <fields>
        <fullName>Program__c</fullName>
        <description>Volunteer program the opportunity is related to</description>
        <label>Program</label>
        <picklist>
            <picklistValues>
                <fullName>To be defined by organization</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Current status of volunteer opportunity (Proposed, Open, Filled, Completed, Cancelled).</description>
        <inlineHelpText>The current status of the Volunteer Opportunity</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Proposed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Filled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aborted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Volunteer Opportunity</label>
    <nameField>
        <label>Volunteer Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Volunteer_Role__c.object
<CustomObject>
    <description>Used to track and manage the required Volunteer Roles within the Volunteer Opportunities in the Causeview Volunteers application</description>
    <fields>
        <fullName>Role_Description_Templates__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Volunteer Position Description used by this Volunteer Position.</inlineHelpText>
        <label>Role Description Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Role_Template__c.Status__c</field>
                <operation>equals</operation>
                <value>Approved</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Role_Template__c</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Volunteer_Positions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Opportunity__c</fullName>
        <inlineHelpText>The Volunteer Opportunity that the role is related to</inlineHelpText>
        <label>Volunteer Opportunity</label>
        <referenceTo>Volunteer_Opportunity__c</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Volunteer_Positions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Volunteer Role</label>
    <nameField>
        <label>Volunteer Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Volunteer_Shift__c.object
<CustomObject>
    <description>Outlines the time shifts for each Volunteer Role</description>
    <fields>
        <fullName>End_Day__c</fullName>
        <description>End date of the volunteer shift (MM/DD/YYYY 12:00 AM). Required for all but &quot;Flexible&quot; frequencies.</description>
        <label>End Day</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>The date and time the volunteer shift ends (MM/DD/YYYY 12:00 AM).</description>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <description>Frequency of the shift (Flexible, One-Time, Weekly, Bi-Weekly, Monthly).</description>
        <label>Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Flexible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One-Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Shift_Date__c</fullName>
        <description>The date of the volunteer shift (MM/DD/YYYY) used with one-time shifts.</description>
        <label>Shift Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Day__c</fullName>
        <description>Start date of the volunteer shift (MM/DD/YYYY 12:00 AM) Required for all but &quot;Flexible&quot; frequencies.</description>
        <label>Start Day</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>The date and time the volunteer shift starts (MM/DD/YYYY 12:00 AM).</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Volunteer_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The ID of the Application of the volunteer assigned to the shift.</description>
        <inlineHelpText>The Application that the Shift is related to</inlineHelpText>
        <label>Volunteer Application</label>
        <referenceTo>Volunteer_Application__c</referenceTo>
        <relationshipName>Volunteer_Position_Shifts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Opportunity__c</fullName>
        <description>Volunteer opportunity that the role belongs to.</description>
        <formula>Volunteer_Role__r.Volunteer_Opportunity__r.Name</formula>
        <label>Volunteer Opportunity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Volunteer_Role__c</fullName>
        <description>The ID of the Volunteer Role the shift is for</description>
        <inlineHelpText>The related Volunteer Role</inlineHelpText>
        <label>Volunteer Role</label>
        <referenceTo>Volunteer_Role__c</referenceTo>
        <relationshipLabel>Volunteer Shifts</relationshipLabel>
        <relationshipName>Volunteer_Position_Shifts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Volunteer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Individual assigned to position shift.</description>
        <label>Volunteer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Volunteer_Position_Shifts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Shift</label>
    <nameField>
        <displayFormat>VS-{000000}</displayFormat>
        <label>Volunteer Shift Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/classes/testShifts.cls
@isTest
private class testShifts {
    @isTest static void test3() {
        //Program__c p = new Program__c(Name = 'TestProg');
        //insert p;
        Volunteer_Opportunity__c vopp = new Volunteer_Opportunity__c(Name = 'afas');
        insert vopp;
        Role_Template__c vpd = new Role_Template__c(Status__c = 'Approved');
        insert vpd;
        Volunteer_Role__c vp = new Volunteer_Role__c(Volunteer_Opportunity__c = vopp.Id, Role_Description_Templates__c = vpd.Id, Name = 'pos');
        insert vp;
        Volunteer_Shift__c shift = new Volunteer_Shift__c(Volunteer_Role__c = vp.Id, Start_Day__c = Date.Today(), End_Day__c = Date.Today(), Shift_Date__c = Date.Today(), Start_Time__c = DateTime.Now(), End_Time__c = DateTime.Now().addHours(2));
        insert shift;
        
        ShiftWrapper sw = new ShiftWrapper(shift);
        //HourWrapper hw = new HourWrapper(DateTime.Now(), DateTime.Now().addHours(2));
       //VolunteerUtil.serializeShiftWrapper(sw);
       // VolunteerUtil.serializeHourWrapper(hw);    
        PageReference pageRef = Page.ShiftEntry;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', shift.Id);        
        ApexPages.StandardController stdcontroller = new ApexPages.StandardController(shift);
        CShiftEntry controller = new CShiftEntry (stdcontroller);    
        controller.getPickLstValue();
        controller.getHours();
        controller.getMins();
        controller.getMeridiemOffset();
        controller.clear();     
        controller.selected.theShift.Frequency__c = 'Weekly';
        controller.selected.theShift.Shift_Date__c = Date.Today();
        controller.selected.theShift.Start_Day__c = Date.Today();
        controller.selected.theShift.End_Day__c = Date.Today();                
        controller.selected.startHours = '2';
        controller.selected.startMins = '15';
        controller.selected.startMeridiemOffset = 'PM';        
        controller.selected.endHours = '3';
        controller.selected.endMins = '15';
        controller.selected.endMeridiemOffset = 'PM';     
        controller.NumOfWeeks = 3;                
        controller.addShift();
        ApexPages.currentPage().getParameters().put('Index', '1');   
        controller.removeShift();
        controller.editShift();
        controller.updateShift();
        controller.cancelUpdate();
        controller.back();     
    }  
    
    
    @isTest static void test4() {
        //Program__c p = new Program__c(Name = 'TestProg');
        //insert p;
        Contact c = new Contact(lastName ='test');
        insert c;
        Volunteer_Opportunity__c vopp = new Volunteer_Opportunity__c(Name = 'afas');
        insert vopp;
        Role_Template__c vpd = new Role_Template__c(Status__c = 'Approved');
        insert vpd;
        Volunteer_Role__c vp = new Volunteer_Role__c(Volunteer_Opportunity__c = vopp.Id, Role_Description_Templates__c = vpd.Id, Name = 'pos');
        insert vp;
        Volunteer_Shift__c shift = new Volunteer_Shift__c(Volunteer_Role__c = vp.Id, Start_Day__c = Date.Today(), End_Day__c = Date.Today(), Shift_Date__c = Date.Today(), Start_Time__c = DateTime.Now(), End_Time__c = DateTime.Now().addHours(2));
        insert shift;
    
         ApexPages.currentPage().getParameters().put('id',c.id);
    
    
        CSearch controller = new CSearch (); 
        controller.getTypes();
        controller.refreshList();
    
    }
         @isTest static void test5() {
        //Program__c p = new Program__c(Name = 'TestProg');
        //insert p;
        Contact c = new Contact(lastName ='test');
        insert c;
        Volunteer_Opportunity__c vopp = new Volunteer_Opportunity__c(Name = 'afas');
        insert vopp;
        Role_Template__c vpd = new Role_Template__c(Status__c = 'Approved');
        insert vpd;
        Volunteer_Role__c vp = new Volunteer_Role__c(Volunteer_Opportunity__c = vopp.Id, Role_Description_Templates__c = vpd.Id, Name = 'pos');
        insert vp;
        Volunteer_Shift__c shift = new Volunteer_Shift__c(Volunteer_Role__c = vp.Id, Start_Day__c = Date.Today(), End_Day__c = Date.Today(), Shift_Date__c = Date.Today(), Start_Time__c = DateTime.Now(), End_Time__c = DateTime.Now().addHours(2));
        insert shift;
    
         ApexPages.currentPage().getParameters().put('id',vp.id);
    
    
        CSearchPos controller = new CSearchPos(); 
        controller.addConfirm();
        controller.addToCampaign();
        controller.getTypes();
        controller.refreshList();
    
    }
    
    
    @isTest static void test7() {
        //Program__c p = new Program__c(Name = 'TestProg');
        //insert p;
        Contact c = new Contact(lastName ='test');
        insert c;
        Volunteer_Opportunity__c vopp = new Volunteer_Opportunity__c(Name = 'afas');
        insert vopp;
        Role_Template__c vpd = new Role_Template__c(Status__c = 'Approved');
        insert vpd;
        Volunteer_Role__c vp = new Volunteer_Role__c(Volunteer_Opportunity__c = vopp.Id, Role_Description_Templates__c = vpd.Id, Name = 'pos');
        insert vp;
        Volunteer_Shift__c shift = new Volunteer_Shift__c(Volunteer_Role__c = vp.Id, Start_Day__c = Date.Today(), End_Day__c = Date.Today(), Shift_Date__c = Date.Today(), Start_Time__c = DateTime.Now(), End_Time__c = DateTime.Now().addHours(2));
        insert shift;
        Volunteer_Application__c va= new Volunteer_Application__c(Volunteer_Role__c = vp.Id, Volunteer__c = c.id);
        insert va;
    
         ApexPages.currentPage().getParameters().put('id',va.id);
    
    
        CPlaceApplicant controller = new CPlaceApplicant(); 
        //controller.volunteerId = c.Id;
        controller.place();
        
    
    }
    
    
          
}