Causeview Package Complete/src/objects/CVAdmin__c.object
<CustomObject>
    <fields>
        <fullName>Disable_Workflows_for_Sending_Receipts__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Workflows for Sending Receipts</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Enhanced_Batch_Interface_Waive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field keeps the waive value of Enable Enhanced Batch Interface.</description>
        <label>Enable Enhanced Batch Interface</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Enhanced_Fund_Accounting_Waive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Enhanced Fund Accounting</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Pledge_Installment_Model_Waive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Pledge Installment Model</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_Event_Registration_Receipt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Event Registration Receipt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_Gift_Receipt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Gift Receipt</label>
        <type>Checkbox</type>
    </fields>
    <label>CVAdmin</label>
    <nameField>
        <label>CVAdmin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CVAdmins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/src/classes/CVHealthCheckControllerTest.cls
@isTest
private class CVHealthCheckControllerTest{
    @istest static void CVHealthCheckControllerTest(){
        CVAdmin__c cvAdmin = new CVAdmin__c(name = 'Waive Settings', Disable_Workflows_for_Sending_Receipts__c = true, Enable_Enhanced_Batch_Interface_Waive__c = true,
                                            Enable_Enhanced_Fund_Accounting_Waive__c = true, Enable_Pledge_Installment_Model_Waive__c = true, Send_Event_Registration_Receipt__c = true,
                                            Send_Gift_Receipt__c = true);
        insert cvAdmin;
        causeview__App_Settings__c app_setting = GLAllocationfieldUpdateTriggerTest.appSettings();
        app_setting.causeview__Enable_Enhanced_Batch_Interface__c = true;
        app_setting.causeview__Enable_Enhanced_Fund_Accounting__c = true;
        app_setting.causeview__Enable_Pledge_Installment_Model__c = true;
        app_setting.causeview__Use_Workflows_for_Sending_Receipts__c = true;
        update app_setting;
        CVHealthCheckController cvhealth = new CVHealthCheckController();
        cvhealth.send_Gift_Receipt_status = true;
        cvhealth.SendEventRegistrationReceipt_status = true;
        cvhealth.updateWaiveSetting();
        //Test.startTest();
        //Test.setMock(WebServiceMock.class, new WebServiceMockImpl());
       cvhealth.updateWorkflowWaiveSetting();
        //cvhealth.workflowStatus();
       // Test.stopTest();
    }
}