Causeview Package Complete/src/objects/Event_Level__c.object
<CustomObject>
    <description>Causeview - event ticket and sponsorship levels</description>
    <fields>
        <fullName>Quantity_Remaining__c</fullName>
        <description>Quantity at Level remaining for sale</description>
        <formula>Quantity_Available__c -  Quantity_Sold__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quantity Remaining</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Quantity sold at this level</description>
        <label>Quantity Sold</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Event Level</label>
    <nameField>
        <label>Event Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Gift__c.object
<CustomObject>
    <description>Causeview - Any financial transactions including: gifts, product purchases, event registrations, membership renewals, etc.</description>
    <fields>
        <fullName>Total_Attendees_Purchased__c</fullName>
        <description>Sum of included event attendees based on event levels purchased</description>
        <inlineHelpText>Sum of included event attendees based on event levels purchased</inlineHelpText>
        <label>Total Attendees</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Gift_Detail__c.object
<CustomObject>
    <description>Causeview - Manages the allocation of your gifts across Funds, Appeals, Tributes, Products and Campaigns.</description>
    <fields>
        <fullName>Event_Level__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Event level purchased as part of Transaction</description>
        <label>Event Level</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The event level does not belong to the event you have allocated to.</errorMessage>
            <filterItems>
                <field>$Source.New_Campaign__c</field>
                <operation>equals</operation>
                <valueField>Event_Level__c.Event__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Event_Level__c</referenceTo>
        <relationshipLabel>Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gift__c</fullName>
        <label>Transaction</label>
        <referenceTo>Gift__c</referenceTo>
        <relationshipLabel>Allocations</relationshipLabel>
        <relationshipName>Gift_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Number_of_Attendees__c</fullName>
        <description>Calculates number of attendees based on Event Level and quantity purchased</description>
        <formula>Event_Level__r.Attendees_per_Level__c *  Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Number of included attendees based on quantity and Event Level</inlineHelpText>
        <label>Number of Attendees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>The quantity of this that was purchased</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Allocation</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Allocation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Transaction_Benefit__c.object
<CustomObject>
    <description>Causeview - captures all benefits included with Transaction</description>
    <label>Transaction Benefit</label>
    <nameField>
        <displayFormat>TBN-{0000000}</displayFormat>
        <label>Benefit No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Benefits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/classes/GiftDetailHandler.cls
public class GiftDetailHandler {
    public static void RollupTotals(List<Gift_Detail__c> records) {
        Set<string> giftIds = new Set<string>();
        Set<string> eventLevelIds = new Set<string>();
        for (Gift_Detail__c gd : records) {
            giftIds.add(gd.Gift__c);
        }
        for (Gift_Detail__c gd : records) {
            eventLevelIds.add(gd.Event_Level__c);
        }        
        List<Gift__c> gifts = [SELECT Id, Total_Attendees_Purchased__c, (SELECT Id, Number_of_Attendees__c FROM Gift_Allocations__r) FROM Gift__c WHERE Id IN :giftIds FOR UPDATE];
        for (Gift__c g : gifts) {
            Decimal total = 0;
            for (Gift_Detail__c  gd : g.Gift_Allocations__r) {
                total = total + gd.Number_of_Attendees__c;
            }
            g.Total_Attendees_Purchased__c = total;
        }
        update gifts;
        
        Map<id,sObject> giftdetailmap = Trigger.NewMap;
        
        List<Event_Level__c> event_levels = [SELECT Id, Name, Quantity_Sold__c, Quantity_Remaining__c ,(SELECT Id, Quantity__c FROM Allocations__r) FROM Event_Level__c WHERE Id IN :eventLevelIds FOR UPDATE];
        
       
        
        for(Gift_Detail__c g:records)
        {
            if(g.Event_Level__c != null)
            {
                for(Event_Level__c e:event_levels)
                {
                   if(e.Id == g.Event_Level__c)
                   {
                       if(e.Quantity_Remaining__c < g.Quantity__c)
                       {
                           giftdetailmap.get(g.Id).AddError('Quantity for '+e.Name+' is greater than Available Quantity');
                       }
                   }
                }
            } 
        }
        
        for (Event_Level__c g : event_levels) {
            Decimal total = 0;
            for (Gift_Detail__c  gd : g.Allocations__r) {
                total = total + gd.Quantity__c;
            }
            g.Quantity_Sold__c = total;
        }
        update event_levels ;
    }
    
    public static void ManageTransactionBenefitsInsert(List<Gift_Detail__c> records) {
        Map<Gift_Detail__c, string> eventLevelToCreate = new Map<Gift_Detail__c, string>();
        List<Transaction_Benefit__c> benefitsToInsert = new List<Transaction_Benefit__c>();
        for(Gift_Detail__c gd : records) {
            eventLevelToCreate.put(gd, gd.Event_Level__c);
        }
        
        benefitsToInsert = EventBenefitHelper.CreateTransactionBenefits(eventLevelToCreate);        
        if(benefitsToInsert.size() > 0){
            insert benefitsToInsert;
        }         
    }
    
    public static void ManageTransactionBenefitsUpdate(List<Gift_Detail__c> new_records, List<Gift_Detail__c> old_records) {
        Map<Gift_Detail__c, string> eventLevelToCreate = new Map<Gift_Detail__c, string>();
        Set<string> eventLevelToDelete = new Set<string>();    
        List<Transaction_Benefit__c> benefitsToInsert = new List<Transaction_Benefit__c>();
        List<Transaction_Benefit__c> benefitsToDelete = new List<Transaction_Benefit__c>();
        for(Integer i = 0; i < new_records.size(); i++) {
            if (new_records[i].Event_Level__c != old_records[i].Event_Level__c) {                
                if (new_records[i].Event_Level__c != null) { eventLevelToCreate.put(new_records[i], new_records[i].Event_Level__c); }
                if (old_records[i].Event_Level__c != null) { eventLevelToDelete.add(new_records[i].Id); }                
            }
        }
        
        benefitsToInsert = EventBenefitHelper.CreateTransactionBenefits(eventLevelToCreate);                   
        benefitsToDelete = EventBenefitHelper.DeleteTransactionBenefits(eventLevelToDelete);          
        if (benefitsToInsert.size() > 0){
            insert benefitsToInsert;
        }  
        if (benefitsToDelete.size() > 0){
            delete benefitsToDelete;
        }  
    }
    
    public static void ManageTransactionBenefitsDelete(List<Gift_Detail__c> records) {
        List<Transaction_Benefit__c> benefitsToDelete = new List<Transaction_Benefit__c>();
        Set<string> eventLevelToDelete = new Set<string>();  
        for(Gift_Detail__c gd : records) {
            if (gd.Event_Level__c != null) {                                
                eventLevelToDelete.add(gd.Id);             
            }
        }
        
        benefitsToDelete = EventBenefitHelper.DeleteTransactionBenefits(eventLevelToDelete);          
        if (benefitsToDelete.size() > 0){
            delete benefitsToDelete;
        }          
    }    
}