Causeview Package Complete/src/objects/Gift__c.object
<CustomObject>
    <description>Causeview - Any financial transactions including: gifts, product purchases, event registrations, membership renewals, etc.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Rollup of all payments with Status = Approved, Deposited, Refunded</description>
        <inlineHelpText>Sum of all payments with status (Approved, Deposited, Refunded)</inlineHelpText>
        <label>Approved Amount</label>
        <summarizedField>Payment__c.Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Payment__c.Status__c</field>
            <operation>equals</operation>
            <value>Approved, Deposited, Refunded, Invoiced</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Payment__c.Amount__c</field>
            <operation>notEqual</operation>
            <value>0</value>
        </summaryFilterItems>
        <summaryForeignKey>Payment__c.Donation__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Constituent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Individual</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Constituent)</relationshipLabel>
        <relationshipName>Gifts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recurring_Donation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recurring Gift</label>
        <referenceTo>Recurring_Donation__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Entered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acknowledged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Payment__c.object
<CustomObject>
    <description>Causeview - Payment records relating to a Transaction.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Constituent__c</fullName>
        <formula>IF(ISBLANK( Donation__r.Organization__c ), HYPERLINK(&quot;/&quot; &amp; Donation__r.Constituent__c, Donation__r.Constituent__r.FirstName &amp; &quot; &quot; &amp; Donation__r.Constituent__r.LastName,&quot;_self&quot;), HYPERLINK(&quot;/&quot; &amp; Donation__r.Organization__c, Donation__r.Organization__r.Name,&quot;_self&quot;))</formula>
        <label>Constituent</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Date of Payment</description>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Donation__c</fullName>
        <label>Transaction</label>
        <referenceTo>Gift__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Recurring_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Credit Card</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card - Offline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACH/PAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK Direct Debit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stock</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Kind</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3rd-Party Payment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Committed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refunded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Written Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACH Return</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Payment No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/RD_Allocation__c.object
<CustomObject>
    <description>Causeview - Recurring gift allocations.  Profile for creating allocation records when a new payment is made.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Identifies if allocation is active.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Recurring_Gift__c</fullName>
        <label>Recurring Gift</label>
        <referenceTo>Recurring_Donation__c</referenceTo>
        <relationshipLabel>Recurring Gift Allocations</relationshipLabel>
        <relationshipName>Recurring_Gift_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Recurring Gift Allocation</label>
    <nameField>
        <displayFormat>RGA-{0000000}</displayFormat>
        <label>RGA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Gift Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Recurring_Donation__c.object
<CustomObject>
    <description>Causeview - Captures recurring gifts</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount per payment</description>
        <label>Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Constituent__c</fullName>
        <label>Constituent</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recurring Gifts</relationshipLabel>
        <relationshipName>Recurring_Donations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Recurring Gift</label>
    <nameField>
        <displayFormat>RD-{00000}</displayFormat>
        <label>Recurring Gift No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Gifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/classes/TestRD.cls
@isTest 
private class TestRD {

    static testMethod void test()
    {
        Contact c = new Contact(LastName = 'Contact');
        insert c;
        Recurring_Donation__c rd = new Recurring_Donation__c(Constituent__c = c.Id, Amount__c = 10, Start_Date__c = Date.today());
        insert rd;
        Gift__c g = new Gift__c(Constituent__c = c.Id, Recurring_Donation__c = rd.Id, Status__c = 'Active');
        insert g;
        //Payment__c p = new Payment__c(Amount__c = 10, Donation__c = g.Id, Date__c = Date.today(), Status__c = 'Approved', Payment_Type__c = 'Credit Card');
        //insert p;
        RD_Allocation__c rda = new RD_Allocation__c(Amount__c = 10, Recurring_Gift__c = rd.Id, Active__c = True);
        insert rda;
        rda.Amount__c = 15;
        update rda;
        system.debug(rd.Amount__c);
        delete rda;  
        Gift__c g2 = new Gift__c(Recurring_Donation__c = rd.Id, Status__c = 'Active');
try {        insert g2; }
catch (exception ex) {}
    }
}