Causeview Package Complete/src/objects/Gift__c.object
<CustomObject>
    <description>Causeview - Any financial transactions including: gifts, product purchases, event registrations, membership renewals, etc.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Rollup of all payments with Status = Approved, Deposited, Refunded</description>
        <inlineHelpText>Sum of all payments with status (Approved, Deposited, Refunded)</inlineHelpText>
        <label>Approved Amount</label>
        <summarizedField>Payment__c.Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Payment__c.Status__c</field>
            <operation>equals</operation>
            <value>Approved, Deposited, Refunded, Invoiced</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Payment__c.Amount__c</field>
            <operation>notEqual</operation>
            <value>0</value>
        </summaryFilterItems>
        <summaryForeignKey>Payment__c.Donation__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <inlineHelpText>Recurring payment Id</inlineHelpText>
        <label>Reference #</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Entered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acknowledged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Payment__c.object
<CustomObject>
    <description>Causeview - Payment records relating to a Transaction.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CC_Reference__c</fullName>
        <description>Payment gateway reference number</description>
        <inlineHelpText>Payment gateway reference number</inlineHelpText>
        <label>Reference #</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Transaction_Date__c</fullName>
        <description>The date the CC was processed.</description>
        <label>CC Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Donation__c</fullName>
        <label>Transaction</label>
        <referenceTo>Gift__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Recurring_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StatusComment__c</fullName>
        <label>Status Comment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Committed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refunded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Written Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACH Return</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Payment No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <recordTypes>
        <fullName>Refund</fullName>
        <active>true</active>
        <description>Refunded credit card payment - processed via payment gateway</description>
        <label>Refund</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/classes/DonationAsyncTransaction.cls
global class DonationAsyncTransaction {
  
   global enum StatusResult { Success, Failure, NotFound, InvalidInput }
   
   global class DonationAsyncResult
   {
       webservice StatusResult Status { get; set; }
       webservice String StatusComment { get; set; }
       webservice String PaymentId { get; set; }
       webservice String GiftId { get; set; }
   }
   
   global class PaymentTransaction 
   { 
       webservice String RecurringPaymentId { get; set; }
       webservice String TransactionId { get; set; } 
       webservice Decimal Amount { get; set; } 
       webservice String Status { get; set; } 
       webservice String StatusComment { get; set; }
       webservice Date TransactionDate { get; set; } 
       webservice String ParentTransactionId {get; set; }
   }
    
   webservice static DonationAsyncResult TransactionUpsert(PaymentTransaction payment)
   {
     string debugStr = ' New transaction call with following info: ';
     debugstr += '\n TransactionId = ' + payment.TransactionId;
     debugstr += '\n RecurringPaymentId = ' + payment.RecurringPaymentId;
     debugstr += '\n Status = ' + payment.Status;
     debugstr += '\n ParentTransactionId = ' + payment.ParentTransactionId;
     debugstr += '\n Amount = ' + payment.Amount;
     System.debug(debugstr);
     
     DonationAsyncResult retVal = new DonationAsyncResult();
     
     try
     {
      
        if (payment.ParentTransactionId != null && payment.ParentTransactionId != '')
        {
          //process refund
          return RefundPayment(payment);
        }
       
        // if the transaction id exists: update the status on the Payment
        if (payment.TransactionId == null || payment.TransactionId == '')
        {
            retVal.Status = StatusResult.InvalidInput;
            retVal.StatusComment = 'Invalid Input: Transaction Id is null.';
            System.debug(retVal.StatusComment);
            return retVal;
        }
     
        List<Payment__c> payments = [Select Id, Status__c, CC_Reference__c, StatusComment__c, Donation__c FROM Payment__c WHERE CC_Reference__c = :payment.TransactionId];
        if (payments != null && payments.size()>0) {
            System.debug('Trans ID:' + payment.TransactionId + ' - Payment found, updating......');
            System.debug('New Status: ' + payment.Status);
            Payment__c p = payments[0];
            p.Status__c = payment.Status;
            p.StatusComment__c = payment.StatusComment;
            update p;
            
            retVal.GiftId = p.Donation__c;
            retVal.StatusComment = 'Payment record: ' + p.Id + ' updated, new status: ' + payment.Status; 
        }
        else {
        
            if (payment.RecurringPaymentId == null || payment.RecurringPaymentId == '') {
                retVal.StatusComment = 'Invalid Input: Recurring payment Id is null.';
                System.debug(retVal.StatusComment);
                retVal.Status = StatusResult.InvalidInput;
                return retVal;
            }
        
            // if the transaction id does not exists: check the recurringPaymentId
            System.debug('Trans ID:' + payment.TransactionId + ' - Inserting new Payment for a recurring donation......');
            List<Gift__c> donations = [SELECT id, Reference__c FROM Gift__c WHERE Status__c = 'Active Recurring' AND Reference__c = :payment.RecurringPaymentId];
            if (donations != null && donations.size()>0) {
                // if found: create a new payment record
                Payment__c p = new Payment__c();
                p.Amount__c = payment.Amount;
                p.CC_Reference__c = payment.TransactionId;
                p.CC_Transaction_Date__c = payment.TransactionDate;
                p.Donation__c = donations[0].Id;
                p.Status__c = payment.Status;
                p.StatusComment__c = payment.StatusComment;
            
                insert p;
                
                retVal.PaymentId = p.Id;
                retVal.GiftId = p.Donation__c;
                retVal.StatusComment = 'New Payment Id: ' + p.Id + ' ---Payment Amount:' + payment.Amount.format()+ '---Status:'+ payment.Status;
                System.debug(retVal.StatusComment);
            }
            else {
                // if not found: return :
                retVal.StatusComment = 'Was not able to locate Donation record based on Recurring payment id.'; 
                System.debug(retVal.StatusComment);
                retVal.Status = StatusResult.NotFound;
                return retVal;
            }//end else
        }
        
     }
     catch(Exception ex)
     {
        retVal.StatusComment = ex.getMessage(); 
        System.debug(retVal.StatusComment);
        retVal.Status = StatusResult.Failure;
        return retVal;
     }
     
     retVal.Status = StatusResult.Success;
     return retVal;
   }
   
   private static DonationAsyncResult RefundPayment(PaymentTransaction payment)
   {
      System.Debug('refuding a payment, Parent Trans ID: '+ payment.ParentTransactionId);
      DonationAsyncResult retVal = new DonationAsyncResult();
      
      
      List<Payment__c> pays = [SELECT Id, Donation__c FROM Payment__c WHERE CC_Reference__c = : payment.ParentTransactionId];
      if (pays == null || pays.size()<=0)
      {
          retVal.Status = StatusResult.NotFound;
          retVal.StatusComment = 'original transaction was not found, Reference=' + payment.ParentTransactionId; 
          System.Debug(retVal.StatusComment);
          return retVal;       
      }
      
      
      Payment__c p = new Payment__c();
      p.Amount__c = payment.Amount;
      p.CC_Reference__c = payment.TransactionId;
      p.CC_Transaction_Date__c = payment.TransactionDate;
      p.Donation__c = pays[0].Donation__c;
      p.Status__c = payment.Status;
      p.StatusComment__c = payment.StatusComment;      
      insert p;
      
      retVal.StatusComment = 'New payment record created (refunded), Id='+ p.Id; 
      System.Debug(retVal.StatusComment);
      retVal.Status = StatusResult.Success;
      retVal.PaymentId = p.Id;
      retVal.GiftId = pays[0].Donation__c;
      return retVal;
   }

}