Causeview Package Complete/src/objects/Gift__c.object
<CustomObject>
    <description>Causeview - Any financial transactions including: gifts, product purchases, event registrations, membership renewals, etc.</description>
    <fields>
        <fullName>Constituent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Individual</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Constituent)</relationshipLabel>
        <relationshipName>Gifts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Receipt__c.object
<CustomObject>
    <description>Causeview - Tax receipt for transaction records.</description>
    <fields>
        <fullName>Constituent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Captures the constituent ID for email receipting purposes.  Hidden to end users.</description>
        <label>Constituent</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gift__c</fullName>
        <label>Gift</label>
        <referenceTo>Gift__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Receipt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <recordTypes>
        <fullName>Pending</fullName>
        <active>true</active>
        <description>Receipt pending to be issued.</description>
        <label>Pending</label>
    </recordTypes>
    <recordTypes>
        <fullName>Void</fullName>
        <active>true</active>
        <description>Void receipt</description>
        <label>Void</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/classes/ReceiptTests.cls
@isTest
class ReceiptTests {

     static testMethod void test1() {
         RecordType rt = [SELECT Id,Name FROM RecordType WHERE SobjectType = 'causeview__Receipt__c' AND Name = 'Pending' LIMIT 1];
         Contact c = new Contact(LastName = 'dsadasd', Email = 'breakeven@breakeveninc.com');
         insert c;
         Gift__c g = new Gift__c(Constituent__c = c.Id);
         insert g;
         Receipt__c r = new Receipt__c(RecordTypeId = rt.Id, Constituent__c = c.Id, Gift__c = g.Id);
         insert r;
         Test.startTest();
        PageReference pageRef = Page.ReceiptPrinter;
        pageRef.getParameters().put('id', r.Id);
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController std = new ApexPages.StandardController(r);
        ReceiptPrinter controller = new ReceiptPrinter(std);
        controller.rerender();
        controller.format = True;
        controller.print();
        controller.format = False;
        controller.print();
        controller.getItems();
        PageReference pageRef2 = Page.ReceiptPrinter;
        pageRef2.getParameters().put('id', r.Id);
        Test.setCurrentPage(pageRef2);
        ApexPages.StandardController std2 = new ApexPages.StandardController(r);
        ReceiptPrinter controller2 = new ReceiptPrinter(std2);
        controller2.rerender();
        controller2.format = True;
        controller2.print();
        controller2.format = False;
        controller2.print();
        controller2.getItems();
        Test.stopTest();
     }
    
}