Causeview Package Complete/src/objects/Gift_Detail__c.object
<CustomObject>
    <description>Causeview - Manages the allocation of your gifts across Funds, Appeals, Tributes, Products and Campaigns.</description>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Payment associated to the allocation record.</description>
        <inlineHelpText>Payment associated to the allocation record.</inlineHelpText>
        <label>Payment</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Gift__c</field>
                <operation>equals</operation>
                <valueField>Payment__c.Donation__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Gift Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Allocation</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Allocation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Payment__c.object
<CustomObject>
    <description>Causeview - Payment records relating to a Transaction.</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Payment No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/classes/PaymentWrapper.cls
public class PaymentWrapper {
        public String id { get; set; }
        public Payment__c thePayment {get;set;}
        public List<Gift_Detail__c> theGiftDetails {get;set;}
       
        public boolean isRemind {get;set;}
        public Integer daysBefore {get;set;}
        
        public PaymentWrapper(Payment__c p)
        {
            id = 'NotSavedYet-' + DateTime.now().format('hmmss');
            thePayment = p;
            system.debug('thePayment==>'+p);
            theGiftDetails = new List<Gift_Detail__c>();
            theGiftDetails.add(new Gift_Detail__c());
        }    
            

            public List<selectOption> getCustompicklist() 
            {
             list<selectoption> options= new list<selectoption>();
             options.add(new selectoption('Cash','Cash'));
             options.add(new selectoption('Check','Check'));
             options.add(new selectoption('Credit Card - Offline','Credit Card - Offline'));
             options.add(new selectoption('Stock','Stock'));
             options.add(new selectoption('Property','Property'));
             options.add(new selectoption('In Kind','In Kind'));
             options.add(new selectoption('Other','Other'));
             return options;
          } 
    
      //}
    }