Causeview Package Complete/src/objects/givingpowerSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Causeview communication and notification templates.</description>
    <fields>
        <fullName>ConsolidatedReceiptPDFDocId__c</fullName>
        <inlineHelpText>The ID of the HTML Document used as Consolidated Receipt&apos;s PDF Template</inlineHelpText>
        <label>Consolidated Receipt PDF Document Id</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DupeConsolidatedReceiptPDFDocId__c</fullName>
        <label>Dupe Consolidated Receipt PDF Doc Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Causeview Receipt Templates</label>
</CustomObject>

Causeview Package Complete/src/classes/ConsolidatedReceiptPDFTemplateController.cls
//Generates a Consolidated Receipt PDF, based on the given Consolidated Receipt PDF Template.


public with sharing class ConsolidatedReceiptPDFTemplateController {  
  public string relatedToType { get; set; }
  public string recipientType { get; set; }
  public String isDupe { get; set; }  
  public string relatedToId { get; set; }
  public string recipientId { get; set; }

  
  public string content { 
    get {
      string retVal = '';
      Id docId = null;
      
      // read custom settings to get the desired documents to generate Consolidated Receipt pdf.
      List<givingpowerSettings__c> settingsRecords = [SELECT DupeConsolidatedReceiptPDFDocId__c, ConsolidatedReceiptPDFDocId__c FROM givingpowerSettings__c WHERE name = 'settings'];
      if (settingsRecords != null && settingsRecords.size()>0) {
         givingpowerSettings__c settings = settingsRecords[0];
         if (isDupe == 'True')
         { 
             docId = (Id)settings.DupeConsolidatedReceiptPDFDocId__c;     
         }
         else
         {
             docId = (Id)settings.ConsolidatedReceiptPDFDocId__c;
         }
      }
      
      
      try 
      {      
       retVal = DonationUtility.MergeDocument(docId, relatedToType, relatedToId, recipientType, recipientId);
      }
      catch(Exception ex)
      {
        retVal = ex.getMessage() + ' doc id: ' + docId + ' recipientType=Contact' + ' recipientId=' + ApexPages.currentPage().getParameters().get('cid');
      }

      //return
      return retVal;
    }
  }
  
}