Causeview Package Complete/src/objects/givingpowerSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Causeview communication and notification templates.</description>
    <fields>
        <fullName>Recurring_Batch_Size__c</fullName>
        <defaultValue>5</defaultValue>
        <label>Recurring Batch Size</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Causeview Receipt Templates</label>
</CustomObject>

Causeview Package Complete/src/classes/paymentsToTransactionMapping.cls
/*Payment Reassign Script
Check all Payments belonging to Transactions that are linked to Recurring Gifts
Verify the Payment year matches with the Transaction year
If the years do not match, then reassign the Payment and Allocations to the correct Transaction
Payment in 2013 is linked to Transaction in 2013
Payment in 2014 is linked to Transaction in 2014
This only applies to Transactions with Recurring Gift lookup populated.
*/

global class paymentsToTransactionMapping implements Schedulable {
    global void execute(SchedulableContext SC)     
    {
        decimal batchSize;
        List<givingpowerSettings__c> settingsRecords = [SELECT Recurring_Batch_Size__c FROM givingpowerSettings__c WHERE name = 'settings'];
        if (settingsRecords != null && settingsRecords.size()>0) {
            batchSize = settingsRecords[0].Recurring_Batch_Size__c;
        }
        if (batchSize==null)
          batchSize=5;
        paymentUpdateBatchable p = new paymentUpdateBatchable(); //creating object of "paymentUpdateBatchable" apex batch class
        ID myBatchJobID = database.executebatch(p, batchSize.intValue());
    }

}