Causeview Package Complete/src/objects/givingpowerSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Causeview communication and notification templates.</description>
    <fields>
        <fullName>ConsolidatedReceiptPDFDocId__c</fullName>
        <inlineHelpText>The ID of the HTML Document used as Consolidated Receipt&apos;s PDF Template</inlineHelpText>
        <label>Consolidated Receipt PDF Document Id</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DupeAttachTemplateId__c</fullName>
        <label>Duplicate Receipt PDF Document Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DupeConsolidatedReceiptPDFDocId__c</fullName>
        <label>Dupe Consolidated Receipt PDF Doc Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReceiptPDFDocId__c</fullName>
        <inlineHelpText>The ID of the HTML Document used as Receipt&apos;s PDF Template</inlineHelpText>
        <label>Receipt PDF Document Id</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Causeview Receipt Templates</label>
</CustomObject>

Causeview Package Complete/src/objects/Receipt__c.object
<CustomObject>
    <description>Causeview - Tax receipt for transaction records.</description>
    <fields>
        <fullName>Receipt_Type__c</fullName>
        <description>Defines the type of receipt either single or consolidated.</description>
        <inlineHelpText>Single: receipt is linked to a single payment
Consolidated: receipt is linked to multiple payments</inlineHelpText>
        <label>Receipt Type</label>
        <picklist>
            <picklistValues>
                <fullName>Single</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Consolidated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Receipt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/classes/ReceiptAttachExportController.cls
public with sharing class ReceiptAttachExportController {

    public string content { 
        get {
                string retVal = '';
                Id docId = null;
                
                // read custom settings
                List<givingpowerSettings__c> settingsRecords = [SELECT DupeAttachTemplateId__c, ReceiptPDFDocId__c, DupeConsolidatedReceiptPDFDocId__c, ConsolidatedReceiptPDFDocId__c FROM givingpowerSettings__c WHERE name = 'settings'];
                if (settingsRecords != null && settingsRecords.size()>0) {
                givingpowerSettings__c settings = settingsRecords[0];
                //If Receipt is of type "Consolidated" set docId with Consolidated doc Ids.
                if([Select Id, Receipt_Type__c From Receipt__c Where Id = :ApexPages.currentPage().getParameters().get('rid') LIMIT 1].Receipt_Type__c == 'Consolidated') {
                    if (ApexPages.currentPage().getParameters().get('isdupe') == 'True')
                    { docId = (Id)settings.DupeConsolidatedReceiptPDFDocId__c; }
                    else
                    { docId = (Id)settings.ConsolidatedReceiptPDFDocId__c; }
                } else {
                    if (ApexPages.currentPage().getParameters().get('isdupe') == 'True')
                    { docId = (Id)settings.DupeAttachTemplateId__c; }
                    else
                    { docId = (Id)settings.ReceiptPDFDocId__c; }                    
                }
            }
            
            // load document
            
            System.Debug('Nitin docId==='+docId);
            System.Debug('Nitin rid==='+ApexPages.currentPage().getParameters().get('rid'));
            System.Debug('Nitin cid==='+ApexPages.currentPage().getParameters().get('cid'));
            try {
                retVal = DonationUtility.MergeDocument(docId, 'Receipt__c', ApexPages.currentPage().getParameters().get('rid'), 'Contact', ApexPages.currentPage().getParameters().get('cid'));
            }
            catch(Exception ex)
            {
                retVal = ex.getMessage() + ' doc id: ' + docId + ' recipientType=Contact' + ' recipientId=' + ApexPages.currentPage().getParameters().get('cid');
            }
            system.debug('Nitin retVal===='+retVal);
            //return
            return retVal;
        }
    }
    
    /*public Receipt__c recipient { get; set; }    
    public Contact relatedTo { get; set; } 
    */
    
    public ReceiptAttachExportController () {
 
    }
}