Causeview Package Complete/src/objects/givingpowerSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Causeview communication and notification templates.</description>
    <fields>
        <fullName>Org_Wide_Email_ID__c</fullName>
        <description>The Salesforce ID of the Organization Wide Email address you would like your Automatic receipting messages to come from.</description>
        <inlineHelpText>The Salesforce ID of the Organization Wide Email address you would like your Automatic receipting messages to come from.</inlineHelpText>
        <label>Org Wide Email ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X15_DAYS_CC_Expiry_Email_Template__c</fullName>
        <description>Template used to send to donor when today is 15 days before credit card expiry date.</description>
        <inlineHelpText>Populate with Salesforce email template Id. Template used to send to donor when today is 15 days before credit card expiry date.</inlineHelpText>
        <label>15 DAYS - CC Expiry Email Template</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X30_DAYS_CC_Expiry_Email_Template__c</fullName>
        <description>Template used to send to donor when today is 30 days before credit card expiry date.</description>
        <inlineHelpText>Populate with Salesforce email template Id. Template used to send to donor when today is 30 days before credit card expiry date.</inlineHelpText>
        <label>30 DAYS - CC Expiry Email Template</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Causeview Receipt Templates</label>
</CustomObject>

Causeview Package Complete/src/objects/RD_Allocation__c.object
<CustomObject>
    <description>Causeview - Recurring gift allocations.  Profile for creating allocation records when a new payment is made.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Recurring_Gift__c</fullName>
        <label>Recurring Gift</label>
        <referenceTo>Recurring_Donation__c</referenceTo>
        <relationshipLabel>Recurring Gift Allocations</relationshipLabel>
        <relationshipName>Recurring_Gift_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Recurring Gift Allocation</label>
    <nameField>
        <displayFormat>RGA-{0000000}</displayFormat>
        <label>RGA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Gift Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Recurring_Donation__c.object
<CustomObject>
    <description>Causeview - Captures recurring gifts</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount per payment</description>
        <label>Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Constituent__c</fullName>
        <label>Constituent</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recurring Gifts</relationshipLabel>
        <relationshipName>Recurring_Donations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Expiry_Date__c</fullName>
        <description>Date of credit card expiry.</description>
        <label>Credit Card Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <description>The link to the cc processing company&apos;srecurring donation record</description>
        <label>Reference #</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>URL_Safe_Key__c</fullName>
        <formula>SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE( Encrypted_Key__c , &apos;%&apos;, &apos;%25&apos;), &apos;=&apos; ,&apos;%3D&apos;), &apos;/&apos; ,&apos;%2F&apos;), &apos;?&apos; ,&apos;%3F&apos;), &apos;#&apos;, &apos;%23&apos;), &apos;&amp;&apos;, &apos;%26&apos;) , &apos;+&apos;, &apos;%2B&apos;)</formula>
        <label>URL Safe Key</label>
        <type>Text</type>
    </fields>
    <label>Recurring Gift</label>
    <nameField>
        <displayFormat>RD-{00000}</displayFormat>
        <label>Recurring Gift No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Gifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Receive_CC_Updates__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Mark this box if you would like to receive a 7 day notification of expiring Recurring Donations</description>
        <inlineHelpText>Mark this box if you would like to receive a 7 day notification of expiring Recurring Donations</inlineHelpText>
        <label>Receive CC Updates</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Causeview Package Complete/src/classes/CCExpiryUtil.cls
public with sharing class CCExpiryUtil {
     public static void RenewCCs(List<Recurring_Donation__c> RDs) {
         List<Messaging.SingleEmailMessage> theMails = new List<Messaging.SingleEmailMessage>();
         List<User> theUsers = [SELECT Id FROM User WHERE Receive_CC_Updates__c = True];       
         givingpowerSettings__c CVTemplates = SFHelper.GetDefaultCVTemplates();
         //TODO: Custom Settings
         
         for (Recurring_Donation__c rd : RDs)
         {
System.debug('#####  Recurring_Donation__c  #####'+rd);
System.debug('#####  CVTemplates  #####'+CVTemplates);

             if (rd.Reference__c == null || rd.Reference__c == '')
             { continue; }
             if (rd.Amount__c == 0 || rd.Amount__c == null) 
             { continue; }
             if (rd.causeview__Status__c == 'Cancelled') 
             { continue; }
             else
             {
                 Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                 mail.setWhatId(rd.Id);   
                 mail.setTargetObjectId(rd.Constituent__c);
                 mail.setOrgWideEmailAddressId(CVTemplates.Org_Wide_Email_ID__c);
                 if (rd.Credit_Card_Expiry_Date__c == Date.Today()+7)
                 { 
                     for (User u : theUsers)
                     {
                         insert new Task (ActivityDate = Date.Today()+7, 
                                          OwnerId = u.Id, 
                                          Subject = 'Expired Credit Card for Shareplan', 
                                          WhatId = rd.Id, 
                                          Description = 'Donor has been sent an e-mail (or snail mail), and a reminder e-mail with no response. Please follow up with a phone call to obtain updated credit card information. Check Activity History of the Recurring Donation for details.',
                                          IsReminderSet = True,
                                          ReminderDateTime = DateTime.Now());
                     }
                 }          
                 if (CVTemplates != null)
                 {       
                     if ((rd.Credit_Card_Expiry_Date__c == Date.Today()+15) && (CVTemplates.X15_DAYS_CC_Expiry_Email_Template__c != ''))
                     { 
                        mail.setTemplateID(CVTemplates.X15_DAYS_CC_Expiry_Email_Template__c); theMails.add(mail); 
                     }
                     else if ((rd.Credit_Card_Expiry_Date__c == Date.Today()+30) && (CVTemplates.X30_DAYS_CC_Expiry_Email_Template__c != ''))
                     { 
                        mail.setTemplateID(CVTemplates.X30_DAYS_CC_Expiry_Email_Template__c); theMails.add(mail); 
                     }                                                                  
                 }
             }
         }        
         Messaging.sendEmail(theMails,false);
     }
     
    static testMethod void testMe()
    {
        Contact c = new Contact(LastName = 'sdsd');
        insert c;
        Recurring_Donation__c rd1 = new Recurring_Donation__c(Amount__c = 25, Start_Date__c = Date.Today(), Reference__c = 'sdsd', Constituent__c = c.Id, Credit_Card_Expiry_Date__c = Date.Today()+30);
        insert rd1;
        RD_Allocation__c rda1 = new RD_Allocation__c(Recurring_Gift__c = rd1.Id, Amount__c = 25);
        insert rda1;
        Recurring_Donation__c rd2 = new Recurring_Donation__c(Amount__c = 25, Start_Date__c = Date.Today(), Reference__c = 'sdsd', Constituent__c = c.Id, Credit_Card_Expiry_Date__c = Date.Today()+15);
        insert rd2;
        RD_Allocation__c rda2 = new RD_Allocation__c(Recurring_Gift__c = rd2.Id, Amount__c = 25);
        insert rda2;
        Recurring_Donation__c rd3 = new Recurring_Donation__c(Amount__c = 25, Start_Date__c = Date.Today(), Reference__c = 'sdsd', Constituent__c = c.Id, Credit_Card_Expiry_Date__c = Date.Today()+7);
        insert rd3;
        RD_Allocation__c rda3 = new RD_Allocation__c(Recurring_Gift__c = rd3.Id, Amount__c = 25);
        insert rda3;  
        Set<Id>RDIDS = new Set<Id>();
        RDIDS.add(rd1.id);
        RDIDS.add(rd2.id);        
        RDIDS.add(rd3.id);        
        List<Recurring_Donation__c> rds = [SELECT r.Id, r.Constituent__c, r.Credit_Card_Expiry_Date__c, r.causeview__Status__c, r.Amount__c, r.Reference__c, r.URL_Safe_Key__c FROM Recurring_Donation__c r WHERE r.Id IN :RDIDS];      
        
        System.Schedule('Test', '0 0 0 3 9 ? 2022', new CCExpiryScheduler());
        CCExpiryUtil.RenewCCs(rds);
        Database.executeBatch(new CCExpiryBatch(), 5); 
    }
    static testMethod void testMe2()
    {     
        Test.startTest();
        string jobId = System.Schedule('Test', '0 0 0 3 9 ? 2022', new CCExpiryScheduler());   
        CronTrigger ct = [SELECT id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId]; 
        System.assertEquals('0 0 0 3 9 ? 2022', ct.CronExpression);
        System.assertEquals(0, ct.TimesTriggered);
        System.assertEquals('2022-09-03 00:00:00',
        String.valueOf(ct.NextFireTime));
        Test.stopTest();
        //System.assertNotEquals('testScheduledApexFromTestMethodUpdated', [SELECT id, name FROM account WHERE id = :a.id].name);
    }
}