Causeview Package Complete/src/objects/givingpowerSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Causeview communication and notification templates.</description>
    <fields>
        <fullName>Org_Wide_Email_ID__c</fullName>
        <description>The Salesforce ID of the Organization Wide Email address you would like your Automatic receipting messages to come from.</description>
        <inlineHelpText>The Salesforce ID of the Organization Wide Email address you would like your Automatic receipting messages to come from.</inlineHelpText>
        <label>Org Wide Email ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X15_DAYS_CC_Expiry_Email_Template__c</fullName>
        <description>Template used to send to donor when today is 15 days before credit card expiry date.</description>
        <inlineHelpText>Populate with Salesforce email template Id. Template used to send to donor when today is 15 days before credit card expiry date.</inlineHelpText>
        <label>15 DAYS - CC Expiry Email Template</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X30_DAYS_CC_Expiry_Email_Template__c</fullName>
        <description>Template used to send to donor when today is 30 days before credit card expiry date.</description>
        <inlineHelpText>Populate with Salesforce email template Id. Template used to send to donor when today is 30 days before credit card expiry date.</inlineHelpText>
        <label>30 DAYS - CC Expiry Email Template</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Causeview Receipt Templates</label>
</CustomObject>

Causeview Package Complete/src/objects/Recurring_Donation__c.object
<CustomObject>
    <description>Causeview - Captures recurring gifts</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount per payment</description>
        <label>Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Constituent__c</fullName>
        <label>Constituent</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recurring Gifts</relationshipLabel>
        <relationshipName>Recurring_Donations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Expiry_Date__c</fullName>
        <description>Date of credit card expiry.</description>
        <label>Credit Card Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <description>The link to the cc processing company&apos;srecurring donation record</description>
        <label>Reference #</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>Recurring Gift</label>
    <nameField>
        <displayFormat>RD-{00000}</displayFormat>
        <label>Recurring Gift No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Gifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Receive_CC_Updates__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Mark this box if you would like to receive a 7 day notification of expiring Recurring Donations</description>
        <inlineHelpText>Mark this box if you would like to receive a 7 day notification of expiring Recurring Donations</inlineHelpText>
        <label>Receive CC Updates</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Causeview Package Complete/src/classes/CCExpiryUtility.cls
public with sharing class CCExpiryUtility {
    public static void RenewCCs(List<Recurring_Donation__c> RDs) {
         List<Messaging.SingleEmailMessage> theMails = new List<Messaging.SingleEmailMessage>();                //Master list to hold emails that will be sent
         List<User> theUsers = [SELECT Id FROM User WHERE Receive_CC_Updates__c = True];             //List of users     
         givingpowerSettings__c CVTemplates = SFHelper.GetDefaultCVTemplates();
    
         //TODO: Wrap/Add logic that checks values in the Custom Settings object (causeview__App_Settings__c) and processes accordingly
         
         for (Recurring_Donation__c rd : RDs) {
            System.debug('#####  Recurring_Donation__c  #####'+rd);
            System.debug('#####  CVTemplates  #####'+CVTemplates);

            if (rd.Reference__c == null || rd.Reference__c == ''){ continue; }
            if (rd.Amount__c == 0 || rd.Amount__c == null) { continue; }
            if (rd.causeview__Status__c == 'Cancelled') { continue; }
            else{
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setWhatId(rd.Id);   
                mail.setTargetObjectId(rd.Constituent__c);
                mail.setOrgWideEmailAddressId(CVTemplates.Org_Wide_Email_ID__c);
                if (rd.Credit_Card_Expiry_Date__c == Date.Today()+7) { 
                     for (User u : theUsers){
                         insert new Task (ActivityDate = Date.Today()+7, 
                                          OwnerId = u.Id, 
                                          Subject = 'Expired Credit Card for Shareplan', 
                                          WhatId = rd.Id, 
                                          Description = 'Donor has been sent an e-mail (or snail mail), and a reminder e-mail with no response. Please follow up with a phone call to obtain updated credit card information. Check Activity History of the Recurring Donation for details.',
                                          IsReminderSet = True,
                                          ReminderDateTime = DateTime.Now());
                     }
                 }          
                 if (CVTemplates != null){    
                    //Add email to list if CC expires in 15 Days   
                     if ((rd.Credit_Card_Expiry_Date__c == Date.Today()+15) && (CVTemplates.X15_DAYS_CC_Expiry_Email_Template__c != '')){ 
                        mail.setTemplateID(CVTemplates.X15_DAYS_CC_Expiry_Email_Template__c); theMails.add(mail); 
                     }
                     //Add email to list if CC expires in 30 Days
                     else if ((rd.Credit_Card_Expiry_Date__c == Date.Today()+30) && (CVTemplates.X30_DAYS_CC_Expiry_Email_Template__c != '')){ 
                        mail.setTemplateID(CVTemplates.X30_DAYS_CC_Expiry_Email_Template__c); theMails.add(mail); 
                     }                                                                  
                 }
             }
         }        
         Messaging.sendEmail(theMails,false);
     }
}