Causeview Package Complete/src/objects/Recurring_Donation__c.object
<CustomObject>
    <description>Causeview - Captures recurring gifts</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount per payment</description>
        <label>Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Constituent__c</fullName>
        <label>Constituent</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recurring Gifts</relationshipLabel>
        <relationshipName>Recurring_Donations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Expiry_Date__c</fullName>
        <description>Date of credit card expiry.</description>
        <label>Credit Card Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <description>The link to the cc processing company&apos;srecurring donation record</description>
        <label>Reference #</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL_Safe_Key__c</fullName>
        <formula>SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE( Encrypted_Key__c , &apos;%&apos;, &apos;%25&apos;), &apos;=&apos; ,&apos;%3D&apos;), &apos;/&apos; ,&apos;%2F&apos;), &apos;?&apos; ,&apos;%3F&apos;), &apos;#&apos;, &apos;%23&apos;), &apos;&amp;&apos;, &apos;%26&apos;) , &apos;+&apos;, &apos;%2B&apos;)</formula>
        <label>URL Safe Key</label>
        <type>Text</type>
    </fields>
    <label>Recurring Gift</label>
    <nameField>
        <displayFormat>RD-{00000}</displayFormat>
        <label>Recurring Gift No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Gifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/classes/CCExpiryBatch.cls
global class CCExpiryBatch implements Database.Batchable<sObject>, Database.Stateful {
    
    global final Date thirty;
    global final Date fifteen;
    global final Date seven; 
    global Integer success;
    global Integer total;    
     public string query;
     
     
     
    global CCExpiryBatch()
    {
    
        
        
    
        thirty = Date.today()+30;
        fifteen = Date.today()+15;
        seven = Date.today()+7;
        success = 0;
        total = 0;
    }    
    
    global Database.Querylocator start(Database.BatchableContext BC) {
        if (!System.Test.isRunningTest())
        {query = 'SELECT r.Id, r.Constituent__c, r.Credit_Card_Expiry_Date__c, r.causeview__Status__c, r.Amount__c, r.Reference__c, r.URL_Safe_Key__c FROM Recurring_Donation__c r WHERE r.Credit_Card_Expiry_Date__c = :thirty OR r.Credit_Card_Expiry_Date__c = :fifteen OR r.Credit_Card_Expiry_Date__c = :seven' ;}        
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope)
    {      
        CCExpiryUtil.RenewCCs((List<Recurring_Donation__c>)scope);
    }
    
    global void finish(Database.BatchableContext BC) {}
}