Causeview Package Complete/src/objects/Volunteer_Role__c.object
<CustomObject>
    <description>Used to track and manage the required Volunteer Roles within the Volunteer Opportunities in the Causeview Volunteers application</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>The end date of the last associated Volunteer Position Shift.</description>
        <label>End Date</label>
        <summarizedField>Volunteer_Shift__c.Shift_Date__c</summarizedField>
        <summaryForeignKey>Volunteer_Shift__c.Volunteer_Role__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The start date of the earliest associated Volunteer Position Shift.</description>
        <label>Start Date</label>
        <summarizedField>Volunteer_Shift__c.Shift_Date__c</summarizedField>
        <summaryForeignKey>Volunteer_Shift__c.Volunteer_Role__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Volunteer Role</label>
    <nameField>
        <label>Volunteer Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Volunteer_Shift__c.object
<CustomObject>
    <description>Outlines the time shifts for each Volunteer Role</description>
    <fields>
        <fullName>Day_of_the_Week__c</fullName>
        <description>The day of the week the volunteer shift falls on.</description>
        <inlineHelpText>The day of the week the Volunteer Position Shift falls on</inlineHelpText>
        <label>Day of the Week</label>
        <picklist>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Duration_Hours__c</fullName>
        <description>The duration of each shift in hours (End Time - Start Time).</description>
        <formula>( End_Time__c -  Start_Time__c) *24</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duration (Hours)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Day__c</fullName>
        <description>End date of the volunteer shift (MM/DD/YYYY 12:00 AM). Required for all but &quot;Flexible&quot; frequencies.</description>
        <label>End Day</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>The date and time the volunteer shift ends (MM/DD/YYYY 12:00 AM).</description>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <description>Frequency of the shift (Flexible, One-Time, Weekly, Bi-Weekly, Monthly).</description>
        <label>Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Flexible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One-Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Location_Address__c</fullName>
        <description>The full address of the Organization where the volunteer shift will take place.</description>
        <formula>IF(  Location__c != &quot;&quot;, Location__r.BillingStreet &amp; &quot;, &quot; &amp; Location__r.BillingCity &amp; &quot;, &quot; &amp; Location__r.BillingState &amp; &quot;, &quot; &amp; Location__r.BillingPostalCode, &quot;No Location Set&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The ID of the Organization where the volunteer shift will take place.</description>
        <label>Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Volunteer_Position_Shifts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Logged_Hours__c</fullName>
        <description>Sum of all Volunteer Hours for the shift with Logged status.</description>
        <label>Logged Hours</label>
        <summarizedField>Volunteer_Hours__c.Service_Hours_Completed__c</summarizedField>
        <summaryFilterItems>
            <field>Volunteer_Hours__c.Status__c</field>
            <operation>equals</operation>
            <value>Logged, Confirmed</value>
        </summaryFilterItems>
        <summaryForeignKey>Volunteer_Hours__c.Volunteer_Shift__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Shift_Date__c</fullName>
        <description>The date of the volunteer shift (MM/DD/YYYY) used with one-time shifts.</description>
        <label>Shift Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Day__c</fullName>
        <description>Start date of the volunteer shift (MM/DD/YYYY 12:00 AM) Required for all but &quot;Flexible&quot; frequencies.</description>
        <label>Start Day</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>The date and time the volunteer shift starts (MM/DD/YYYY 12:00 AM).</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Volunteer_Role__c</fullName>
        <description>The ID of the Volunteer Role the shift is for</description>
        <inlineHelpText>The related Volunteer Role</inlineHelpText>
        <label>Volunteer Role</label>
        <referenceTo>Volunteer_Role__c</referenceTo>
        <relationshipLabel>Volunteer Shifts</relationshipLabel>
        <relationshipName>Volunteer_Position_Shifts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Volunteer Shift</label>
    <nameField>
        <displayFormat>VS-{000000}</displayFormat>
        <label>Volunteer Shift Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/classes/CShiftEntry.cls
public with sharing class CShiftEntry {

    public CShiftEntry(ApexPages.StandardController controller) {
        //Volunteer_Position_Shift__c theVPS = new Volunteer_Position_Shift__c();
        List<Volunteer_Shift__c> theVPS = [SELECT Volunteer_Role__c FROM Volunteer_Shift__c WHERE Id = :controller.getId()];
        system.debug('theVPS==='+theVPS);
        if (theVPS.size() > 0)
        { posId = theVPS[0].Volunteer_Role__c; }
        else
        { posId = ApexPages.currentPage().getParameters().get('pid'); }
        wizardState = 1;
        refresh();
    }
    
    private void refresh() {
        thePos = [SELECT Id, Name, Start_Date__c, End_Date__c, (SELECT Logged_Hours__c, Volunteer_Role__c, Start_Day__c, End_Day__c, Start_Time__c, End_Time__c, Location_Address__c, Location__c, Frequency__c, Shift_Date__c, Duration_Hours__c,  Day_of_the_week__c FROM Volunteer_Position_Shifts__r ORDER BY Shift_Date__c DESC) FROM Volunteer_Role__c WHERE Id = :posId ];
        theShifts = new List<ShiftWrapper>();
        for (Volunteer_Shift__c vps : thePos.Volunteer_Position_Shifts__r)
        {
            theShifts.add(new ShiftWrapper(vps));
        }        
        selected = new ShiftWrapper(thePos);
    }

    //public boolean isRO { get; set; }
    //public ApexPages.StandardController stdController { get;set; }
    public String posId { get;set; }
    public Integer wizardState { get; set; }
    public List<ShiftWrapper> theShifts { get; set; }    
    public ShiftWrapper selected { get; set; }
    public Volunteer_Role__c thePos { get; set; }
    public Integer NumOfWeeks { get; set; }

    
    public List<SelectOption> getPickLstValue()    
    {    
        List<SelectOption> options = new List<SelectOption>(); 
        options.add(new SelectOption('', '--None--'));      
        Schema.DescribeFieldResult fieldResult = Volunteer_Shift__c.Frequency__c.getDescribe();    
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();    
        for(Schema.PicklistEntry f : ple)    
        {    
            //if(f.getValue() != 'Flexible')    
            //{    
                options.add(new SelectOption(f.getLabel(), f.getValue()));        
            //}    
        }     
        return options;               
    }
                                    
    public List<SelectOption> getHours() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('1', '1'));        
        options.add(new SelectOption('2', '2'));  
        options.add(new SelectOption('3', '3'));  
        options.add(new SelectOption('4', '4'));  
        options.add(new SelectOption('5', '5'));  
        options.add(new SelectOption('6', '6'));  
        options.add(new SelectOption('7', '7'));  
        options.add(new SelectOption('8', '8'));  
        options.add(new SelectOption('9', '9'));  
        options.add(new SelectOption('10', '10'));  
        options.add(new SelectOption('11', '11'));                                                                                  
        options.add(new SelectOption('12', '12'));                                                                                                                                                                                                                                                                                               
        return options;
    }
    
    public List<SelectOption> getMins() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('00', '00'));        
        options.add(new SelectOption('15', '15'));  
        options.add(new SelectOption('30', '30'));  
        options.add(new SelectOption('45', '45'));                                                                                                                                                                                                                                                                                               
        return options;
    }    

    public List<SelectOption> getMeridiemOffset () {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('AM', 'AM'));        
        options.add(new SelectOption('PM', 'PM'));                                                                                                                                                                                                                                                                                               
        return options;
    }               
    
    public void addShift() {
        if (selected.theShift.Frequency__c != '' && selected.theShift.Frequency__c != null) 
        {
            List<Volunteer_Shift__c> toBeInserted = new List<Volunteer_Shift__c>();
            selected.theShift.Shift_Date__c = selected.theShift.Start_Day__c;
            VolunteerUtil.serializeShiftWrapper(selected);
            selected.theShift.Volunteer_Role__c = thePos.Id;
            toBeInserted.add(selected.theShift);
            if (selected.theShift.Frequency__c == 'Weekly' || selected.theShift.Frequency__c == 'Bi-Weekly' || selected.theShift.Frequency__c == 'Monthly')
            {         
                Volunteer_Shift__c buffShift = selected.theShift.clone(false, true);            
                for (Integer i = 1; i < NumOfWeeks; i++)
                {
                    selected = new ShiftWrapper(thePos);                
                    selected.theShift = buffShift.clone(false, true);
                    if (selected.theShift.Frequency__c == 'Weekly') 
                    { 
                        selected.theShift.Shift_Date__c = buffShift.Shift_Date__c.addDays(i*7);
                        selected.theShift.Start_Day__c = buffShift.Start_Day__c.addDays(i*7);
                        selected.theShift.Start_Time__c = buffShift.Start_Time__c.addDays(i*7);
                        selected.theShift.End_Day__c = buffShift.End_Day__c.addDays(i*7);
                        selected.theShift.End_Time__c = buffShift.End_Time__c.addDays(i*7);                                              
                    }
                    if (selected.theShift.Frequency__c == 'Bi-Weekly')
                    { 
                        selected.theShift.Shift_Date__c = buffShift.Shift_Date__c.addDays(i*14);
                        selected.theShift.Start_Day__c = buffShift.Start_Day__c.addDays(i*14);                        
                        selected.theShift.Start_Time__c = buffShift.Start_Time__c.addDays(i*14);
                        selected.theShift.End_Day__c = buffShift.End_Day__c.addDays(i*14);                        
                        selected.theShift.End_Time__c = buffShift.End_Time__c.addDays(i*14);                                                 
                    }
                    if (selected.theShift.Frequency__c == 'Bi-Weekly')
                    { 
                        selected.theShift.Shift_Date__c = buffShift.Shift_Date__c.addMonths(i);
                        selected.theShift.Start_Day__c = buffShift.Start_Day__c.addMonths(i);                        
                        selected.theShift.Start_Time__c = buffShift.Start_Time__c.addMonths(i);
                        selected.theShift.End_Day__c = buffShift.End_Day__c.addMonths(i);                        
                        selected.theShift.End_Time__c = buffShift.End_Time__c.addMonths(i);                                                 
                    }                    
                    selected.theShift.Volunteer_Role__c = thePos.Id;
                    toBeInserted.add(selected.theShift);
                }
            }
            insert toBeInserted;
            selected = new ShiftWrapper(thePos); 
            
            refresh();
        }
    }
    
    public void removeShift() {
        Integer i = Decimal.valueOf(ApexPages.currentPage().getParameters().get('Index')).intValue();
        delete theShifts.remove(i-1).theShift;
    } 

    public void clear() {
        List<Volunteer_Shift__c> toDelete = new List<Volunteer_Shift__c>();
        for (ShiftWrapper i : theShifts)
        {
            toDelete.add(i.theShift);
        }
        delete toDelete;
        refresh();
    }         

    public void editShift() {
        Integer i = Decimal.valueOf(ApexPages.currentPage().getParameters().get('Index')).intValue();
        wizardState = 2;
        selected = new ShiftWrapper(theShifts.remove(i-1).theShift);
    }    
    
    public void cancelUpdate() {   
        wizardState = 1;
        refresh();            
    }  
        
    public void updateShift() {   
        VolunteerUtil.serializeShiftWrapper(selected);
        update selected.theShift;
        wizardState = 1;
        refresh();            
    }            
    
    public PageReference back() {    
        PageReference pr = new ApexPages.StandardController(thePos).view();
        pr.setRedirect(true);
        return pr;
    }
}