Causeview Package Complete/src/objects/Volunteer_Role__c.object
<CustomObject>
    <description>Used to track and manage the required Volunteer Roles within the Volunteer Opportunities in the Causeview Volunteers application</description>
    <label>Volunteer Role</label>
    <nameField>
        <label>Volunteer Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/objects/Volunteer_Shift__c.object
<CustomObject>
    <description>Outlines the time shifts for each Volunteer Role</description>
    <fields>
        <fullName>End_Day__c</fullName>
        <description>End date of the volunteer shift (MM/DD/YYYY 12:00 AM). Required for all but &quot;Flexible&quot; frequencies.</description>
        <label>End Day</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>The date and time the volunteer shift ends (MM/DD/YYYY 12:00 AM).</description>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Shift_Date__c</fullName>
        <description>The date of the volunteer shift (MM/DD/YYYY) used with one-time shifts.</description>
        <label>Shift Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Day__c</fullName>
        <description>Start date of the volunteer shift (MM/DD/YYYY 12:00 AM) Required for all but &quot;Flexible&quot; frequencies.</description>
        <label>Start Day</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>The date and time the volunteer shift starts (MM/DD/YYYY 12:00 AM).</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Volunteer_Role__c</fullName>
        <description>The ID of the Volunteer Role the shift is for</description>
        <inlineHelpText>The related Volunteer Role</inlineHelpText>
        <label>Volunteer Role</label>
        <referenceTo>Volunteer_Role__c</referenceTo>
        <relationshipLabel>Volunteer Shifts</relationshipLabel>
        <relationshipName>Volunteer_Position_Shifts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Volunteer Shift</label>
    <nameField>
        <displayFormat>VS-{000000}</displayFormat>
        <label>Volunteer Shift Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/src/classes/ShiftWrapper.cls
public class ShiftWrapper {
        public ShiftWrapper(Volunteer_Role__c p) { theShift = new Volunteer_Shift__c (); theShift.Volunteer_Role__c= p.Id; }
        //public ShiftWrapper(Volunteer_Positions__c p, Date sd) { theShift = new Volunteer_Position_Shift__c(); theShift.Volunteer_Position__c = p.Id; startDate = sd; }
        public ShiftWrapper(Volunteer_Shift__c s) 
        { 
            theShift = s; 
            //startDate = theShift.Shift_Date__c; 
            if (theShift.Start_Day__c != null)
            {
                System.debug(theShift);
                startHours = String.valueOf(Math.mod(theShift.Start_Time__c.hour(), 12));
                startMins = String.valueOf(theShift.Start_Time__c.minute());            
                startMeridiemOffset = (theShift.Start_Time__c.hour() > 11 ? 'PM' : 'AM');
            }
            if (theShift.End_Day__c != null)
            {
                endHours = String.valueOf(Math.mod(theShift.End_Time__c.hour(), 12));
                endMins = String.valueOf(theShift.End_Time__c.minute());            
                endMeridiemOffset = (theShift.End_Time__c.hour() > 11 ? 'PM' : 'AM');        
            }
        }        
        public Volunteer_Shift__c theShift { get; set; }
        //public Date startDate { get; set; }
        //public Date startDay { get; set; }
        public String startHours { get; set; } 
        public String startMins { get; set; }
        public String startMeridiemOffset { get; set; }        
        //public Date endDay { get; set; }
        public String endHours { get; set; }
        public String endMins { get; set; }        
        public String endMeridiemOffset { get; set; }     
    }