Causeview Package Complete/ant script/retrieveUnpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>Default organization email address.</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <recordTypes>
        <fullName>Organization</fullName>
        <active>true</active>
        <description>Organization, Corporation, School, Institution, etc.</description>
        <label>Organization</label>
    </recordTypes>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Gift__c.object
<CustomObject>
    <description>Causeview - Any financial transactions including: gifts, product purchases, event registrations, membership renewals, etc.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Rollup of all payments with Status = Approved, Deposited, Refunded</description>
        <inlineHelpText>Sum of all payments with status (Approved, Deposited, Refunded)</inlineHelpText>
        <label>Approved Amount</label>
        <summarizedField>Payment__c.Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Payment__c.Status__c</field>
            <operation>equals</operation>
            <value>Approved, Deposited, Refunded, Invoiced</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Payment__c.Amount__c</field>
            <operation>notEqual</operation>
            <value>0</value>
        </summaryFilterItems>
        <summaryForeignKey>Payment__c.Donation__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Constituent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Individual</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Constituent)</relationshipLabel>
        <relationshipName>Gifts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gift_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gift_Type__c</fullName>
        <label>Gift Type</label>
        <picklist>
            <picklistValues>
                <fullName>One Time Gift</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Recurring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pledge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Sponsorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grant</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Receipt_Type__c</fullName>
        <label>Receipt Type</label>
        <picklist>
            <picklistValues>
                <fullName>Single Receipt</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No Receipt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consolidated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Entered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acknowledged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Payment__c.object
<CustomObject>
    <description>Causeview - Payment records relating to a Transaction.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Constituent__c</fullName>
        <formula>IF(ISBLANK( Donation__r.Organization__c ), HYPERLINK(&quot;/&quot; &amp; Donation__r.Constituent__c, Donation__r.Constituent__r.FirstName &amp; &quot; &quot; &amp; Donation__r.Constituent__r.LastName,&quot;_self&quot;), HYPERLINK(&quot;/&quot; &amp; Donation__r.Organization__c, Donation__r.Organization__r.Name,&quot;_self&quot;))</formula>
        <label>Constituent</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Date of Payment</description>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Donation__c</fullName>
        <label>Transaction</label>
        <referenceTo>Gift__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Recurring_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Refunded__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the payment that refund applies to.</description>
        <inlineHelpText>Lookup to the payment that refund applies to.</inlineHelpText>
        <label>Payment Refunded</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Credit Card</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card - Offline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACH/PAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stock</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Kind</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Receipt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Single or Consolidated Receipt.</description>
        <label>Receipt</label>
        <referenceTo>Receipt__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Committed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refunded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Written Off</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Payment No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <recordTypes>
        <fullName>Refund</fullName>
        <active>true</active>
        <description>Refunded credit card payment - processed via payment gateway</description>
        <label>Refund</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Receipt__c.object
<CustomObject>
    <description>Causeview - Tax receipt for transaction records.</description>
    <fields>
        <fullName>Amount_Receipted__c</fullName>
        <description>Amount of gift that is receipted.</description>
        <inlineHelpText>Populate if you would like to provide a specific dollar amount.  This will override all other calculations and set the Receipt Amount to your input.</inlineHelpText>
        <label>Custom Receipt Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Constituent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Captures the constituent ID for email receipting purposes.  Hidden to end users.</description>
        <label>Constituent</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gift_Type__c</fullName>
        <description>Type of gift received</description>
        <formula>TEXT(Gift__r.Gift_Type__c)</formula>
        <inlineHelpText>Type of gift received</inlineHelpText>
        <label>Gift Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Organization that receipt is issued to</description>
        <inlineHelpText>Organization that receipt is issued to</inlineHelpText>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Receipt_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>Date of receipt.</description>
        <label>Receipt Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Receipt_Email_Address__c</fullName>
        <description>Address receipt was emailed to.</description>
        <label>Receipt Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Receipt_Type__c</fullName>
        <description>Defines the type of receipt either single or consolidated.</description>
        <inlineHelpText>Single: receipt is linked to a single payment
Consolidated: receipt is linked to multiple payments</inlineHelpText>
        <label>Receipt Type</label>
        <picklist>
            <picklistValues>
                <fullName>Single</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Consolidated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Issued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To be Issued</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Void</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Receipt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <recordTypes>
        <fullName>Void</fullName>
        <active>true</active>
        <description>Void receipt</description>
        <label>Void</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>Payment_Filter__c</fullName>
        <description>To save last selected payment filter in the Consolidated Receipt view.</description>
        <label>Payment Filter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/classes/consolidatedReceiptController.cls
//Users will be presented with an interface which displays all unreceipted Payments belonging to the donor.
//The user can select All or individual Payments to consolidate into the receipt.
//A new receipt record will be created, grouping all Payments (transactions) selected and Link each Payment to the master receipt record, on click of the create button.
//The user is able to filter the Payment records via a picklist of filters (This Year, Last Year, All).
    //The picklist defaults to what the user last selected.
//From the receipt record, the user can click a button to print consolidated receipt which generates an email and  PDF receipt.
    //The PDF receipt will include a list of all donation included in the consolidated receipt.

public class consolidatedReceiptController{

    public Boolean containsPayment{get;set;}
    public List<paymentWrapper> payments{get;set;}
    public Receipt__c receipt{get;set;}
    public String selectedPaymentFilter{get;set;}

    private List<Payment__c> selectedPayments;
    @TestVisible
    private List<Payment__c> allPayments;
    private String cid;
    private User currentUser;


    public consolidatedReceiptController(ApexPages.StandardController controller) {
        cid = System.currentPagereference().getParameters().get('cid');
        payments = new List<paymentWrapper>();
        selectedPayments = new List<Payment__c>();
        containsPayment = true;

        try{
                //Get all the payments belonging to the given Organization/Individual, having Receipt__c as "null",
                //    Record Type not as "Refund", status as "Approved", with Transactions not having Receipt Type as "No Receipt", and Approved Payments with no Refund linked to it.
            RecordType RT = [SELECT Id FROM RecordType Where SobjectType = 'cv_pkg_dev_I__Payment__c' AND Name = 'Refund' AND NamespacePrefix = 'causeview' LIMIT 1];
            allPayments = [Select Id, Name, Date__c, Amount__c, Payment_Type__c, Status__c,
                            Donation__r.Name, Donation__r.Gift_Type__c, Donation__r.Gift_Date__c,
                            Donation__r.Constituent__c, Donation__r.Organization__c, Donation__r.Receipt_Type__c, Receipt__c,
                            (Select Id From Payments__r)
                            From Payment__c
                            Where (
                                Donation__r.Constituent__c = :cid OR
                                Donation__r.Organization__c = :cid
                            ) AND
                            Receipt__c = null AND
                            RecordTypeId != :RT.Id AND
                            Status__c = 'Approved' AND
                            Donation__r.Receipt_Type__c != 'No Receipt' AND
                            Payment_Refunded__c = null LIMIT 1000];
    
            //If no payments, display Info.
            if(allPayments == null || allPayments.Size() < 1) {
                containsPayment = false;
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'There are no unreceipted Payments belonging to the donor.'));
            } else {

                //Filter out Refunded Payments
                for(Integer i = 0; i < allPayments.size(); i++) {
                    if(allPayments[i].Payments__r.size() > 0) {
                        allPayments.remove(i);
                    }
                }
    
                createNewReceipt();
    
                //Get the user last selected filter value.
                currentUser = [Select Id, Payment_Filter__c From User Where Id = :UserInfo.getUserId()];
                selectedPaymentFilter = 'This Year';
                if(currentUser.Payment_Filter__c != null) {
                    selectedPaymentFilter = currentUser.Payment_Filter__c;
                }
                applyPaymentFilter();    
            }
        } catch(Exception ex) {
            ApexPages.addMessages(ex);
        }
    }

    @TestVisible
    //Create a new Receipt record and populate default fields.
    private void createNewReceipt() {
        receipt = new Receipt__c();

        try {
            //Populate Receipt_Email_Address__c based on the donor type.
            if(allPayments[0].Donation__r.Constituent__c == null) {
                receipt.Receipt_Email_Address__c = [Select Email__c From Account Where Id = :cid].Email__c;
            } else {
                receipt.Receipt_Email_Address__c = [Select Email From Contact Where Id = :cid].Email;
            }
    
            receipt.Constituent__c = allPayments[0].Donation__r.Constituent__c;
            receipt.Organization__c = allPayments[0].Donation__r.Organization__c;
            receipt.Receipt_Date__c = System.Today();
            receipt.Receipt_Type__c = 'Consolidated';
        } catch(Exception ex) {
            ApexPages.addMessages(ex);
        }
    }

    //Create Payment Filter options.
    public List<SelectOption> getPaymentFilters() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('This Year','This Year'));
        options.add(new SelectOption('Last Year','Last Year'));
        options.add(new SelectOption('All','All'));

        return options;
    }

    //Attach recent Transaction(Among the selected Payments) to the Receipt record.
    public List<SelectOption> getTransactionsToAttach() {
        List<SelectOption> options = new List<SelectOption>();
        Integer index = 0;
        Integer recentIndex = 0;
        Date recent;
        for(paymentWrapper PW : payments) {
            if(PW.selected) {
                if(recent == null || recent < PW.payment.Donation__r.Gift_Date__c) {
                    recent = PW.payment.Donation__r.Gift_Date__c;
                    recentIndex = index;
                }
                options.add(new SelectOption(PW.payment.Donation__c, PW.payment.Donation__r.Name));
                index++;
            }
        }

        if(recentIndex != 0) {
            SelectOption opt = options.remove(recentIndex);
            options.add(0, opt);
        }
        return options;

    }

    //Filter records based on payment filter
    public pageReference applyPaymentFilter() {
        Boolean isAll = false;
        Integer cond = System.Today().year();
        if(selectedPaymentFilter == 'All') {
            isAll = true;
        } else if(selectedPaymentFilter == 'Last Year') {
            cond = cond - 1;
        }

        payments.clear();

        for(Payment__c P : allPayments) {
            if( isAll || (P.Date__c).year() == cond ) {
                payments.add(new paymentWrapper(P));
            }
        }

        return null;
    }

    //Wrapper class for payment to store the payments that are selected.
    public class paymentWrapper {
        public Payment__c payment{get;set;}
        public boolean selected{get;set;}
        public paymentWrapper(Payment__c p) {
            payment = p;
            selected = false;
        }
    }

    public pageReference cancel() {
        return new pageReference('/' + cid);
    }

    //Insert the Receipt record with all the field values and update the payment records.
    public pageReference generateReceipt() {

        Boolean isEmpty = true;
        //If no Payments are selected
        for(paymentWrapper PW : payments) {
            if(PW.selected) {
                isEmpty = false;
            }
        }

        //If no payments are selected display Warning message.
        if(isEmpty) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.WARNING, 'Please select a Payment to generate Receipt'));
            return null;
        }

        try {
            //Update User record with the selected payment filter.
            currentUser.Payment_Filter__c = selectedPaymentFilter;
            Update currentUser;

            Insert receipt;
    
            receipt.Amount_Receipted__c = 0;
            //Update Selected Payment records with the Receipt id, and Amount_Receipted__c field with the sum of all the payment amounts.
            for(paymentWrapper PW : payments) {
                if(PW.selected) {
                    PW.payment.Receipt__c = receipt.Id;
                    selectedPayments.add(PW.payment);
                    receipt.Amount_Receipted__c = receipt.Amount_Receipted__c + PW.payment.Amount__c;
                }
            }
            
             
            
            //Update receipt record and related payment records.
            Update receipt;
            Update selectedPayments;
    

        } catch(Exception ex) {
            ApexPages.addMessages(ex);
            containsPayment = false;
            return null;
        }

        pageReference page = new pageReference('/' + receipt.id);
        return page;
    }

}