Causeview Package Complete/ant script/retrieveUnpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>Default organization email address.</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Gift__c.object
<CustomObject>
    <description>Causeview - Any financial transactions including: gifts, product purchases, event registrations, membership renewals, etc.</description>
    <fields>
        <fullName>Constituent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Individual</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Constituent)</relationshipLabel>
        <relationshipName>Gifts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gift_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gift_Type__c</fullName>
        <label>Gift Type</label>
        <picklist>
            <picklistValues>
                <fullName>One Time Gift</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Recurring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pledge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Sponsorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grant</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Receipt_Type__c</fullName>
        <label>Receipt Type</label>
        <picklist>
            <picklistValues>
                <fullName>Single Receipt</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No Receipt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consolidated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Recurring_Donation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recurring Gift</label>
        <referenceTo>Recurring_Donation__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Entered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acknowledged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Gift_Detail__c.object
<CustomObject>
    <description>Causeview - Manages the allocation of your gifts across Funds, Appeals, Tributes, Products and Campaigns.</description>
    <fields>
        <fullName>Constituent__c</fullName>
        <formula>IF(ISBLANK( Gift__r.Organization__c ), HYPERLINK(&quot;/&quot; &amp; Gift__r.Constituent__c, Gift__r.Constituent__r.FirstName &amp; &quot; &quot; &amp; Gift__r.Constituent__r.LastName,&quot;_self&quot;), HYPERLINK(&quot;/&quot; &amp; Gift__r.Organization__c, Gift__r.Organization__r.Name,&quot;_self&quot;))</formula>
        <label>Constituent</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gift_Type__c</fullName>
        <formula>TEXT( Gift__r.Gift_Type__c )</formula>
        <label>Gift Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gift__c</fullName>
        <label>Transaction</label>
        <referenceTo>Gift__c</referenceTo>
        <relationshipLabel>Allocations</relationshipLabel>
        <relationshipName>Gift_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <description>Deprecated field - combined into Constituent field</description>
        <formula>HYPERLINK(&quot;/&quot; &amp; Gift__r.Organization__c, Gift__r.Organization__r.Name,&quot;_self&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organization</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Payment associated to the allocation record.</description>
        <inlineHelpText>Payment associated to the allocation record.</inlineHelpText>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Gift Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Allocation</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Allocation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Payment__c.object
<CustomObject>
    <description>Causeview - Payment records relating to a Transaction.</description>
    <fields>
        <fullName>Constituent__c</fullName>
        <formula>IF(ISBLANK( Donation__r.Organization__c ), HYPERLINK(&quot;/&quot; &amp; Donation__r.Constituent__c, Donation__r.Constituent__r.FirstName &amp; &quot; &quot; &amp; Donation__r.Constituent__r.LastName,&quot;_self&quot;), HYPERLINK(&quot;/&quot; &amp; Donation__r.Organization__c, Donation__r.Organization__r.Name,&quot;_self&quot;))</formula>
        <label>Constituent</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Receipt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Single or Consolidated Receipt.</description>
        <label>Receipt</label>
        <referenceTo>Receipt__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Committed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refunded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Written Off</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Payment No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Standard payment record - all non credit card payments</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Receipt__c.object
<CustomObject>
    <description>Causeview - Tax receipt for transaction records.</description>
    <fields>
        <fullName>Constituent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Captures the constituent ID for email receipting purposes.  Hidden to end users.</description>
        <label>Constituent</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gift_Type__c</fullName>
        <description>Type of gift received</description>
        <formula>TEXT(Gift__r.Gift_Type__c)</formula>
        <inlineHelpText>Type of gift received</inlineHelpText>
        <label>Gift Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gift__c</fullName>
        <label>Gift</label>
        <referenceTo>Gift__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Organization that receipt is issued to</description>
        <inlineHelpText>Organization that receipt is issued to</inlineHelpText>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Receipt_Type__c</fullName>
        <description>Defines the type of receipt either single or consolidated.</description>
        <inlineHelpText>Single: receipt is linked to a single payment
Consolidated: receipt is linked to multiple payments</inlineHelpText>
        <label>Receipt Type</label>
        <picklist>
            <picklistValues>
                <fullName>Single</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Consolidated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Issued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To be Issued</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Void</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Receipt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <recordTypes>
        <fullName>Issued</fullName>
        <active>true</active>
        <description>Read-only receipt record.</description>
        <label>Issued</label>
    </recordTypes>
    <recordTypes>
        <fullName>Void</fullName>
        <active>true</active>
        <description>Void receipt</description>
        <label>Void</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Recurring_Donation__c.object
<CustomObject>
    <description>Causeview - Captures recurring gifts</description>
    <fields>
        <fullName>Constituent__c</fullName>
        <label>Constituent</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recurring Gifts</relationshipLabel>
        <relationshipName>Recurring_Donations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Organization related to the recurring transaction.</description>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Recurring_Donations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Recurring Gift</label>
    <nameField>
        <displayFormat>RD-{00000}</displayFormat>
        <label>Recurring Gift No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Gifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Solicitor__c.object
<CustomObject>
    <description>Causeview - Captures credit given to individuals that participated in the solicitation of a gift.</description>
    <fields>
        <fullName>Gift_Date__c</fullName>
        <formula>Gift__r.Gift_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The date we expect to receive payment</inlineHelpText>
        <label>Gift Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gift__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Gift that soft credit is related to.</description>
        <label>Gift</label>
        <referenceTo>Gift__c</referenceTo>
        <relationshipLabel>Soft Credits</relationshipLabel>
        <relationshipName>Soft_Credits</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Solicitor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Individual involved in soliciting gift</description>
        <label>Individual Solicitor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Soft Credits</relationshipLabel>
        <relationshipName>Additional_Solicitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Soft Credit</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Soft Credit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Soft Credits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/classes/NewCVEventRegistrationController.cls
public class NewCVEventRegistrationController {   
    // ** Standard Objects  ** //
  
    public Gift__c theGift { get; set; }
    public Payment__c thePayment { get; set; }
    public Receipt__c theReceipt { get; set; }
    public Recurring_Donation__c theRecurring { get; set; }
    
    public List<Gift_Detail__c> theGiftDetails { get; set; }
    public List<Solicitor__c> softCredits { get; set; }    
    public Contact theIndividual { get; set; }
    public Account theOrg { get; set; }    
    public boolean isOrg { get; set; }
    private string authToken { get; set; }
    
    public string payment_structure { get; set; }    
    public string default_payment_status { get; set; }    
    public string per_payment_amount { get; set; }        
    public string ccExpM { get; set; }
    public string ccExpY { get; set; }    
    public string ccCVV { get; set; }
    public boolean shouldSubmit { get; set; }
    public boolean shouldInsertReceipt { get; set; }
    
    public static string TestContactId { get; set; }
    //** API  **//
    //private Causeview_REST_API api { get; set; }
    //public Actionpage batch_form { get; set; }
    
    /** Used for Fund Lookup Override **/
    public string FundKeyPrefix { get; set; }
    
    //used for credit card number
    String ccNumber; 
    
    /** Dynamic Fieldsets **/
    public List<Schema.FieldSetMember> PaymentFieldList {get; set;}
    public List<Schema.FieldSetMember> AllocationFieldList {get; set;}  
    
    //added by nitin
    public Boolean multiCurrenyEnable{get;set;}
    public string selectedCurrencyCode{get;set;} 
    public Boolean pledgeInstallmentEnable {get;set;}
    public Integer fixedNumberInstallment {get;set;}
    public List<cv_pkg_dev_I__Installment__c> theInstallments {get; set;}
    
    //added by shridhar....
    public list<campaign> theEvent { get; set; }
    public cv_pkg_dev_I__Event_Level__c theEventLevel { get; set; }
    public list<cv_pkg_dev_I__Event_Level__c> theEventLevelsList { get; set; }
    public string evenName{get;set;}
    public list<eventLevelsWrapperClass> eventLevelsWrappers{get;set;}
    public decimal totalAmount{get;set;}
    //till here
    
    public void setAllocationFieldList() {
        AllocationFieldList = new List<Schema.FieldSetMember>();
        List<Schema.FieldSetMember> afl = SObjectType.cv_pkg_dev_I__Gift_Detail__c.FieldSets.cv_pkg_dev_I__allocation.getFields();
        
        
        for(Schema.FieldSetMember f : afl) {            
            AllocationFieldList.add(f);
        }  
        
    }
    
    public void setPaymentFieldList() {
        PaymentFieldList = new List<Schema.FieldSetMember>();
        List<Schema.FieldSetMember> pfl = SObjectType.cv_pkg_dev_I__Payment__c.FieldSets.cv_pkg_dev_I__Single_Transation_Custom_Fields.getFields();
        for(Schema.FieldSetMember f : pfl) {            
            PaymentFieldList.add(f);
        }
    }
    
    public NewCVEventRegistrationController(ApexPages.StandardController controller) {
        /** Setting Fieldsets in Constructor **/
        Schema.DescribeSObjectResult fund = cv_pkg_dev_I__Fund__c.sObjectType.getDescribe();
        FundKeyPrefix = fund.getKeyPrefix();    
        setAllocationFieldList();
        setPaymentFieldList();
        
        /** Initialization **/
        theGift = new Gift__c();
        
        string cId = System.currentPagereference().getParameters().get('cid');
        if (cId == null) cId = TestContactId;
        InitializeContact(cId);
        //added by nitin
        cv_pkg_dev_I__App_Settings__c appSetting = cv_pkg_dev_I__App_Settings__c.getInstance();
        
        shouldInsertReceipt = false;
        
        multiCurrenyEnable = checkMCEnabled();
    	//added by shridhar
        
       theEventLevel = new cv_pkg_dev_I__Event_Level__c();
        theEventLevelsList=new list<cv_pkg_dev_I__Event_Level__c>();

    }
    
    public void InitializeContact(string contactId)
    {
        system.debug('<==Inside InitializeContact==>');
        shouldSubmit = false;
        
        isOrg = contactId.startsWith('001');
        
        if (isOrg) {
            List<Account> contacts = [SELECT BillingStreet, Email__c, BillingCity, BillingPostalCode,Phone, BillingState, BillingCountry, Name, Id FROM Account WHERE Id = :contactId];
            if (contacts==null || contacts.size()<=0) return; 
            
            theOrg = contacts[0];        
        }
        else {
            List<Contact> contacts = [SELECT Name, FirstName, LastName, Email, Id, MailingStreet, MailingCity, MailingPostalCode, MailingState, MailingCountry FROM Contact WHERE Id = :contactId];
            if (contacts==null || contacts.size()<=0) return; 
            
            theIndividual = contacts[0];
        }
        
        if (!isOrg) {
            theGift.Constituent__c = theIndividual.Id;
        }
        else {
            theGift.Organization__c = theOrg.Id;        
        }
        theGift.Gift_Type__c = 'One Time Gift';    
        theGift.Gift_Date__c = Date.Today();          
        theGift.Status__c = 'Entered';
        theGift.Receipt_Type__c = 'Single Receipt';            
        
        thePayment = new Payment__c();
        thePayment.Payment_Type__c = '';
        thePayment.Status__c = 'Approved';
        
        theGiftDetails = new List<Gift_Detail__c>();     
        
        if (!isOrg) {
            theReceipt = new Receipt__c(Receipt_Date__c = Date.Today(), Status__c = 'To Be Issued', Constituent__c = theIndividual.Id);
        }
        else {
            theReceipt = new Receipt__c(Receipt_Date__c = Date.Today(), Status__c = 'To Be Issued', Organization__c  = theOrg.Id);
        }        
        
        
        
        
    }       
    
    
    
    public PageReference Submit() {
        return null;
    }    
    
    public PageReference GoBack() {
        system.debug('<==Inside GoBack==>');
        if(!isOrg) {
            PageReference pr = new ApexPages.StandardController(theIndividual).view();
            pr.setRedirect(true);
            return pr;
        }
        PageReference pr = new ApexPages.StandardController(theOrg).view();
        pr.setRedirect(true);
        return pr;
    }
    
    
    
    //vg edit 
    
    public integer tryParseToInt(String txt)
    {
        integer result = 0;
        try {
            result = integer.valueOf(txt);
        }
        catch(Exception ex) {
            //do nothing
        }
        
        return result;
    }
    
    //** Used to feed Javascript to Dynamicly populate fund when an Appeal is selected ** //  
    public class BatchAllocationSetting {
        public string LetterId { get; set; }
        public string LetterName { get; set; }
        
        public string FundId { get; set; }
        public string FundName { get; set; }
        
        
        
        public BatchAllocationSetting() { }
        public BatchAllocationSetting(string l, string f)
        {
            LetterId = l;
            FundId = f;
            
        }
    }
    
    public List<SelectOption> getMonths() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('1', 'Jan'));        
        options.add(new SelectOption('2', 'Feb'));  
        options.add(new SelectOption('3', 'Mar'));  
        options.add(new SelectOption('4', 'Apr'));  
        options.add(new SelectOption('5', 'May'));  
        options.add(new SelectOption('6', 'Jun'));  
        options.add(new SelectOption('7', 'Jul'));  
        options.add(new SelectOption('8', 'Aug'));  
        options.add(new SelectOption('9', 'Sept'));  
        options.add(new SelectOption('10', 'Oct'));  
        options.add(new SelectOption('11', 'Nov'));                                                                                  
        options.add(new SelectOption('12', 'Dec'));                                                                                                                                                                                                                                                                                               
        return options;
    }
    
    public List<SelectOption> getYears() {
        List<SelectOption> options = new List<SelectOption>();
        for (Integer i = 0; i < 10; i++)
        {
            options.add(new SelectOption(String.valueOf(Date.Today().Year()+i), String.valueOf(Date.Today().Year()+i)));     
        }                                                                                                                                                                                                                                                                                            
        return options;
    }    
    
    
    
    //added by nitin to check exsiting org has currency enabled or not
    public Boolean checkMCEnabled(){
        Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();
        Schema.SObjectType mcEnabled = gd.get('CurrencyType');
        system.debug('Nitin mcEnabled=='+mcEnabled);
        return (mcEnabled != null) ? true : false;
    }
    //To get list of enabled currencies in org
    
    //Extended
     public PageReference eventLevels() {
         system.debug('----level-'+evenName );
         eventLevelsWrappers =new list<eventLevelsWrapperClass>();
         theEventLevelsList = [select id, Name, Level_Price__c  from cv_pkg_dev_I__Event_Level__c where cv_pkg_dev_I__Event__c=: evenName ];
         for(cv_pkg_dev_I__Event_Level__c eventLevelTemp :  theEventLevelsList){
            eventLevelsWrappers.add(new eventLevelsWrapperClass(eventLevelTemp)); 
         }
        return null;
    }
    
    public class eventLevelsWrapperClass{
        public string Quantity{get;set;}
         public cv_pkg_dev_I__Event_Level__c eventLevel{get;set;}
        
        public eventLevelsWrapperClass(cv_pkg_dev_I__Event_Level__c EL){
            eventLevel=EL;
            Quantity='';
        }
        
        
    }
    
}