Causeview Package Complete/ant script/retrieveUnpackaged/objects/aNums__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Causeview auto number format for constituent IDs</description>
    <fields>
        <fullName>ContactCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ContactCount(DEP)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ContactLength__c</fullName>
        <defaultValue>8</defaultValue>
        <label>ContactLength</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ContactPrefix__c</fullName>
        <defaultValue>TEXT(1)</defaultValue>
        <label>ContactPrefix</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>OrgCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OrgLength__c</fullName>
        <defaultValue>8</defaultValue>
        <label>OrgLength</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OrgPrefix__c</fullName>
        <defaultValue>TEXT(1)</defaultValue>
        <label>OrgPrefix</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Auto Number Counts</label>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/classes/Test_DM.cls
@isTest
private class Test_DM {
	//Test GITHUB
    static testMethod void Test_GiftRollup() {
        Test.startTest();
        aNums__c a = new aNums__c(Name = 'Default', ContactCount__c = 8, ContactLength__c = 8, ContactPrefix__c = 'Con-', OrgCount__c = 8, OrgLength__c = 8, OrgPrefix__c = 'Con-');
        insert a;
        
        Account acc = new Account(Name = 'sss');
        insert acc;
        
        cv_pkg_dev_I__BatchSettings__c cs2 = new cv_pkg_dev_I__BatchSettings__c( Name = 'Default', cv_pkg_dev_I__BatchFormID__c = 'sadas',   cv_pkg_dev_I__BatchReportId__c = 'asdasd', cv_pkg_dev_I__RegularGiftRecordTypeId__c = 'test', cv_pkg_dev_I__BucketAccountId__c = acc.Id,    cv_pkg_dev_I__CurrencyCode__c = 'CAD', cv_pkg_dev_I__GatewayUrl__c = 'asdasd');        
        insert cs2;
                
        Contact c = new Contact(LastName = 'Contact');
        insert c;
        //Database.executeBatch(new DMContactRollups(), 5); 
        Test.stopTest();
    }
}