Causeview Package Complete/ant script/retrieveUnpackaged/objects/App_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Causeview settings specific to each customer such as recordtype Ids</description>
    <fields>
        <fullName>CV_Auth_Token__c</fullName>
        <description>Token is used in conjunction withActionengine REST API integration.</description>
        <inlineHelpText>Token is used in conjunction withActionengine REST API integration.</inlineHelpText>
        <label>Causeview Authorization Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Causeview_REST_API_URL__c</fullName>
        <defaultValue>&quot;https://api.causeview.com/v2.1/services/rest&quot;</defaultValue>
        <description>URL of Actionengine REST API.</description>
        <inlineHelpText>URL of Actionengine REST API.</inlineHelpText>
        <label>Causeview REST API URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Causeview App Settings</label>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/classes/Causeview_REST_API.cls
public class Causeview_REST_API 
{
    private string token;
    private string api_url;
    
    public Causeview_REST_API() {
        App_Settings__c settings = App_Settings__c.getInstance();
        if (settings != null) {
            token = settings.CV_Auth_Token__c;
            api_url = settings.Causeview_REST_API_URL__c;
        }
    }
    
    public Actionpage GetActionpage(string form_id) {
        Actionpage retVal = new Actionpage();
        string results = HttpGet(api_url + '/Form/' + form_id);  
        System.debug(results);
        if (results != '') { retVal = (Actionpage)JSON.deserialize(results, Actionpage.class); }
        return retVal;
    }        
    
    private string HttpGet(string url) {
        Http h = new Http();    
        HttpRequest req = new HttpRequest();
        req.setEndpoint(url);
        req.setMethod('GET');       
        req.setHeader('Authorization', 'Bearer ' + token);
        req.setHeader('Content-Type', 'application/json; charset=UTF-8');
        req.setHeader('Accept', 'application/json');
        
        if (!Test.isRunningTest()) { 
            HttpResponse res = h.send(req);    
            if (res.getStatusCode() >= 200 && res.getStatusCode() <= 299) {
                if (res.getBody() == '') return 'OK';
                return res.getBody();                   
            }
        }
        return '';        
    }
    
/*    private string HttpPost(string url, string body) {
        Http h = new Http();        
        HttpRequest req = new HttpRequest();
        req.setEndpoint(url);
        req.setMethod('POST');
        req.setBody(body);
        System.debug(body);
        req.setHeader('Authorization Bearer', token);
        req.setHeader('Content-Type', 'application/json; charset=UTF-8');
        req.setHeader('Accept', 'application/json');
        req.setHeader('Content-Length', String.valueOf(body.length()));
        
        if (!Test.isRunningTest()) { 
            HttpResponse res = h.send(req);     
            if (res.getStatusCode() >= 200 && res.getStatusCode() <= 299) {
                system.debug(res.getBody());
                if (res.getBody() == '') return 'OK';
                return res.getBody();                   
            }
        }
        return '';
    }

    private string HttpPut(string url, string body) {
        Http h = new Http();        
        HttpRequest req = new HttpRequest();
        req.setEndpoint(url);
        req.setMethod('PUT');
        req.setBody(body);
        System.debug(body);
        req.setHeader('Authorization Bearer', token);
        req.setHeader('Content-Type', 'application/json; charset=UTF-8');
        req.setHeader('Accept', 'application/json');
        
        if (!Test.isRunningTest()) { 
            HttpResponse res = h.send(req);     
            if (res.getStatusCode() >= 200 && res.getStatusCode() <= 299) {
                system.debug(res.getBody());
                if (res.getBody() == '') return 'OK';
                return res.getBody();                   
            }
        }
        return '';
    }
*/
}