Causeview Package Complete/ant script/retrieveUnpackaged/objects/BatchSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Causeview batch processing settings.</description>
    <fields>
        <fullName>Unknown_Guest_Id__c</fullName>
        <defaultValue>&quot;NA&quot;</defaultValue>
        <description>Record Id of Unknown Guest contact record.  Used with event registrations.  This field is deprecated post Causeview v1.936.</description>
        <inlineHelpText>Record Id of Unknown Guest contact record.  Used with event registrations.  This field is deprecated post Causeview v1.936.</inlineHelpText>
        <label>(deprecated) Unknown Guest Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Batch Settings</label>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Campaign.object
<CustomObject>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>A gathering of constituents for the purpose of fundraising or support</description>
        <label>Event</label>
    </recordTypes>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Date_of_Last_Event_Attended__c</fullName>
        <inlineHelpText>The Date of the last event this individual has attended.</inlineHelpText>
        <label>Date of Last Event Attended</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Attended__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Flagged if the individual has been to an Event.</inlineHelpText>
        <label>Event Attendee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name_of_Last_Event_Attended__c</fullName>
        <inlineHelpText>The Name of the last event this individual has attended.</inlineHelpText>
        <label>Name of Last Event Attended</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Event__c.object
<CustomObject>
    <description>Causeview - No longer required.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending for Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Donation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Donation Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>(DEPRECATED)</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Event No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(DEPRECATED)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Event_Registration__c.object
<CustomObject>
    <description>Causeview - Registrations links individuals to events and to a transaction.</description>
    <fields>
        <fullName>Event__c</fullName>
        <description>Event associated to the event registration</description>
        <label>Event</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Event_Registrations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Individual__c</fullName>
        <description>Individual related to event registration</description>
        <label>Registrant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Event Registrations</relationshipLabel>
        <relationshipName>Event_Registrations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Parent_Registration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the primary guest registration.  A method to link all related free event registration together.</description>
        <inlineHelpText>Parent Event Registration; this generally belongs to the primary guest.</inlineHelpText>
        <label>Parent Registration</label>
        <referenceTo>Event_Registration__c</referenceTo>
        <relationshipLabel>Guest Registrations</relationshipLabel>
        <relationshipName>Event_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Registration_Date__c</fullName>
        <description>Date of registration</description>
        <label>Registration Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Swapped Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Transaction associated to the event registration.  Applicable to events with paid fee.</description>
        <label>Transaction</label>
        <referenceTo>Gift__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Event_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>ER-{0000000}</displayFormat>
        <label>Registration No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Gift__c.object
<CustomObject>
    <description>Causeview - Any financial transactions including: gifts, product purchases, event registrations, membership renewals, etc.</description>
    <fields>
        <fullName>Attendee_Names_Received__c</fullName>
        <description>Number of attendee names received</description>
        <inlineHelpText>Number of attendee names received</inlineHelpText>
        <label>Attendee Names Received</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event (dep)</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Entered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acknowledged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/classes/EventRegistrationTrigger.cls
public class EventRegistrationTrigger{
    
    @future
    public static void RollupNamesReceivedTrigger(Set<String> ContactIDs){
        
        List<Contact> Contacts = [SELECT Id, Date_of_Last_Event_Attended__c, Event_Attended__c, Name_of_Last_Event_Attended__c, (SELECT Registration_Date__c, Event__r.Name,Event__r.StartDate FROM Event_Registrations__r WHERE Status__c = 'Attended' ORDER BY Registration_Date__c DESC) FROM Contact WHERE Id IN :ContactIDs FOR UPDATE];
    
        for (Contact c : Contacts)
        {
            c.Event_Attended__c = False;
            c.Date_of_Last_Event_Attended__c = null;
            c.Name_of_Last_Event_Attended__c = '';
            
            if (c.Event_Registrations__r.size() != 0)
            {
                c.Event_Attended__c = True;
               // c.Date_of_Last_Event_Attended__c = c.Event_Registrations__r[0].Registration_Date__c;
               // Date of Last Event Attended Not Calculating Correctly--https://www.pivotaltracker.com/story/show/99610876
               c.Date_of_Last_Event_Attended__c = c.Event_Registrations__r[0].Event__r.StartDate;
                c.Name_of_Last_Event_Attended__c = c.Event_Registrations__r[0].Event__r.Name;                
            }
        }
        
        update Contacts;
    }
    
    @future
    public static void RollupNamesReceivedTrigger(Set<Id> transIds){
        BatchSettings__c settings = BatchSettings__c.getInstance('Default');
        String guestId = settings.Unknown_Guest_Id__c;
        List<Gift__c> trans = [SELECT Id, Attendee_Names_Received__c, (SELECT Id FROM Event_Registrations__r WHERE Individual__c != :guestId ) FROM Gift__c WHERE Id IN :transIds FOR UPDATE];
           
        List<Gift__c> updateGift = new List<Gift__c>();
        
        
       if(trans.size() > 0)
        {
         for (Gift__c g : trans) {
             if(g.Attendee_Names_Received__c != g.Event_Registrations__r.size())
               {
                g.Attendee_Names_Received__c = g.Event_Registrations__r.size();
                updateGift.add(g); 
              }   
        }
        if(updateGift.size() > 0)
            update updateGift;
        }
    }
    
}