Causeview Package Complete/ant script/retrieveUnpackaged/objects/Benefit__c.object
<CustomObject>
    <description>Captures benefits related to event levels and membership levels</description>
    <label>Benefit</label>
    <nameField>
        <label>Benefit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Event_Level__c.object
<CustomObject>
    <description>Causeview - event ticket and sponsorship levels</description>
    <label>Event Level</label>
    <nameField>
        <label>Event Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Event_Level_Benefit__c.object
<CustomObject>
    <description>Causeview - benefits related to specific Event Level</description>
    <fields>
        <fullName>Benefit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Benefit included with Event Level</description>
        <inlineHelpText>Benefit included with Event Level</inlineHelpText>
        <label>Benefit</label>
        <referenceTo>Benefit__c</referenceTo>
        <relationshipLabel>Event Levels</relationshipLabel>
        <relationshipName>Event_Level_Benefits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Level__c</fullName>
        <description>Event Level the benefit is applied to</description>
        <label>Event Level</label>
        <referenceTo>Event_Level__c</referenceTo>
        <relationshipName>Benefits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Quantity of benefit</description>
        <label>Quantity</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Event Level Benefit</label>
    <nameField>
        <displayFormat>ELB-{000000}</displayFormat>
        <label>Benefits No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Level Benefits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Gift__c.object
<CustomObject>
    <description>Causeview - Any financial transactions including: gifts, product purchases, event registrations, membership renewals, etc.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Gift_Detail__c.object
<CustomObject>
    <description>Causeview - Manages the allocation of your gifts across Funds, Appeals, Tributes, Products and Campaigns.</description>
    <fields>
        <fullName>Event_Level__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Event level purchased as part of Transaction</description>
        <label>Event Level</label>
        <referenceTo>Event_Level__c</referenceTo>
        <relationshipLabel>Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gift__c</fullName>
        <label>Transaction</label>
        <referenceTo>Gift__c</referenceTo>
        <relationshipLabel>Allocations</relationshipLabel>
        <relationshipName>Gift_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>The quantity of this that was purchased</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Allocation</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Allocation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Transaction_Benefit__c.object
<CustomObject>
    <description>Causeview - captures all benefits included with Transaction</description>
    <fields>
        <fullName>Allocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Allocation record that includes the Event Level Benefit.</description>
        <inlineHelpText>Lookup to the Allocation record that includes the Event Level Benefit.</inlineHelpText>
        <label>Allocation</label>
        <referenceTo>Gift_Detail__c</referenceTo>
        <relationshipLabel>Transaction Benefits</relationshipLabel>
        <relationshipName>Transaction_Benefits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Benefit_Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Quantity of benefit received</description>
        <label>Benefit Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Benefit__c</fullName>
        <description>Included benefit</description>
        <label>Benefit</label>
        <referenceTo>Benefit__c</referenceTo>
        <relationshipLabel>Transaction Benefits</relationshipLabel>
        <relationshipName>Transaction_Benefits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <description>Transaction linked to event level</description>
        <label>Transaction</label>
        <referenceTo>Gift__c</referenceTo>
        <relationshipLabel>Transaction Benefits</relationshipLabel>
        <relationshipName>Transaction_Benefits</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Transaction Benefit</label>
    <nameField>
        <displayFormat>TBN-{0000000}</displayFormat>
        <label>Benefit No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Benefits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/classes/EventBenefitHelper.cls
public class EventBenefitHelper {
    public static List<Transaction_Benefit__c> CreateTransactionBenefits(Map<Gift_Detail__c, string> eventLevelToCreate) {
        List<Transaction_Benefit__c> retVal = new List<Transaction_Benefit__c>();
        Map<string, List<Event_Level_Benefit__c>> event_to_eventbenefits = new Map<string, List<Event_Level_Benefit__c>>(); 
        for(Event_Level_Benefit__c elb : [SELECT Id, Event_Level__c, Benefit__c, Quantity__c FROM Event_Level_Benefit__c WHERE Event_Level__c IN :eventLevelToCreate.values()]){            
            if(event_to_eventbenefits.containsKey(elb.Event_Level__c)) {
                event_to_eventbenefits.get(elb.Event_Level__c).add(elb);
            }
            else {
                List<Event_Level_Benefit__c> temp = new List<Event_Level_Benefit__c>();
                temp.add(elb);
                event_to_eventbenefits.put(elb.Event_Level__c, temp);
            }
        }
            
        for(Gift_Detail__c gd : eventLevelToCreate.keyset()){
            if(eventLevelToCreate.get(gd) != null && event_to_eventbenefits.get(eventLevelToCreate.get(gd)) != null){    //event_to_eventbenefits.values().size() > 0
                for(Event_Level_Benefit__c evtvl : event_to_eventbenefits.get(eventLevelToCreate.get(gd))) {
                    Transaction_Benefit__c tracbnft = new Transaction_Benefit__c();
                    tracbnft.Benefit__c = evtvl.Benefit__c;
                    tracbnft.Benefit_Quantity__c = evtvl.Quantity__c * gd.Quantity__c;                
                    tracbnft.Transaction__c = gd.Gift__c;
                    tracbnft.Allocation__c = gd.Id;
                    retVal.add(tracbnft);
                }
            }
        }
        return retVal;
    }
    public static List<Transaction_Benefit__c> DeleteTransactionBenefits(Set<string> eventLevelToDelete) {
        List<Transaction_Benefit__c> retVal = [SELECT Id FROM Transaction_Benefit__c WHERE Allocation__c IN :eventLevelToDelete];
        return retVal;
    }    
}