Causeview Package Complete/ant script/retrieveUnpackaged/objects/Benefit__c.object
<CustomObject>
    <description>Captures benefits related to event levels and membership levels</description>
    <label>Benefit</label>
    <nameField>
        <label>Benefit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Event_Level_Benefit__c.object
<CustomObject>
    <description>Causeview - benefits related to specific Event Level</description>
    <fields>
        <fullName>Benefit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Benefit included with Event Level</description>
        <inlineHelpText>Benefit included with Event Level</inlineHelpText>
        <label>Benefit</label>
        <referenceTo>Benefit__c</referenceTo>
        <relationshipLabel>Event Levels</relationshipLabel>
        <relationshipName>Event_Level_Benefits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Level Benefit</label>
    <nameField>
        <displayFormat>ELB-{000000}</displayFormat>
        <label>Benefits No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Level Benefits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/classes/BenefitHandler.cls
public class BenefitHandler {
    public static void UpdateEventLevels(List<Benefit__c> records) {
        Set<string> benefitIds = new Set<string>();
        for (Benefit__c b : records) {
            benefitIds.add(b.Id);
        }
        List<Benefit__c> benefits = [SELECT Id, (SELECT Id FROM Event_Level_Benefits__r) FROM Benefit__c WHERE Id IN :benefitIds FOR UPDATE];
        List<Event_Level_Benefit__c> elb = new List<Event_Level_Benefit__c>();
        for (Benefit__c b : benefits ) {
            if (b.Event_Level_Benefits__r.size() > 0) {
                elb.addAll(b.Event_Level_Benefits__r);  
            }
        }
        update elb;
    }
}