Causeview Package Complete/ant script/retrieveUnpackaged/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Number_of_Tickets_Planned__c</fullName>
        <label>Number of Tickets Planned</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Event_Level__c.object
<CustomObject>
    <description>Causeview - event ticket and sponsorship levels</description>
    <fields>
        <fullName>Event__c</fullName>
        <description>Event the ticket type is belongs to</description>
        <label>Event</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ticket_Count__c</fullName>
        <formula>Quantity_Available__c *  Attendees_per_Level__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ticket Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Event Level</label>
    <nameField>
        <label>Event Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/classes/EventLevelHandler.cls
public class EventLevelHandler {
    public static void RollupTotals(Set<string> eventLevelIds) {
        List<Campaign> camps = [SELECT Number_of_Tickets_Planned__c, (SELECT Ticket_Count__c FROM Tickets__r) FROM Campaign WHERE Id IN :eventLevelIds FOR UPDATE];
        for (Campaign c : camps) {
            Decimal total = 0;
            for (Event_Level__c el : c.Tickets__r) {
                total = total + el.Ticket_Count__c;            
            }
            c.Number_Of_Tickets_Planned__c = total;
        }
        update camps;
    }
}