Causeview Package Complete/ant script/retrieveUnpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Volunteer_Availability__c</fullName>
        <description>Times during the week when the individual is available to volunteer.</description>
        <inlineHelpText>Captures when volunteer is available for service</inlineHelpText>
        <label>Volunteer Availability</label>
        <picklist>
            <picklistValues>
                <fullName>Monday Morning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monday Afternoon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monday Evening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday Morning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday Afternoon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday Evening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday Morning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday Afternoon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday Evening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday Morning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday Afternoon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday Evening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday Morning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday Afternoon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday Evening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday Morning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday Afternoon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday Evening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunday Morning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunday Afternoon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunday Evening</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Volunteer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if constituent is a current volunteer</description>
        <inlineHelpText>Checked if constituent is a current volunteer</inlineHelpText>
        <label>Volunteer</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Volunteer_Application__c.object
<CustomObject>
    <description>Used to manage and review the Applications submitted by Volunteers</description>
    <fields>
        <fullName>Service_Exit_Date__c</fullName>
        <description>Date the volunteer stopped volunteering in the role to which the application relates</description>
        <label>Service Exit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The current status of the application (Submitted / In Screening, Screening Complete, Approved, Placed, Declined, Exited).</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted / In-Screening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Screening Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Placed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exited</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volunteer_Availability__c</fullName>
        <description>Times during the week when the individual is available to volunteer.</description>
        <label>Volunteer Availability</label>
        <picklist>
            <picklistValues>
                <fullName>Monday Morning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monday Afternoon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monday Evening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday Morning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday Afternoon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday Evening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday Morning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday Afternoon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday Evening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday Morning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday Afternoon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday Evening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday Morning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday Afternoon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday Evening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday Morning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday Afternoon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday Evening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunday Morning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunday Afternoon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunday Evening</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Volunteer_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The ID of the Volunteer Role the application is related to.</description>
        <inlineHelpText>The Volunteer Role that the Application is matched with</inlineHelpText>
        <label>Volunteer Role</label>
        <referenceTo>Volunteer_Role__c</referenceTo>
        <relationshipLabel>Volunteer Applications</relationshipLabel>
        <relationshipName>Volunteer_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The ID of the Individual making the application.</description>
        <label>Volunteer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Applications</relationshipLabel>
        <relationshipName>Volunteer_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Application</label>
    <nameField>
        <displayFormat>VA-{000000}</displayFormat>
        <label>Volunteer Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Volunteer_Role__c.object
<CustomObject>
    <description>Used to track and manage the required Volunteer Roles within the Volunteer Opportunities in the Causeview Volunteers application</description>
    <label>Volunteer Role</label>
    <nameField>
        <label>Volunteer Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Volunteer_Shift__c.object
<CustomObject>
    <description>Outlines the time shifts for each Volunteer Role</description>
    <fields>
        <fullName>Day_of_the_Week__c</fullName>
        <description>The day of the week the volunteer shift falls on.</description>
        <inlineHelpText>The day of the week the Volunteer Position Shift falls on</inlineHelpText>
        <label>Day of the Week</label>
        <picklist>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Duration_Hours__c</fullName>
        <description>The duration of each shift in hours (End Time - Start Time).</description>
        <formula>( End_Time__c -  Start_Time__c) *24</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duration (Hours)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>The date and time the volunteer shift ends (MM/DD/YYYY 12:00 AM).</description>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <description>Frequency of the shift (Flexible, One-Time, Weekly, Bi-Weekly, Monthly).</description>
        <label>Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Flexible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One-Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Location_Address__c</fullName>
        <description>The full address of the Organization where the volunteer shift will take place.</description>
        <formula>IF(  Location__c != &quot;&quot;, Location__r.BillingStreet &amp; &quot;, &quot; &amp; Location__r.BillingCity &amp; &quot;, &quot; &amp; Location__r.BillingState &amp; &quot;, &quot; &amp; Location__r.BillingPostalCode, &quot;No Location Set&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>The date and time the volunteer shift starts (MM/DD/YYYY 12:00 AM).</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Volunteer_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The ID of the Application of the volunteer assigned to the shift.</description>
        <inlineHelpText>The Application that the Shift is related to</inlineHelpText>
        <label>Volunteer Application</label>
        <referenceTo>Volunteer_Application__c</referenceTo>
        <relationshipName>Volunteer_Position_Shifts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Role__c</fullName>
        <description>The ID of the Volunteer Role the shift is for</description>
        <inlineHelpText>The related Volunteer Role</inlineHelpText>
        <label>Volunteer Role</label>
        <referenceTo>Volunteer_Role__c</referenceTo>
        <relationshipLabel>Volunteer Shifts</relationshipLabel>
        <relationshipName>Volunteer_Position_Shifts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Volunteer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Individual assigned to position shift.</description>
        <label>Volunteer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Volunteer_Position_Shifts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Shift</label>
    <nameField>
        <displayFormat>VS-{000000}</displayFormat>
        <label>Volunteer Shift Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/classes/CPlaceApplicant.cls
public with sharing class CPlaceApplicant {

    public PageReference place() {    
        List<Volunteer_Shift__c> shiftsToUpdate = new List<Volunteer_Shift__c>();
        Integer count = 0;
        for (PlacementWrapper pw : shift_wrappers) {
            if (pw.placed) {
                pw.shift.Volunteer__c = volunteerId;
                shiftsToUpdate.add(pw.shift);
                count++;
            }
            else {
                pw.shift.Volunteer__c = null;
                pw.shift.Volunteer_Application__c = null;                
                shiftsToUpdate.add(pw.shift);
            }
            if (count == 0) {
                app.Status__c = 'Exited';
                app.Service_Exit_Date__c = Date.Today();
            }
            else {
                app.Status__c = 'Placed';
            }
        }
        System.debug(shiftsToUpdate);
        update shiftsToUpdate;
        update app;
        return new PageReference('/' + ApexPages.CurrentPage().GetParameters().get('id'));        
    }

    
    public class PlacementWrapper {
        public PlacementWrapper() { }
        public boolean placed { get; set; }
        public Volunteer_Shift__c shift { get; set; }
    }
    
    public List<PlacementWrapper> shift_wrappers { get; set; }
    public string volunteerId { get; set; }
    public Contact volunteer { get; set; }
    public Volunteer_Application__c app { get; set; }
    
    public CPlaceApplicant() {
        shift_wrappers = new List<PlacementWrapper>();
        app = [SELECT Id, Volunteer_Role__c, Volunteer__c, Volunteer_Availability__c FROM Volunteer_Application__c WHERE Id = :ApexPages.CurrentPage().GetParameters().get('id') LIMIT 1];
        volunteerId = app.Volunteer__c;
        volunteer = [SELECT Id, Volunteer_Availability__c FROM Contact WHERE Id = :volunteerId];
        for (Volunteer_Shift__c vps : [SELECT Id, Name, Volunteer__c, Start_Time__c,End_Time__c,Day_of_the_Week__c ,Duration_Hours__c ,Frequency__c ,Location_Address__c    FROM Volunteer_Shift__c WHERE Volunteer_Role__c = :app.Volunteer_Role__c AND (Volunteer__c = :volunteerId OR Volunteer__c = '' OR Volunteer__c = null)]) {
            PlacementWrapper pw = new PlacementWrapper();
            pw.placed = (vps.Volunteer__c == volunteerId);
            pw.shift = vps;
            shift_wrappers.add(pw);
        }
        
    }
}