Causeview Package Complete/ant script/retrieveUnpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Consecutive_Years_of_Giving__c</fullName>
        <label>Consecutive Years of Giving</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Consecutive_Years_of_Transactions__c</fullName>
        <label>Consecutive Years of Transactions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Gift_Amount__c</fullName>
        <label>Last Gift Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Fiscal_Gifts__c</fullName>
        <description>Total number of gifts by constituent within current fiscal year</description>
        <inlineHelpText>Total number of gifts by constituent within current fiscal year</inlineHelpText>
        <label>Quantity of Fiscal Gifts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Fiscal_Transaction_Amount__c</fullName>
        <description>Total dollar value of transactions by constituent within current fiscal year</description>
        <inlineHelpText>Total dollar value of transactions by constituent within current fiscal year</inlineHelpText>
        <label>Total Fiscal Transaction Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Fiscal_Transactions__c</fullName>
        <description>Total number of transactions by constituent within current fiscal year</description>
        <inlineHelpText>Total number of transactions by constituent within current fiscal year</inlineHelpText>
        <label>Quantity of Fiscal Transactions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Fiscal_Year_Giving__c</fullName>
        <description>Total dollar value of gifts by constituent within current fiscal year</description>
        <inlineHelpText>Total dollar value of gifts by constituent within current fiscal year</inlineHelpText>
        <label>Total Fiscal Year Giving</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Lifetime_Fundraising__c</fullName>
        <description>Total lifetime fundraising by constituent.  Includes all giving, primary solicitations and soft credits</description>
        <inlineHelpText>Total lifetime fundraising by constituent.  Includes all giving, primary solicitations and soft credits</inlineHelpText>
        <label>Total Lifetime Fundraising</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Lifetime_Gifts__c</fullName>
        <description>Total number of gifts by constituent within lifetime</description>
        <inlineHelpText>Total number of gifts by constituent within lifetime</inlineHelpText>
        <label>Quantity of Lifetime Gifts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Lifetime_Giving__c</fullName>
        <description>Total dollar value of gifts by constituent within lifetime</description>
        <inlineHelpText>Total dollar value of gifts by constituent within lifetime</inlineHelpText>
        <label>Total Lifetime Giving</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Lifetime_Transaction_Amount__c</fullName>
        <description>Total dollar value of transactions by constituent within lifetime</description>
        <inlineHelpText>Total dollar value of transactions by constituent within lifetime</inlineHelpText>
        <label>Total Lifetime Transaction Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Lifetime_Transactions__c</fullName>
        <description>Total number of transactions by constituent within lifetime</description>
        <inlineHelpText>Total number of transactions by constituent within lifetime</inlineHelpText>
        <label>Quantity of Lifetime Transactions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Gift__c.object
<CustomObject>
    <description>Causeview - Any financial transactions including: gifts, product purchases, event registrations, membership renewals, etc.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Rollup of all payments with Status = Approved, Deposited, Refunded</description>
        <inlineHelpText>Sum of all payments with status (Approved, Deposited, Refunded)</inlineHelpText>
        <label>Approved Amount</label>
        <summarizedField>Payment__c.Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Payment__c.Status__c</field>
            <operation>equals</operation>
            <value>Approved, Deposited, Refunded, Invoiced</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Payment__c.Amount__c</field>
            <operation>notEqual</operation>
            <value>0</value>
        </summaryFilterItems>
        <summaryForeignKey>Payment__c.Donation__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Constituent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Individual</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Constituent)</relationshipLabel>
        <relationshipName>Gifts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gift_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Solicitor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Deprecated - all soft credits are managed via Soft Credit object</description>
        <inlineHelpText>Deprecated - all soft credits are managed via Soft Credit object</inlineHelpText>
        <label>Primary Solicitor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Primary Solicitor)</relationshipLabel>
        <relationshipName>Gifts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Entered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acknowledged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Solicitor__c.object
<CustomObject>
    <description>Causeview - Captures credit given to individuals that participated in the solicitation of a gift.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <formula>IF(ISBLANK(Custom_Amount__c), Gift__r.Amount__c, Custom_Amount__c)</formula>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gift_Date__c</fullName>
        <formula>Gift__r.Gift_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The date we expect to receive payment</inlineHelpText>
        <label>Gift Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gift_Status__c</fullName>
        <description>Status of related gift.</description>
        <formula>TEXT(Gift__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gift Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gift__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Gift that soft credit is related to.</description>
        <label>Gift</label>
        <referenceTo>Gift__c</referenceTo>
        <relationshipLabel>Soft Credits</relationshipLabel>
        <relationshipName>Soft_Credits</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Solicitor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Individual involved in soliciting gift</description>
        <label>Individual Solicitor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Soft Credits</relationshipLabel>
        <relationshipName>Additional_Solicitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Soft Credit</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Soft Credit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Soft Credits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/classes/RollupBatchForConsecutiveYears.cls
global class RollupBatchForConsecutiveYears implements Database.Batchable<sObject>, Database.stateful{
    
    global List<Contact> contactRecord = new List<Contact>();
    global set<string> cid = new Set<string>();
    global DateTime previousRunTime;
    List<String> giftQueries = new List<String>();
    global RollupBatchForConsecutiveYears()
    {
    }
    global Database.Querylocator start(Database.BatchableContext BC)
    {
        //get a list of constieunts whose gift is updated or created since the last run.
        if (previousRunTime == null) previousRunTime = DateTime.now().addHours(-24);
            
        //string query = 'Select c.Id From Contact c' + 
        //  ' WHERE c.Id IN (Select Constituent__c FROM Gift__c WHERE Constituent__c!=null AND Gift_Date__c !=null AND LastModifiedDate > :previousRunTime )';
        string query = GetQuery();
        System.debug(query);
        return Database.getQueryLocator(query);
    }
    public static string GetQuery()
    {   
        string query = '';
        query += 'SELECT Id, Consecutive_Years_of_Giving__c, Consecutive_Years_of_Transactions__c, Last_Gift_Amount__c, Total_Lifetime_Gifts__c, Total_Lifetime_Giving__c, ';
        query += 'Total_Fiscal_Gifts__c, Total_Fiscal_Year_Giving__c, Total_Lifetime_Transactions__c, Total_Lifetime_Transaction_Amount__c, ';
        query += 'Total_Fiscal_Transactions__c, Total_Fiscal_Transaction_Amount__c, Total_Lifetime_Fundraising__c, ';
        //commented by nitin
        //query += '(Select Id, Amount__c, Status__c, Gift_Date__c, RecordTypeId From Gifts__r ORDER BY Gift_Date__c DESC), ';
        //query += '(Select Id, Amount__c, Gift_Date__c, Gift_Status__c From Additional_Solicitations__r), ';
        query += '(Select Id, Amount__c, Status__c From Gifts1__r), ';
        //query += '(Select Id, Amount__c, Status__c From Gifts1__r) ';
        query += '(Select npe4__RelatedContact__c FROM npe4__Relationships1__r where cv_pkg_dev_I__Apply_Soft_Credit__c=true) ';
        //query += 'FROM Contact c where Id=\'003A000000qVaMQ\'';
        query += 'FROM Contact c';
        
        return query;       
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope)
    {
        Map<ID, Contact> scopeMap = new Map<ID, Contact>((List<Contact>)scope);
        List<Contact> contactToUpdate = new List<Contact>();
        //system.debug(scopeMap.keySet().size());
        Set<ID> contactIds = scopeMap.keySet();
        //Commented by nitin
        for(Contact c : (List<Contact>)scope){
            cid.add(c.id);
            contactRecord.add(c);
        }
    }
    // Reschedule the job for an hour from now
    global void finish(Database.BatchableContext BC)
    {
        RollupBatchforgift r = new RollupBatchforgift();
        r.cid1.addAll(cid);
        r.con.addAll(contactRecord);
        r.query = 'Select Id, Amount__c, Status__c, Gift_Date__c, Constituent__c, RecordTypeId From Gift__c where Constituent__c IN: cid1 ORDER BY Gift_Date__c DESC';
        Database.executeBatch(r);
    }
}