Causeview Package Complete/ant script/retrieveUnpackaged/objects/Event_Registration__c.object
<CustomObject>
    <description>Causeview - Registrations links individuals to events and to a transaction.</description>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Transaction associated to the event registration.  Applicable to events with paid fee.</description>
        <label>Transaction</label>
        <referenceTo>Gift__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Event_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sysLastTransactionUpdate__c</fullName>
        <description>Date defines when the related Transaction, Allocation or Payment was last updated.  This enables workflows to fire if dependent on Transaction values.</description>
        <label>_sysLastTransactionUpdate</label>
        <type>Date</type>
    </fields>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>ER-{0000000}</displayFormat>
        <label>Registration No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/classes/sysLastTransUpdatePaymentBatch.cls
global class sysLastTransUpdatePaymentBatch implements Database.Batchable<sObject>{
    
    Set<Id> setGiftIds = new Set<Id>();
    global sysLastTransUpdatePaymentBatch(Set<Id> giftIds){
        setGiftIds = giftIds;
    }
    
    global Database.queryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([SELECT Id,sysLastTransactionUpdate__c FROM Event_Registration__c WHERE Transaction__c IN: setGiftIds]);
    }
    
    global void execute(Database.BatchableContext BC, List<Event_Registration__c> eventRegList){
        if(eventRegList.size() > 0) {
            for(Event_Registration__c eventReg: eventRegList)
            {
               eventReg.sysLastTransactionUpdate__c = system.today();
               //toUpdateEventReg.add(eventReg);
            }
            /*if(toUpdateEventReg.size() > 0) {
             update toUpdateEventReg;
            }*/
        }    
        system.debug('---- Script Statements: '+Limits.getScriptStatements()); 
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
}