Causeview Package Complete/ant script/retrieveUnpackaged/objects/Gift__c.object
<CustomObject>
    <description>Causeview - Any financial transactions including: gifts, product purchases, event registrations, membership renewals, etc.</description>
    <fields>
        <fullName>Gift_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Solicitor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Deprecated - all soft credits are managed via Soft Credit object</description>
        <inlineHelpText>Deprecated - all soft credits are managed via Soft Credit object</inlineHelpText>
        <label>Primary Solicitor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Primary Solicitor)</relationshipLabel>
        <relationshipName>Gifts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/classes/RollupSolicitorBatch.cls
global class RollupSolicitorBatch implements Database.Batchable<sObject> {
  
    global DateTime previousRunTime;
	global RollupSolicitorBatch(DateTime lastRun) {
		previousRunTime = lastRun;
	}
	global Database.Querylocator start(Database.BatchableContext BC) {
	    if (previousRunTime==null)
	    	previousRunTime = DateTime.now().addHours(-24);
		string query = 'Select c.Id From Contact c' + 
			' WHERE Id IN (Select Primary_Solicitor__c FROM Gift__c WHERE Primary_Solicitor__c!=null AND Gift_Date__c !=null AND LastModifiedDate > :previousRunTime )';
		return Database.getQueryLocator(query);
	}
	global void execute(Database.BatchableContext BC, List<sObject> scope) {
		Map<ID, Contact> scopeMap = new Map<ID, Contact>((List<Contact>)scope);
		RollupHelper.RecalculateTotalGiving(scopeMap.keySet());
	}
	global void finish(Database.BatchableContext BC) {
	}
  
}