Causeview Package Complete/ant script/retrieveUnpackaged/objects/Gift_Batch__c.object
<CustomObject>
    <description>Causeview - Offline batch processing of gifts.</description>
    <fields>
        <fullName>Name__c</fullName>
        <description>Batch name.</description>
        <label>Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Batch Template associated.</description>
        <label>Template Name</label>
        <referenceTo>Batch_Template__c</referenceTo>
        <relationshipLabel>Gift Batches</relationshipLabel>
        <relationshipName>Gift_Batches</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Gift Batch</label>
    <nameField>
        <displayFormat>GB-{00000}</displayFormat>
        <label>Batch #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gift Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/classes/TestCloneBatchTemplateOnCreateTrigger.cls
@isTest
public class TestCloneBatchTemplateOnCreateTrigger {
    static TestMethod void test() {
        RecordType RT = [SELECT Id FROM RecordType WHERE SobjectType = 'cv_pkg_dev_I__Batch_Template__c' AND Name = 'Parent'];
        cv_pkg_dev_I__Batch_Template__c temp = new cv_pkg_dev_I__Batch_Template__c();
        temp.Name = 'test';
        temp.RecordTypeId = RT.Id;
        Insert temp;

        Gift_Batch__c gb = new Gift_Batch__c();
        gb.Name__c = 'batch';
        gb.Template_Name__c = temp.Id;
        Insert gb;

        //System.assertNotEquals([Select Id, Template_Name__c From Gift_Batch__c Where Id =: gb.Id].Template_Name__c, temp.Id);
    }
}