Causeview Package Complete/ant script/retrieveUnpackaged/objects/Gift__c.object
<CustomObject>
    <description>Causeview - Any financial transactions including: gifts, product purchases, event registrations, membership renewals, etc.</description>
    <fields>
        <fullName>Sponsorship_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Defines amount of transaction that is related to sponsorships (not eligible for tax receipt)</description>
        <inlineHelpText>Defines amount of transaction that is related to sponsorships (not eligible for tax receipt)</inlineHelpText>
        <label>Sponsorship/Benefit Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Transaction_Benefit__c.object
<CustomObject>
    <description>Causeview - captures all benefits included with Transaction</description>
    <fields>
        <fullName>Sponsorship_Amount__c</fullName>
        <description>Total sponsorship amount of benefit (benefit.sponsorship amount * benefit quantity)</description>
        <formula>Benefit__r.Benefit_Value__c *  Benefit_Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total value of benefit</inlineHelpText>
        <label>Benefit Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <description>Transaction linked to event level</description>
        <label>Transaction</label>
        <referenceTo>Gift__c</referenceTo>
        <relationshipLabel>Transaction Benefits</relationshipLabel>
        <relationshipName>Transaction_Benefits</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Transaction Benefit</label>
    <nameField>
        <displayFormat>TBN-{0000000}</displayFormat>
        <label>Benefit No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Benefits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/classes/TransactionBenefitHandler.cls
public class TransactionBenefitHandler {
    public static void RollupTotals (List<Transaction_Benefit__c> records) {
        Set<string> giftIds = new Set<string>();
        for (Transaction_Benefit__c tb : records) {
            giftIds.add(tb.Transaction__c);
        }
        List<Gift__c> gifts = [SELECT Id, Sponsorship_Amount__c, (SELECT Id, Sponsorship_Amount__c FROM Transaction_Benefits__r) FROM Gift__c WHERE Id IN :giftIds];
        for (Gift__c g : gifts) {
            Decimal total = 0;
            for (Transaction_Benefit__c tb : g.Transaction_Benefits__r) {
                total = total + tb.Sponsorship_Amount__c;
            }
            g.Sponsorship_Amount__c = total;
        }
        update gifts;
    }
}