Causeview Package Complete/ant script/retrieveUnpackaged/objects/Gift__c.object
<CustomObject>
    <description>Causeview - Any financial transactions including: gifts, product purchases, event registrations, membership renewals, etc.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Rollup of all payments with Status = Approved, Deposited, Refunded</description>
        <inlineHelpText>Sum of all payments with status (Approved, Deposited, Refunded)</inlineHelpText>
        <label>Approved Amount</label>
        <summarizedField>Payment__c.Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Payment__c.Status__c</field>
            <operation>equals</operation>
            <value>Approved, Deposited, Refunded, Invoiced</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Payment__c.Amount__c</field>
            <operation>notEqual</operation>
            <value>0</value>
        </summaryFilterItems>
        <summaryForeignKey>Payment__c.Donation__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Constituent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Individual</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Constituent)</relationshipLabel>
        <relationshipName>Gifts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gift_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Entered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acknowledged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Payment_Amount__c</fullName>
        <description>Total payment roll-up amount (includes Approved and Committed payments)</description>
        <inlineHelpText>Sum of all payments (includes Approved and Committed payments)</inlineHelpText>
        <label>Total Payment Amount</label>
        <summarizedField>Payment__c.Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Payment__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Declined, Pending, Voided</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Payment__c.Amount__c</field>
            <operation>notEqual</operation>
            <value>0</value>
        </summaryFilterItems>
        <summaryForeignKey>Payment__c.Donation__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Grant</fullName>
        <active>true</active>
        <description>A converted Opportunity</description>
        <label>Grant</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Gift_Detail__c.object
<CustomObject>
    <description>Causeview - Manages the allocation of your gifts across Funds, Appeals, Tributes, Products and Campaigns.</description>
    <fields>
        <fullName>Allocation_Date__c</fullName>
        <description>Date of allocation - referenced from Gift Payment</description>
        <inlineHelpText>Date of allocation - referenced from Gift Payment</inlineHelpText>
        <label>Allocation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Allocated Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Constituent__c</fullName>
        <formula>IF(ISBLANK( Gift__r.Organization__c ), HYPERLINK(&quot;/&quot; &amp; Gift__r.Constituent__c, Gift__r.Constituent__r.FirstName &amp; &quot; &quot; &amp; Gift__r.Constituent__r.LastName,&quot;_self&quot;), HYPERLINK(&quot;/&quot; &amp; Gift__r.Organization__c, Gift__r.Organization__r.Name,&quot;_self&quot;))</formula>
        <label>Constituent</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gift__c</fullName>
        <label>Transaction</label>
        <referenceTo>Gift__c</referenceTo>
        <relationshipLabel>Allocations</relationshipLabel>
        <relationshipName>Gift_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <description>Deprecated field - combined into Constituent field</description>
        <formula>HYPERLINK(&quot;/&quot; &amp; Gift__r.Organization__c, Gift__r.Organization__r.Name,&quot;_self&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organization</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Payment associated to the allocation record.</description>
        <inlineHelpText>Payment associated to the allocation record.</inlineHelpText>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Gift Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Allocation</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Allocation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Payment__c.object
<CustomObject>
    <description>Causeview - Payment records relating to a Transaction.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Constituent__c</fullName>
        <formula>IF(ISBLANK( Donation__r.Organization__c ), HYPERLINK(&quot;/&quot; &amp; Donation__r.Constituent__c, Donation__r.Constituent__r.FirstName &amp; &quot; &quot; &amp; Donation__r.Constituent__r.LastName,&quot;_self&quot;), HYPERLINK(&quot;/&quot; &amp; Donation__r.Organization__c, Donation__r.Organization__r.Name,&quot;_self&quot;))</formula>
        <label>Constituent</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Deposited__c</fullName>
        <label>Date Deposited</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Donation__c</fullName>
        <label>Transaction</label>
        <referenceTo>Gift__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Recurring_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Credit Card</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card - Offline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACH/PAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stock</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Kind</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Committed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refunded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Written Off</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Payment No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/classes/testMajorDonor.cls
@isTest
class testMajorDonor {
     static testMethod void testTrigger() {
         Contact aContact = new Contact(LastName = 'Test');     
         insert aContact;
         
         List<RecordType> rtypes = [Select Name, Id From RecordType where sObjectType='cv_pkg_dev_I__Gift__c' and isActive=true and Name = 'Gift'];

         Gift__c aGift = new Gift__c(Status__c = 'Entered', RecordTypeID = rtypes[0].Id, Constituent__c = aContact.Id, Gift_Date__c = Date.Today());
         insert aGift;
         
         List<RecordType> rtypes2 = [Select Name, Id From RecordType where sObjectType='cv_pkg_dev_I__Payment__c' and isActive=true and Name = 'Credit Card'];
         Payment__c aPayment = new Payment__c(Payment_Type__c = 'Credit Card', RecordTypeID = rtypes2[0].Id, Status__c = 'Approved', Amount__c = 10000, Donation__c = aGift.Id);   
         insert aPayment; 
         
         aPayment.Date_Deposited__c = date.today();
         update aPayment;
         
         aGift.Constituent__c = null;
         Account anAcc = new Account(Name = 'Test');
         insert anAcc;
         
         aGift.Organization__c = anAcc.Id;
         update aGift;
         
         List<RecordType> rtypes3 = [Select Name, Id From RecordType where sObjectType='cv_pkg_dev_I__Gift__c' and isActive=true and Name = 'Grant'];
         aGift.RecordTypeID = rtypes3[0].Id;
         update aGift;
         
         System.debug(aGift.Total_Payment_Amount__c); 
         system.debug(aContact.Id);
         system.debug(aGift.Id);
         system.debug(aPayment.Id);         
     }
     
     //test clone transaction trigger
     static testMethod void testCloneTransactionTrigger()
     {
         Contact aContact = new Contact(LastName = 'Test');    
         insert aContact;
         
         List<RecordType> rtypes = [Select Name, Id From RecordType where sObjectType='cv_pkg_dev_I__Gift__c' and isActive=true and Name = 'Gift'];

         Gift__c aGift = new Gift__c(Status__c = 'Entered', RecordTypeID = rtypes[0].Id, Constituent__c = aContact.Id, Gift_Date__c = Date.Today());
         insert aGift;
         
         List<RecordType> rtypes2 = [Select Name, Id From RecordType where sObjectType='cv_pkg_dev_I__Payment__c' and isActive=true and Name = 'Credit Card'];
         Payment__c aPayment = new Payment__c(Payment_Type__c = 'Credit Card', RecordTypeID = rtypes2[0].Id, Status__c = 'Approved', Amount__c = 10000, Donation__c = aGift.Id);   
         insert aPayment; 
         
         Gift_Detail__c gd1 = new Gift_Detail__c(Payment__c = aPayment.Id, Gift__c = aGift.Id, Allocation_Date__c = Date.Today()-5, Amount__c = 10000);
         insert gd1;
         
         Gift__c bGift = new Gift__c(Status__c = 'Entered', cv_pkg_dev_I__Sys_Clone_Transaction__c=aGift.Id, RecordTypeID = rtypes[0].Id, Constituent__c = aContact.Id, Gift_Date__c = Date.Today());
         insert bGift;
         
         Payment__c bPayment = new Payment__c(Payment_Type__c = 'Credit Card', RecordTypeID = rtypes2[0].Id, Status__c = 'Approved', Amount__c = 5000, Donation__c = bGift.Id);   
         insert bPayment; 
        
     }
}