Causeview Package Complete/ant script/retrieveUnpackaged/objects/Gift__c.object
<CustomObject>
    <description>Causeview - Any financial transactions including: gifts, product purchases, event registrations, membership renewals, etc.</description>
    <fields>
        <fullName>Constituent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Individual</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Constituent)</relationshipLabel>
        <relationshipName>Gifts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Receipt_Type__c</fullName>
        <label>Receipt Type</label>
        <picklist>
            <picklistValues>
                <fullName>Single Receipt</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No Receipt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consolidated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Entered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acknowledged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/givingpowerSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Causeview communication and notification templates.</description>
    <fields>
        <fullName>ConsolidatedReceiptEmailTemplateId__c</fullName>
        <label>Consolidated Receipt Email Template ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DupeConsolidatedReceiptEmailTempId__c</fullName>
        <label>Dupe Consolidated Receipt Email Temp Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DupeEmailTemplateId__c</fullName>
        <label>Duplicate Email Template ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dupe_Event_Registration_Template_ID__c</fullName>
        <description>Event registration communication template ID (Salesforce ID) - duplicate/replacement template</description>
        <inlineHelpText>Event registration communication template ID (Salesforce ID) - duplicate/replacement template</inlineHelpText>
        <label>Dupe Event Registration Template ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmailTemplateId__c</fullName>
        <inlineHelpText>The Id of the Visualforce Email Template</inlineHelpText>
        <label>Email Template ID</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Registration_Email_Template_ID__c</fullName>
        <description>Event registration communication template ID (Salesforce ID)</description>
        <inlineHelpText>Event registration communication template ID (Salesforce ID)</inlineHelpText>
        <label>Event Registration Email Template ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_Wide_Email_ID__c</fullName>
        <description>The Salesforce ID of the Organization Wide Email address you would like your Automatic receipting messages to come from.</description>
        <inlineHelpText>The Salesforce ID of the Organization Wide Email address you would like your Automatic receipting messages to come from.</inlineHelpText>
        <label>Org Wide Email ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Causeview Templates</label>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Receipt__c.object
<CustomObject>
    <description>Causeview - Tax receipt for transaction records.</description>
    <fields>
        <fullName>Constituent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Captures the constituent ID for email receipting purposes.  Hidden to end users.</description>
        <label>Constituent</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Issued__c</fullName>
        <description>Populated by Conga Merge when receipt is generated.</description>
        <label>Date Issued</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_Subject__c</fullName>
        <description>The email subject of the email sent to the donor.</description>
        <inlineHelpText>The email subject of the email sent to the donor.</inlineHelpText>
        <label>Email Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gift__c</fullName>
        <label>Gift</label>
        <referenceTo>Gift__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Print_Date__c</fullName>
        <label>Print Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Receipt_Email_Address__c</fullName>
        <description>Address receipt was emailed to.</description>
        <label>Receipt Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Receipt_Type__c</fullName>
        <description>Defines the type of receipt either single or consolidated.</description>
        <inlineHelpText>Single: receipt is linked to a single payment
Consolidated: receipt is linked to multiple payments</inlineHelpText>
        <label>Receipt Type</label>
        <picklist>
            <picklistValues>
                <fullName>Single</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Consolidated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Issued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To be Issued</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Void</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Receipt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <recordTypes>
        <fullName>Duplicate</fullName>
        <active>true</active>
        <description>Deprecated record type</description>
        <label>Duplicate</label>
    </recordTypes>
    <recordTypes>
        <fullName>Issued</fullName>
        <active>true</active>
        <description>Read-only receipt record.</description>
        <label>Issued</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/classes/ReceiptPrinter.cls
public with sharing class ReceiptPrinter {

    public Receipt__c receipt { get; set; }

    public PageReference rerender() {
        if (receipt.Constituent__c == null)        
        { ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'No Constituent Lookup on Receipt, cannot Email receipt.')); }
        return null;
    }

    public Boolean format { get; set; }
    public Boolean isDupe { get; set; }
    //For Consolidated Receipt
    public Boolean isConsolidatedReceipt { get; set; }
    
    public String giftRecordType  { get; set; } 
    public String emailSubject  { get; set; } 
    public String templateId  { get; set; }    
    public String dupeTemplateId  { get; set; }        
    public String orgWideId { get; set; }  
    public RecordType rt { get; set; }  

    public PageReference print() {
        if (format == true)
        {
            try
            {
                
                
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                if (isDupe == True)
                {   /*if(emailSubject != null)
                        {   EmailTemplate dupeTemplate = [SELECT Id, Subject FROM EmailTemplate where Id =: dupeTemplateId ];
                            dupeTemplate.subject = emailSubject;
                            update dupeTemplate;
                            
                        }*/
                        
                    mail.setTemplateID(dupeTemplateId); 
                }
                else
                { 
                    /*if(emailSubject != null)
                        {
                            EmailTemplate nTemplate = [SELECT Id, Subject FROM EmailTemplate where Id =: templateId ];
                            nTemplate.subject = emailSubject;
                            update nTemplate;
                        }*/
                    mail.setTemplateID(templateId);
                  }
                mail.setWhatId(receipt.Id);
               //mail.setSubject(receipt.Email_subject__c);
                mail.setTargetObjectId(receipt.Constituent__c);
                mail.setOrgWideEmailAddressId(orgWideId);
                mail.setSaveAsActivity(False);
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                if (isDupe == False)
                { insert new Task(Subject = 'Receipt Emailed', Status = 'Completed', WhatId = receipt.Id, ActivityDate = Date.Today(), WhoId = receipt.Constituent__c, Type = 'Automated Email'); }            
                if (isDupe == True)
                { insert new Task(Subject = 'Duplicate Receipt Emailed', Status = 'Completed', WhatId = receipt.Id, ActivityDate = Date.Today(), WhoId = receipt.Constituent__c, Type = 'Automated Email'); }                 
                if (isDupe == False)
                { receipt.RecordTypeId = rt.Id; receipt.Date_Issued__c = Date.Today(); receipt.Status__c = 'Issued'; update receipt; }                                
                PageReference pgRef = new PageReference('/' + receipt.Id);
                pgRef.setRedirect(true);
                return pgRef;
            }
            catch (Exception ex)
            {
                ApexPages.addMessages(ex);
                return null;
            }
        }
        else
        {
            if (isDupe == False)
            { insert new Task(Subject = 'Receipt Exported for Mailing or Printing', Status = 'Completed', WhatId = receipt.Id, ActivityDate = Date.Today(), WhoId = receipt.Constituent__c, Type = 'Automated Email'); }            
            if (isDupe == True)
            { insert new Task(Subject = 'Duplicate Receipt Exported for Mailing or Printing', Status = 'Completed', WhatId = receipt.Id, ActivityDate = Date.Today(), WhoId = receipt.Constituent__c, Type = 'Automated Email'); } 
            if (isDupe == False)
            { receipt.RecordTypeId = rt.Id; receipt.Date_Issued__c = Date.Today(); receipt.Status__c = 'Issued'; update receipt; }                          
            PageReference pgRef = new PageReference('/' + receipt.Id);
            pgRef.setRedirect(true);
            return pgRef;                             
        }
    }

    public List<SelectOption> getItems() {
    List<SelectOption> options = new List<SelectOption>();
    options.add(new SelectOption('True','Send E-mail'));
    options.add(new SelectOption('False','Save and Print'));
    return options;
    }
    
    public ReceiptPrinter(ApexPages.StandardController controller) {
        List<givingpowerSettings__c> settingsRecords = [SELECT ConsolidatedReceiptEmailTemplateId__c, Event_Registration_Email_Template_ID__c, Dupe_Event_Registration_Template_ID__c, DupeConsolidatedReceiptEmailTempId__c, DupeEmailTemplateId__c, Org_Wide_Email_ID__c, EmailTemplateId__c FROM givingpowerSettings__c WHERE Name = 'Settings'];
        rt = [SELECT Id,Name FROM RecordType WHERE SobjectType = 'cv_pkg_dev_I__Receipt__c' AND Name = 'Issued' LIMIT 1];
        receipt = [SELECT Status__c, Date_Issued__c, Constituent__c, Id, Print_Date__c, Receipt_Email_Address__c, Receipt_Type__c, Gift__r.RecordTypeId,email_subject__c FROM Receipt__c WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
        
        system.debug('-----------Gift__r.RecordTypeId -----'+receipt.Gift__r.RecordTypeId );
        isDupe = false;
        
        giftRecordType = [SELECT Name FROM RecordType WHERE Id =: receipt.Gift__r.RecordTypeId  LIMIT 1].name;

        
        if(receipt.Date_Issued__c != null)
        { isDupe = true; }

        
                if(receipt.Email_subject__c != null)
                    emailSubject =  receipt.Email_subject__c;
                    
        //Check if Receipt is Consolidated.
        isConsolidatedReceipt = false;
        if(receipt.Receipt_Type__c == 'Consolidated')
        { isConsolidatedReceipt = true; }

        if (settingsRecords != null && settingsRecords.size()>0)
        {
            if(isConsolidatedReceipt)
            {  dupeTemplateId = settingsRecords[0].DupeConsolidatedReceiptEmailTempId__c;  templateId = settingsRecords[0].ConsolidatedReceiptEmailTemplateId__c; 
                system.debug('Nitin dupeTemplateId===='+dupeTemplateId);
                system.debug('Nitin templateId===='+templateId);
            }
            else if(giftRecordType == 'Event Registration')
             {  dupeTemplateId = settingsRecords[0].Dupe_Event_Registration_Template_ID__c;  templateId = settingsRecords[0].Event_Registration_Email_Template_ID__c; }
            else
            { dupeTemplateId = settingsRecords[0].DupeEmailTemplateId__c;  templateId = settingsRecords[0].EmailTemplateId__c; 
              system.debug('Nitin dupeTemplateId===='+dupeTemplateId);
                system.debug('Nitin templateId===='+templateId);
            }
            orgWideId = settingsRecords[0].Org_Wide_Email_ID__c;
        }
    }
    
    public ReceiptPrinter() {
        List<givingpowerSettings__c> settingsRecords = [SELECT ConsolidatedReceiptEmailTemplateId__c, DupeConsolidatedReceiptEmailTempId__c,Event_Registration_Email_Template_ID__c, Dupe_Event_Registration_Template_ID__c, DupeEmailTemplateId__c, Org_Wide_Email_ID__c, EmailTemplateId__c FROM givingpowerSettings__c WHERE Name = 'Settings'];
        rt = [SELECT Id,Name FROM RecordType WHERE SobjectType = 'cv_pkg_dev_I__Receipt__c' AND Name = 'Issued' LIMIT 1];
        receipt = [SELECT Status__c, Date_Issued__c, Constituent__c, Id, Print_Date__c, Receipt_Email_Address__c, Receipt_Type__c, Gift__r.RecordTypeId, email_subject__c FROM Receipt__c WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
        isDupe = false;
        
                system.debug('-----------Gift__r.RecordTypeId in () -----'+receipt.Gift__r.RecordTypeId );
        
        
        if(receipt.Date_Issued__c != null)
        { isDupe = true; }

         giftRecordType = [SELECT Name FROM RecordType WHERE Id =: receipt.Gift__r.RecordTypeId  LIMIT 1].name;
          
         
                if(receipt.Email_subject__c != null)
                    emailSubject =  receipt.Email_subject__c; 
          
        //Check if Receipt is Consolidated.
        isConsolidatedReceipt = false;
        if(receipt.Receipt_Type__c == 'Consolidated')
        { isConsolidatedReceipt = true; }

        if (settingsRecords != null && settingsRecords.size()>0)
        {
            if(isConsolidatedReceipt)
            {  dupeTemplateId = settingsRecords[0].DupeConsolidatedReceiptEmailTempId__c;  templateId = settingsRecords[0].ConsolidatedReceiptEmailTemplateId__c; 
                system.debug('Nitin dupeTemplateId===='+dupeTemplateId);
                system.debug('Nitin templateId===='+templateId);
            }
             else if(giftRecordType == 'Event Registration')
             {  dupeTemplateId = settingsRecords[0].Dupe_Event_Registration_Template_ID__c;  templateId = settingsRecords[0].Event_Registration_Email_Template_ID__c; }
           
            else 
            { dupeTemplateId = settingsRecords[0].DupeEmailTemplateId__c;  templateId = settingsRecords[0].EmailTemplateId__c; 
                system.debug('Nitin dupeTemplateId===='+dupeTemplateId);
                system.debug('Nitin templateId===='+templateId);
            }
            orgWideId = settingsRecords[0].Org_Wide_Email_ID__c;
        }
        
         
        
        
    }
    
    
    
    
}