Causeview Package Complete/ant script/retrieveUnpackaged/objects/Gift__c.object
<CustomObject>
    <description>Causeview - Any financial transactions including: gifts, product purchases, event registrations, membership renewals, etc.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Entered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acknowledged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Payment__c.object
<CustomObject>
    <description>Causeview - Payment records relating to a Transaction.</description>
    <fields>
        <fullName>Donation__c</fullName>
        <label>Transaction</label>
        <referenceTo>Gift__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Recurring_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Receipt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Single or Consolidated Receipt.</description>
        <label>Receipt</label>
        <referenceTo>Receipt__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Committed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refunded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Written Off</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Payment No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Receipt__c.object
<CustomObject>
    <description>Causeview - Tax receipt for transaction records.</description>
    <fields>
        <fullName>Gift__c</fullName>
        <label>Gift</label>
        <referenceTo>Gift__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Issued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To be Issued</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Void</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Receipt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <recordTypes>
        <fullName>Void</fullName>
        <active>true</active>
        <description>Void receipt</description>
        <label>Void</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/classes/linkPaymentsToReceiptsBatch.cls
//To link all historical payment records to existing receipts.
//Update the Receipt__c field of all the historical payment records with respective receipt Ids.

global class linkPaymentsToReceiptsBatch implements Database.Batchable<sObject> {

    global Database.Querylocator start(Database.BatchableContext BC) {
            //Query All the Gift__c records associated with Payment__c records, where the associated Payment__c records having Receipt__c field as "null".
        String query = 'Select Id, (Select Id, Receipt__c, Status__c From Recurring_Payments__r Where Receipt__c = null AND Status__c = \'Approved\'), (Select Id From Receipts__r Where Status__c != \'Void\') From Gift__c Where Id IN (Select Donation__c From Payment__c Where Receipt__c = null AND Status__c = \'Approved\')';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
            // Extract all the Payment__c records, populate the Receipt__c fields and Update the Payment__c records.
        List<Payment__c> paymentsToUpdate = new List<Payment__c>();
        system.debug('<==inside execute==>'+scope.size());
        for(sObject each : scope) {
            Gift__c gift = (Gift__c)each;
            //Added by Nitin
            if(gift.Receipts__r != null && gift.Receipts__r.size() > 0 && gift.Recurring_Payments__r.size() > 0) {
                system.debug('gift==>'+gift.Recurring_Payments__r);
                for(Payment__c payment : gift.Recurring_Payments__r){
                    system.debug('gift==>'+payment);
                    payment.Receipt__c = gift.Receipts__r[0].Id;
                    paymentsToUpdate.add(payment);
                }
            }
        }
        if(paymentsToUpdate.size() > 0)
        Update paymentsToUpdate;
    }

    global void finish(Database.BatchableContext BC) {
    }
}