Causeview Package Complete/ant script/retrieveUnpackaged/objects/givingpowerSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Causeview communication and notification templates.</description>
    <fields>
        <fullName>Recurring_Batch_Size__c</fullName>
        <defaultValue>5</defaultValue>
        <label>Recurring Batch Size</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Causeview Templates</label>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/classes/RecurringScheduler.cls
global class RecurringScheduler implements Schedulable {
    
    global void execute(SchedulableContext SC) {
        
        RollupHelper.CreateTodayRecurringBatch();
        
        decimal batchSize = 5;
        List<givingpowerSettings__c> settingsRecords = [SELECT Recurring_Batch_Size__c FROM givingpowerSettings__c WHERE name = 'settings'];
        if (settingsRecords != null && settingsRecords.size()>0) {
            batchSize = settingsRecords[0].Recurring_Batch_Size__c;
        }
        if (batchSize==null)
          batchSize=5;
          
        RecurringProcessor runningProc = new RecurringProcessor();
        Database.executeBatch(runningProc, batchSize.intValue());
    }
    
}