Causeview Package Complete/ant script/retrieveUnpackaged/objects/givingpowerSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Causeview communication and notification templates.</description>
    <fields>
        <fullName>Rollup_Batch_Size__c</fullName>
        <defaultValue>50</defaultValue>
        <inlineHelpText>Number of records that should be processed in a batch in order to recalculate total giving and first/last transaction date.</inlineHelpText>
        <label>Rollup Batch Size</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Causeview Templates</label>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/classes/DMAccountRollupScheduler.cls
global class DMAccountRollupScheduler implements Schedulable {
  global void execute(SchedulableContext SC) {
    //Limit the Batch size to givingpowerSettings__c.Rollup_Batch_Size__c, to avoid the Exception "Aggregate query has too many rows for direct assignment, use FOR loop".
    givingpowerSettings__c GPS = [Select Id, Rollup_Batch_Size__c From givingpowerSettings__c Where IsDeleted = false];
    if(GPS != null && GPS.Rollup_Batch_Size__c != null && GPS.Rollup_Batch_Size__c > 0) {
        Database.executeBatch(new RollupBatchForOrganization(), (Integer)GPS.Rollup_Batch_Size__c);
        //Database.executeBatch(new DMAccountRollups(), (Integer)GPS.Rollup_Batch_Size__c);
    } else {
        Database.executeBatch(new RollupBatchForOrganization());
        //Database.executeBatch(new DMAccountRollups());
    }
  }
}