Causeview Package Complete/ant script/retrieveUnpackaged/objects/givingpowerSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Causeview communication and notification templates.</description>
    <fields>
        <fullName>DupeDocumentTemplateId__c</fullName>
        <label>Duplicate Receipt Email Document Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReceiptEmailDocId__c</fullName>
        <inlineHelpText>The ID of the document (set as public) used for Receipt Email Template</inlineHelpText>
        <label>Receipt Email Document Id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Causeview Templates</label>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Receipt__c.object
<CustomObject>
    <description>Causeview - Tax receipt for transaction records.</description>
    <label>Receipt</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Receipt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/classes/ReceiptBodyExportController.cls
public with sharing class ReceiptBodyExportController {

    public string content { 
        get {
                string retVal = '';
                Id docId = null;
                
                // read custom settings
                List<givingpowerSettings__c> settingsRecords = [SELECT DupeDocumentTemplateId__c, ReceiptEmailDocId__c FROM givingpowerSettings__c WHERE name = 'settings'];
                if (settingsRecords != null && settingsRecords.size()>0) {
                givingpowerSettings__c settings = settingsRecords[0];
                if (ApexPages.currentPage().getParameters().get('isdupe') == 'True')
                { docId = (Id)settings.DupeDocumentTemplateId__c; }
                else
                { docId = (Id)settings.ReceiptEmailDocId__c; }
            }
            
            // load document
            
            System.Debug(docId);
            try {
                retVal = DonationUtility.MergeDocument(docId, 'Receipt__c', ApexPages.currentPage().getParameters().get('rid'), 'Contact', ApexPages.currentPage().getParameters().get('cid'));
            }
            catch(Exception ex)
            {
                retVal = ex.getMessage() + ' doc id: ' + docId + ' recipientType=Contact' + ' recipientId=' + ApexPages.currentPage().getParameters().get('cid');
            }
            //return
            return retVal;
        }
    }
    
    /*public Receipt__c recipient { get; set; }    
    public Contact relatedTo { get; set; } 
    */
    
    public ReceiptBodyExportController () {
        
    }
}