Causeview Package Complete/ant script/retrieveUnpackaged/objects/Volunteer_Application__c.object
<CustomObject>
    <description>Used to manage and review the Applications submitted by Volunteers</description>
    <fields>
        <fullName>Volunteer_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to populate MyGroups</description>
        <inlineHelpText>Used to populate MyGroups</inlineHelpText>
        <label>(Dep) Volunteer Opportunity</label>
        <referenceTo>Volunteer_Opportunity__c</referenceTo>
        <relationshipLabel>Volunteer Applications</relationshipLabel>
        <relationshipName>Volunteer_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The ID of the Volunteer Role the application is related to.</description>
        <inlineHelpText>The Volunteer Role that the Application is matched with</inlineHelpText>
        <label>Volunteer Role</label>
        <referenceTo>Volunteer_Role__c</referenceTo>
        <relationshipLabel>Volunteer Applications</relationshipLabel>
        <relationshipName>Volunteer_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Application</label>
    <nameField>
        <displayFormat>VA-{000000}</displayFormat>
        <label>Volunteer Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Volunteer_Opportunity__c.object
<CustomObject>
    <description>Used to track and manage the various Volunteer Opportunities within the Volunteer application.</description>
    <label>Volunteer Opportunity</label>
    <nameField>
        <label>Volunteer Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Volunteer_Role__c.object
<CustomObject>
    <description>Used to track and manage the required Volunteer Roles within the Volunteer Opportunities in the Causeview Volunteers application</description>
    <fields>
        <fullName>Volunteer_Opportunity__c</fullName>
        <inlineHelpText>The Volunteer Opportunity that the role is related to</inlineHelpText>
        <label>Volunteer Opportunity</label>
        <referenceTo>Volunteer_Opportunity__c</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Volunteer_Positions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Volunteer Role</label>
    <nameField>
        <label>Volunteer Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/classes/testSetTraining.cls
//Test SetTraining Trigger
@isTest
Public class testSetTraining{
                            
    static testMethod void testTrigger() {
        Volunteer_Opportunity__c vo1 = new Volunteer_Opportunity__c();
        Insert vo1;
        Volunteer_Role__c vr1 = new Volunteer_Role__c(Volunteer_Opportunity__c=vo1.Id);
        Insert vr1;
        Volunteer_Application__c va1 = new Volunteer_Application__c(Volunteer_Role__c=vr1.Id);

        Test.startTest();
        Insert va1;
        Test.stopTest();
    }
}