Causeview Package Complete/ant script/retrieveUnpackaged/objects/Volunteer_Application__c.object
<CustomObject>
    <description>Used to manage and review the Applications submitted by Volunteers</description>
    <fields>
        <fullName>Number_of_Service_Hours_Involved__c</fullName>
        <description>Service hours involved in the volunteer role</description>
        <formula>Volunteer_Role__r.Number_of_Service_Hours_Involved__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number of Service Hours Involved</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Volunteer_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The ID of the Volunteer Role the application is related to.</description>
        <inlineHelpText>The Volunteer Role that the Application is matched with</inlineHelpText>
        <label>Volunteer Role</label>
        <referenceTo>Volunteer_Role__c</referenceTo>
        <relationshipLabel>Volunteer Applications</relationshipLabel>
        <relationshipName>Volunteer_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Application</label>
    <nameField>
        <displayFormat>VA-{000000}</displayFormat>
        <label>Volunteer Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Volunteer_Role__c.object
<CustomObject>
    <description>Used to track and manage the required Volunteer Roles within the Volunteer Opportunities in the Causeview Volunteers application</description>
    <fields>
        <fullName>Number_of_Service_Hours_Involved__c</fullName>
        <description>Sum of the duration (hours) for all existing Volunteer Position Shifts for the Volunteer Role.</description>
        <label>Number of Service Hours Involved</label>
        <summarizedField>Volunteer_Shift__c.Duration_Hours__c</summarizedField>
        <summaryForeignKey>Volunteer_Shift__c.Volunteer_Role__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Role_Status__c</fullName>
        <description>The status of the Volunteer Role (Proposed, Open - Public, Open - Private, In Screening, Filled, Completed, Cancelled, Closed)</description>
        <inlineHelpText>The status of the Volunteer Role</inlineHelpText>
        <label>Role Status</label>
        <picklist>
            <picklistValues>
                <fullName>Proposed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open - Public</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open - Private</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Screening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Filled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volunteer_Supervisor_Email__c</fullName>
        <description>The email of the User supervising the volunteer work.</description>
        <formula>Volunteer_Supervisor__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Volunteer Supervisor Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Volunteer_Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The ID of the User supervising the volunteer work</description>
        <label>Volunteer Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Volunteer_Positions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Role</label>
    <nameField>
        <label>Volunteer Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/classes/CMyPosition.cls
public class CMyPosition {
    public List<Volunteer_Application__c> theApps { get; set; }    
    public Set<String> thePosIds{ get; set; }
    public List<Volunteer_Role__c> pastPositions { get; set; }
    public List<Volunteer_Role__c> currentPositions { get; set; }
    public List<Volunteer_Role__c> futurePositions { get; set; }        
    
    public CMyPosition() {
        thePosIds = new Set<String>();
        theApps = VolunteerUtil.getAppsFromUser(UserInfo.getUserId());
        for (Volunteer_Application__c va : theApps)
        {
            thePosIds.add(va.Volunteer_Role__c);
        }
        List<Volunteer_Role__c> thePos = [SELECT Role_Status__c, Volunteer_Supervisor_Email__c, Name,Volunteer_Supervisor__r.Email, Volunteer_Supervisor__r.Name,   Number_of_Service_Hours_Involved__c FROM Volunteer_Role__c WHERE Id IN :thePosIds];
        pastPositions = new List<Volunteer_Role__c>();
        currentPositions = new List<Volunteer_Role__c>();
        futurePositions = new List<Volunteer_Role__c>();                
        for (Volunteer_Role__c vp : thePos)
        {
            if (vp.Role_Status__c == 'Completed') { pastPositions.add(vp); }
            if (vp.Role_Status__c == 'Filled') { currentPositions.add(vp); }
            if (vp.Role_Status__c == 'In Screening') { futurePositions.add(vp); }                        
        }
    }
}