Causeview Package Complete/ant script/retrieveUnpackaged/objects/Volunteer_Opportunity__c.object
<CustomObject>
    <description>Used to track and manage the various Volunteer Opportunities within the Volunteer application.</description>
    <label>Volunteer Opportunity</label>
    <nameField>
        <label>Volunteer Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/objects/Volunteer_Role__c.object
<CustomObject>
    <description>Used to track and manage the required Volunteer Roles within the Volunteer Opportunities in the Causeview Volunteers application</description>
    <fields>
        <fullName>Role_Locale__c</fullName>
        <description>The areas that the role requires the Volunteer to travel to</description>
        <inlineHelpText>The areas that the role requires the Volunteer to travel to</inlineHelpText>
        <label>Role Locale</label>
        <picklist>
            <picklistValues>
                <fullName>To be defined by organization</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Volunteer_Opportunity__c</fullName>
        <inlineHelpText>The Volunteer Opportunity that the role is related to</inlineHelpText>
        <label>Volunteer Opportunity</label>
        <referenceTo>Volunteer_Opportunity__c</referenceTo>
        <relationshipLabel>Volunteer Roles</relationshipLabel>
        <relationshipName>Volunteer_Positions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Volunteer Role</label>
    <nameField>
        <label>Volunteer Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Causeview Package Complete/ant script/retrieveUnpackaged/classes/GroupWrapper.cls
public class GroupWrapper {
        public Volunteer_Opportunity__c theOpp {get; set;}
        public List<Volunteer_Role__c> thePositions {get; set;}
        public String locations {get; set;}
        
        public GroupWrapper (Volunteer_Opportunity__c Opp, List<Volunteer_Role__c> Positions) {
            theOpp = Opp;
            thePositions = Positions;
            locations = '';
            Set<string> locs = new Set<String>();
            for (Volunteer_Role__c vp : Positions)
            {
                if (vp.Role_Locale__c!= null) 
                { 
                    List<String> locations = vp.Role_Locale__c.split(';');
                    locs.addAll(locations);
                }
            }
            for (String str : locs)
            {
                if(str == null || str == '') { continue; }
                locations += (str + ';');
            }
        } 
    }